- web/css/index.css
Fixes #225.
Allow sentence-box to grow by just setting min-height instead
of height.
> Grow green containers vertically to fix overflow

- web/src/lib/components/pages/faq.tsx
Tried to eliminate confusion about the dataset's license, as expressed in [a thread on Discourse](https://discourse.mozilla-community.org/t/sharing-the-dataset/17390). I found issue #7 where CC-0 is mentioned.
Is the thing I wrote about the free download true? How are you going to provide a download if you don't mind me asking? I suppose it will be a huge amount of data.
> Clarify dataset license in FAQ

- server/src/lib/db/mysql.ts
- server/src/lib/utility.ts
When an empty string was specified as the password in config.json, then [the createDb.js script](https://github.com/Omniscimus/voice-web/blob/4386d083f4a12a1260e2a29ee6a26030b60492fe/tools/createDb.js) failed with the following error:
`database create error ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)`
The cause of this error was that empty strings are evaluated to `false` by JavaScript and TypeScript. [In the mysql.ts file](https://github.com/Omniscimus/voice-web/blob/4386d083f4a12a1260e2a29ee6a26030b60492fe/server/src/lib/db/mysql.ts#L37), config values were determined using the OR-operand. If one of `options.password` or `config.MYSQLPASS` was an empty string, then it was ignored, and the next one was used.
Fixed this by explicitly checking if …
> Fix MySQL error if using empty password

- gulpfile.js
- package-lock.json
- package.json
Result after applying #406 (Promise polyfill so the page could be loaded successfully) and this PR on IE 11 on Windows 10:
(more or less fixes #182 maybe?)
Essential step is cssnext where it transforms usage of new CSS features into older ones as supported by older browsers. Current settings is set to be "last 2 versions", hopefully it is enough to capture the majority of users of this project.
I also removed "gulp-clean-css" in favor of "cssnano" because cssnano could be used as plugin of postcss.
> Change gulp compile CSS step to use postcss, cssnext, and cssnano

- web/css/index.css
Elements with `display: inline-block` could introduces a space between elements: https://stackoverflow.com/q/5078239
Looks better now? Fixes #164
> Fix issue with record button not centered

- README.md
The Travis CI status badge currently does not link to the Travis CI builds (when clicking it, you only get the badge image in a new tab).
This uses the recommended markdown snippet from Travis to show the badge, and at the same time make it a link to the build project itself.
> Add link to Travis CI build to the build status badge

- web/css/index.css
Since the Discource link was moved from the footer link list to the contributions/community bar, the remaining four links in the footer looked like they were "left hanging" there.
So I made a small tweak to align them evenly horizontally, to the width of the line below them.
I implemented this using [CSS flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) for the immediate container of the links. This "new" CSS feature is currently supported by [over 80% of users' browsers according to caniuse.com](https://caniuse.com/#feat=flexbox), so I think it's safe to put in.
**Note:** Semi-unintentionally, this also changes the layout of the footer links on mobile, from a vertical list to a horizontal list (see screenshots below). I think the …
> Make footer links evenly spaced horizontally

- web/src/lib/components/listen-box.tsx
This is a fix for the `Invalid URI. Load of media resource failed.` error in the Firefox console when loading the app (#397).
If the listen boxes were disabled, the `src` attribute of its `audio` element had the value of an empty string. This is invalid, because the src attribute on media elements must always contain a valid, non-empty URL if it is present ([source](https://html.spec.whatwg.org/#attr-media-src)).
> Fix Invalid URI errors in Firefox console

- server/src/lib/clip.ts
S3 buckets in newer AWS regions require the v4 signature version, although the older ones support v2.  The default region used in voice-web is older and thus does handle v2 but for anyone who switches to use buckets in a newer region will run into errors with the signature, as explained in issue #448.
This fix simply explicitly adds the v4 signature version so it works on all regions.
> Fix for issue #448 - include AWS signature version to enable S3 buckets in new regions

- web/src/lib/components/pages/record.tsx
Fixes #384.
I added client-side volume and length checks on recordings. If a recording is invalid, the user has to re-record it.
At the moment, the user doesn't get notified about what's wrong with the recording. I'm not great at UI. Can someone help me to [make some kind of alert appear](https://github.com/Omniscimus/voice-web/blob/75117895b4d8983aa1af8b0d099f2b20103431e2/web/src/lib/components/pages/record.tsx#L137) to notify the user?
Also, thoughts about the length bounds (>0.4s and <10s)?
> Recording sense checks

- nubis/puppet/web.pp
Fixes #103. The CSP header may be important for security (XSS prevention), especially when more user-generated content will be displayed to other users in the future, such as accent information. The browser will ignore content loaded from external websites, as well as inline scripts and CSS.
Couldn't test this properly due to #315. I did test the header by adding it in a meta tag to web/index.html. If the `media-src` directive is omitted, the browser refuses to load recorded audio, which appears to have a URI similar to `blob:https://voice.mozilla.org/ad3c9602-f211-4a28-88f2-f98f61bbe72f`.
Before being merged, this should be tested on a website where the Nubis stuff works. If the header contains mistakes, legitimate content may not load. I'm curious about downloading validation audio and …
> Added a Content Security Policy header

- web/css/index.css
- web/src/lib/app.tsx
- web/src/lib/utility.ts
As I started working on implementing #424, I noticed that the Safari detection was too broad (it caught macOS Safari as well).
Changes in this PR:
* restrict Safari browser detection to iOS Safari (using logic collected from [this SO question](https://stackoverflow.com/q/3007480)
* rename the detection function and CSS class to `mobile-safari` to reflect its updated meaning
* adjust CSS to show the "Open in app" banner at the bottom of the screen on all iOS devices, not just narrow-viewport ones
* previously, it was not shown on iPads (their viewports are too wide to hit the media query that was in use)
> Restrict Safari detection to iOS-only

- server/src/lib/api.ts
- server/src/lib/clip.ts
- server/src/lib/files.ts
- server/src/lib/logger.ts
- server/src/lib/webhook.ts
- server/src/server.ts
Since the Node typings are already part of package.json (though currently in version 7, we need to remember to change this if we decide to make Node 8 the minimum supported version), parts of the Node standard library can imported with `import` already, adding type support.
I'm planning to add more typings for other libraries used, but that will go in a separate PR :)
> Use TS 'import' instead of 'require' where currently possible

- package-lock.json
- package.json
- server/src/lib/api.ts
- server/src/lib/clip.ts
- server/src/lib/db.ts
- server/src/lib/db/base-db.ts
- server/src/lib/files.ts
- server/src/promisify.ts
As shortly discussed with @mikehenrty in #402, this removes the dependency on `bluebird`.
The server part now uses native ES6 Promises just like the web part does.
@mikehenrty, since I have relatively little time (in particular to make changes you request), I'm creating this as a separate small PR and didn't attack introducing async/await yet. I'll follow up with that in a new PR when I can, but if someone else gets around to starting it first, I don't want to block that :)
Also, feel free to make minor adjustments yourself as you see fit :)
> Remove bluebird dependency (use native ES6 Promise instead)

- gulpfile.js
- package-lock.json
- package.json
- server/@types/mediaserver.d.ts
- server/src/lib/aws.ts
- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- server/src/lib/corpus.ts
- server/src/lib/db/mysql.ts
- server/src/lib/db/postgres.ts
- server/src/lib/prometheus.ts
- server/src/lib/utility.ts
- server/src/lib/webhook.ts
- server/src/server.ts
This further improves the server code by installing and using typings for third-party libraries, where available.
Some notes:
* no typings are available (directly or as separate packages) for the following dependencies:
* `ff`
* `proxy-agent`
* `stream-transcoder`
* `mediaserver`
* I wrote custom typings for the one function used from `mediaserver` (this need a minor adjustment of the gulp script too)
* `memorystream` was unused and therefore removed
* i replaced default/module imports with direct imports of the needed symbols, where possible and appropriate
* the `Postgres` class (in `server/src/lib/db`) seems to be unused. should it be removed?
* `SimpleGit` was previously initialized/instantiated using `new SimpleGit(PROJECT_PATH)`, even though it should be invoked as a function (not a …
> Add TS typings for (most) server dependencies

- ios/voicebank-ios-wrapper/Info.plist
- web/css/index.css
- web/index.html
- web/src/lib/app.tsx
- web/src/lib/components/pages.tsx
- web/src/lib/utility.ts
Fixes #467.
iOS Safari users were redirected to the Common Voice app in the App Store with a green banner at the bottom of the screen. I replaced this with a so-called [Smart App Banner](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html). This is a bar at the top of the screen which redirects users to the app's page in the App Store if the app is not installed yet, and it opens the app if it is.
Browsers on iOS other than Safari do not support Smart App Banners. The old bar is still in place for them. Clicking this banner previously always opened the App Store, regardless of whether the app was installed. Now, the app's page in the App Store will be opened if the app isn't …
> Improvements to the 'Open In App' bar on iOS

- web/css/index.css
- web/src/lib/components/pages/record.tsx
Closes #435 
Paired on it with @irmela 
We thought that it makes more sense to replace the record button while/if sentences are being/not loaded.
We faked the error by throwing an exception inside `getRandomSentences` in `src/lib/api.ts`.
> Display error/waiting message while sentences are not/being loaded

- docs/HOWTO_S3.md
quick fix for a type on HOWTO_S3.md. 
====
Create a new S3 bucket:
Log into your new Amazon Services account:
Choose "S3" under the "Storage" catagory in the "Services" drop down.
====
The word "catagory" was changed to "category".
Also fixed the key BUCKET_LOATION (last step in the document) to BUCKET_LOCATION.
Fix #560
> Fixed a typo in HOWTO_S3.md: 'catagory' -> 'category'

- web/src/lib/components/pages.tsx
- web/src/lib/components/pages/profile/profile.tsx
References to document.getElementById and document.queryselector inside components were replaced by attributes that are set when rendering the components by using refs.
Only preact components were reviewed. The HTML files containing pure HTML elements not rendered by a preact component were not modified (i.e. voice-web/ios/voicebank-ios-wrapper/index-cv.html)
resolves #541
> Replace getElementById or queryselectors inside preact components by refs during rendering

- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- web/src/lib/api.ts
- web/src/lib/components/pages/listen.tsx
- web/src/lib/components/validator.tsx
Minor cleanup:
* remove unused `Clip` type from web code
* rename some things called "ClipJson" to just "Clip" to reflect they're not actually passing around JSON anymore
* other minor cleanup of the modified code passages
> Remove unused `Clip` type and improve naming related to ClipJson

- web/src/lib/components/pages/profile/profile.tsx
In preparation of #550, I went ahead and refactored profile a bit. It's 40 lines shorter now, just want to make sure I didn't sacrifice readability (imo I didn't but there's bound to be some subjectivity here). 
Possible points of contention:
- prefer object literal shorthands
- prefer `const` over `let`
- extracting state into local vars in render
Uncontroversial parts of this PR:
- directly access select values
- remove `Component.render()`-call
- extract options renderin into its own method
> Profile Refactor

- web/index.html
- web/src/lib/app.tsx
This improve page load UX by keeping the spinner in the DOM until them `#main` content is considered ready (images are pre-loaded or timeout occurred) and the fade-in transition is done.
It also replaces two `setTimeout` calls used for this with usage of our own Promise-based `sleep(ms)` utility function, improving code readability.
Short preview video: <a href="https://www.dropbox.com/s/bdq5h9zkfkr6arh/load-spinner.mov" target="_blank">on Dropbox</a>
> Improve page loading UX by letting content fade in over spinner

- web/src/lib/components/pages/record/audio-ios.ts
- web/src/lib/components/pages/record/audio-web.ts
- web/src/lib/confirm/confirm.ts
This replaces `Promise.then()` usage with async/await in the `AudioWeb` class, as part of #402.
@mikehenrty, please take a look at the remaining usages of `then()` in the web part of the code. I would actually leave them as they are, because they intentionally spawn off asynchronous actions and don't directly wait for them.
Introducing async/await in their place would pull up the Promise another call, and require changes in more places. In contrast to our goal with #402, this would actually degrade readability IMO.
> Use async/await in AudioWeb class

- nubis/puppet/web.pp
Add settings to Apache's configuration file to compress js, css, and svg files. This fixes #562.
It looks like your site serves javascript with the "application/javascript" content type, but I left the "text/javascript" content type in there just to be on the safe side.
> Fix #562: Modify apache config to compress js, css, and svg files.

- web/src/lib/components/listen-box/listen-box.tsx
- web/src/lib/components/pages/record/profile-actions.css
- web/src/lib/components/pages/record/record.css
- web/src/lib/components/pages/record/record.tsx
- web/src/lib/components/pages/record/review.css
Switched to conditionally rendering either recordings view or the review submissions view. This should fix the whitespace issues. Also we need less arbitrary offsetting of the submissions view like before.
But a problem that came up is the audio element inside of `ListenBox` not triggering `onCanPlayThrough` after re-recording. I "fixed" this, by setting `loaded` to `true` by default (it gets set to `false` when loading starts, so we should be good?!). Maybe you have an idea about that @mikehenrty?
> Fix whitespace issue on record page

- web/src/components/index.css
Fixes issue #720. Tested in Firefox and Chrome on Android. Screenshot:
> More spacing below robot on homepage (issue #720)

- web/src/components/profile-form/profile-form.css
Fixes issue #716 by changing the wrapping div to flex-direction: column
and centering the "Create a Profile" header when on mobile. Screenshot:
> Move "Delete Profile" link to its own line

- web/src/components/nav.css
This PR intends to fix #715.
1. Removes the padding around the lines of links and adds some padding
above them.
2. Removes the padding around the content div, except on the bottom.
This is replaced by padding on the entire moz-links section of the
footer, which creates the padding around the bottom box and keeps
everything nice and neat.
Screenshot:
> Tweak footer styling

- web/src/components/nav.css
Menu items had padding at the top and bottom. Therefore the first item was closer to the top, than it was from the second item.
Before:
After:
Fixes: https://github.com/mozilla/voice-web/issues/718
> [Mobile] Pad menu items from the top.

- web/src/components/nav.css
Intends to fix issue #714 by removing the dividers, reducing icon and text size by 20%, and making the subfooter shorter. These changes only apply on mobile devices. Screenshot:
> Tweaks to help links subfooter

- web/src/components/pages/record/review.css
Hi,
I jumped on and addressed the two comments in #672 as my first PR as part of the Open Mozilla Night. Hope that's OK! 
Namely:
* Increasing button height
* Making the 'Cancel Submission' text semi-bold instead of bold.
<br/>
> Touch up submit record button, fixes #672 

- nubis/terraform/main.tf
- nubis/terraform/users.tf
- Don't hard-code a resource's name, instaed build it up with environment, region, etc
- link resources with their internal IDs instead of hard-coding names
> Handle multiple environments for aws_db_parameter_group

- nubis/puppet/files/upstart.logrotate
- nubis/puppet/logs.pp
Also, cleanup .pos files
Works around fluent/fluentd#1734
Fixes #847
> Replace Ubuntu's default upstart logrotate config with one that restarts fluent's td-agent afterwards

- l10n.toml
- web/locales/en/messages.ftl
I can drop the change to single unicode character if you prefer, but that's what is usually used across Mozilla projects.
The new FTL syntax also has an equal sign when the value is empty
```properties
foo =
.title = bar
```
**l10n.toml**
You can use it get the status of locales, find errors, etc.
Install [compare-locales](https://pypi.python.org/pypi/compare-locales), then run `compare-locales l10n.toml . en ab-CD` (where `ab-CD` is a locale code). You can also run it on multiple locales, as part of automation, etc.
CC @pike
> Improve FTL and l10n support

- web/src/components/pages/record/record.css
- web/src/components/pages/record/record.tsx
- Wrap the "sentences are being loaded" error message in a `<div>` and `<p>`
that give it a solid background, as well as fading the text to give a
visual indication that something is missing. This is the same as what
the validation box does when there are no sentences to validate.
- Remove the "1 of 3" text when there are no sentences to read.
> Fix issue #828: When sentences can't be loaded, the error message displays improperly.

- web/src/components/listen-box/listen-box.tsx
The `return` statement blocked further code execution, which is why user needs to click twice in order to rerecord. Essentially, the first time for "pausing" the playback, and the second time to actually switch view to rerecord.
> fix: #608 expect to one touch and do rerecord

- web/locales/en/messages.ftl
- web/src/components/layout/nav.tsx
- web/src/components/pages/home/project-status.tsx
- web/src/services/localization.ts
- get list of "completed" locales from `completed_locales.json` (which is updated by running `import-pontoon-locales.json` based on locales with >= 95% translation)
- show Languages in Nav
- show Help Translate Modal on Home
> Enable multi-language on production

- web/src/components/modal/modal.css
This seems to resolve a display issue (#990) that I investigated with @mikehenrty at the voice sprint.
The `display-table` property here causes an issue where text flow on the language flows off the bottom of the modal you can see this in the screenshot from #990 (this affected mobile firefox and chrome when we looked into it together):
Removing the `display-table` property resolves it, but I understand this to be used for vertical centering normally, and I'm not sure what layouts this is likely to affect.
Is there chance someone give me an idea of where i might look, to see if fixing this issue breaks things elsewhere?
> WIP - Remove display-table to on modal css to resolve issue 990

- contribute.json
Added **"urls"** and "repository":{**"tests"**}. Also changed "participate":{"chat"} to "participate":{"slack" and "slack-invite"}.
This was done based on issue #1003 and following advise from @Gregoor.
> Some keys required by ObsMoz added to contribute.json

- server/data/de/jf99.txt
- server/data/fr/gerard-majax.txt
- web/locales/kab/messages.ftl
@mikehenrty This should fix the punctuation characters that went missing due to the script's bug.
I also fixed around 3 other small issues in German, I stumbled upon.
It would be nice, if we could find someone that speaks french to take a short look at this, I'm not 100% sure, if this many exclamation marks are accurate.
For German the exclamation marks have just been restored from @jf99 's file
> Fixed punctuation marks in german and french sentences

- server/data/fr/ofis_publik_ar_brezhoneg.txt
This is based on PR #1139.
I took @Booteille 's commit, rebased it to master to resolve conflicts and added my own commit on top to:
-  Fix other spelling/grammar errors
-  Remove duplicates
-  Cut long sentences
-  Keep valid (but unusual) spelling according to the "rectifications orthographiques du français en 1990"
-  Add missing punctuation
-  Add capital letter at the start of sentences
-  Convert numbers to words
-  Remove parenthesises and slashes
@lissyx if you want to have a look at it before @mikehenrty merges it.
When this is merged, PR #1139 can be closed.
> Fix french sentences

- web/src/components/index.css
The way the text broke due to the font size on my smartphone looked kinda ugly, so I adjusted the font size:
Before:
After:
I'm using Firefox on a 1080x1920 screen, Firefox seems to use 400x660 as the size/aspect ratio for the view port
EDIT: I know this is only the case in german, but other languages don't look worse with this imo, so it should be ok.
French is also in 3 lines btw. but remains in 3 lines with this patch, but those 3 lines are filled with text
another success:
English fits on 3 lines instead of 4 on 320x480
Another change that could be done:
.contribution-banner .open {
min-height: 120px;
}
instead of 150px would look better in English on 320x480 btw.
In german it doesn't make any difference (looks good both ways)
In french the bug report string is too long for both links …
> decrease contribution banner font size

- server/data/de/countries-and-cities.txt
- server/data/de/german-cities.txt
- server/data/de/jf99.txt
Not so sure about the year numbers. In other files, they are written without hyphens.
neunzehn-hundert-achtzehn vs. neunzehnhundertachtzehn
Sure, it's easier to read with hyphens, but I think without them is the formerly correct way. Also, we should probably have a consistent way to write such year numbers.
Shall I remove the hyphens?
> more corrections in German

- server/data/de/jf99.txt
Das Adjektiv „trainiert“ darf nicht mit einem Komma von seinem Bezugswort getrennt werden. Deutlicher wird dies, wenn man schreibt: *Wenn trainierte neuronale Netze träumen, …*
Wenn man das als eingeschobenen Nachtrag (siehe [§ 77(7)](https://grammis.ids-mannheim.de/rechtschreibung/6201#par77)) auffassen würde, müsste man zwei Kommas setzen und den Satz wahrscheinlich umstellen: *Wenn neuronale Netze, auf Bilderkennung trainiert, träumen, …*
> [German data] punctuation fix

- server/data/de/countries-and-cities.txt
- server/data/de/est31.txt
A wrong article, a comma and wrong tense.
> 2 minor corrections for German

- server/data/nl/danielsjf.txt
- server/data/nl/pcmill.txt
* "qwerty toetsenbord" should be "qwertytoetsenbord". [(ref.)](http://woordenlijst.org/#/?q=qwertytoetsenbord)
* If a sentence starts with «'s», the second words should be capitalized. [(ref.)](https://taaladvies.net/taal/advies/vraag/1600/s_avonds_s_avonds_hoofdletter/)
* "Één" should be "Eén". [(ref.)](https://onzetaal.nl/taaladvies/accenten-op-hoofdletters/)
* "second" should be "seconde". [(ref.)](http://woordenlijst.org/#/?q=seconde)
* "tweede wereld oorlog" should be "Tweede Wereldoorlog". [(ref.)](http://woordenlijst.org/#/?q=Tweede%20Wereldoorlog)
* "fastfood tent" should be "fastfoodtent".
* "Ik vindt" should be "Ik vind".
* "email" should be "e-mail". [(ref.)](https://www.taaladvies.net/taal/advies/vraag/1144/)
* "internet verbinding" should be "internetverbinding". …
> Fixed grammatical and orthographic errors in the Dutch files

- package.json
- web/src/components/listen-box/listen-box.tsx
- web/src/components/normalized-player.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- yarn.lock
Fixes #1498.
Should have safari support now by using the promise-decode-audio-data package the way its author described in [this gist](https://gist.github.com/mohayonao/89fd55526cef5a60364e860695a4bf75). But please test it because I don't have any safari lying around to test it. I've tested it on Firefox though and here normalization works again!
> Bring back normalization

- server/package.json
- server/src/config-helper.ts
Currently non-dualstack S3 endpoints are used, meaning that requests are made only over IPv4, even if the user's browser would prefer IPv6.
> Use dualstack for S3

- web/locales/en/messages.ftl
- web/src/components/pages/faq.tsx
@Gregoor r?
I had to bump both question and answer strings, which is not ideal. This might need some re-thinking :)
However, I think a bump is necessary to make sure the other languages get "re-translated" and can include the tag in the translation.
> Add missing FAQ link to GitHub source folder (fixes #1711)

- web/src/stores/demographics.ts
Originally received the report here: https://www.meetup.com/Berlin-Mozilla-Meetup/events/257383300/
Currently the accents do not list "Turkish German", but they list some others. Given the amount of Turkish people living in German speaking countries, I agree with Mehmet that adding this would make sense.
> Add Turkish German to list of accents

- web/src/components/pages/contribution/listen/listen.tsx
Fixed: #1217 
I think this quick fix should solve this bug.
> Fixed: Clicking Yes/No control doesn't stop the playing audio

- server/data/it/frasi.txt
We worked on cleaning, fix typos and remove duplicates.
> Another italian review to improve the sentences

- server/data/eo/proverbaro.txt
In Esperanto apostrophes are used as ellision marks mainly in literature and songs, for metrical reasons[1][2]. Only one normal usage of the ellision is in widespread use, in the idiomatic sentence "dank'al".
Because the Common Voice database is a tool to help voice recognition, and since in normal conversations speakers do not use the ellisions, this pull request changes all the apostrophized words to the actually spoken forms.
[1] https://en.wikipedia.org/wiki/Apostrophe#As_a_mark_of_elision
[2] https://bertilow.com/pmeg/gramatiko/apostrofo/normala_uzo.html
> Please remove apostrophes

- web/src/stores/demographics.ts
Chinese is Hong Kong's official language, and traditional characters are their de facto writing standard. (Hong Kong are the second large zh-tw Firefox usage place besides Taiwan.) 
They plan to promote Common Voice soon.
> add Hong Kong to zh-tw accents

- CONTRIBUTING.md
The keys for use with Auth0 had a slight mismatch between the keyname given (SECRET) and that in the code (CLIENT_SECRET) so simply clarifying that here in this minor update
> Clarify format of Auth0 credentials

- web/src/components/ui/ui.css
* Closes #2025 
The color had to be changed from `--black` to `--near-black` because:
1. Both `Safari & Chrome` fail to show the **checkmark**. 
2. Using `-webkit-fill: var(--near-black)` to create a specialized case for *WebKit* browsers and retaining style for others did **NOT** work. 
This essentially undoes 3271508c .
> Revert fill to near-black for visibility in Chrome & Safari

- web/src/components/pages/datasets/dataset-info.tsx
I clicked checkboxes below, but check marks don't appear.
I found `"checked"` property was not passed to the checkbox components, so I fixed it.
(In addition, I fixed react "key" warning of list)
> Fix "checked" property of checkboxes

- nubis/terraform/metrics.tf
Actually only one global IAM role is needed in order to get the metrics. However having only one, would make Jenkins prod fail trying to create that role and finding that it already exists.
One option could have been manually importing the role into the Terraform state, but in case we want to start from scratch with the same Terraform code, it will fail. That's why I went for creating 2.
> Create one role per environment

- web/package.json
- web/src/components/layout/layout.tsx
- web/src/components/welcome-modal/wave-grey.svg
- web/src/components/welcome-modal/welcome-modal.css
- web/src/components/welcome-modal/welcome-modal.tsx
- web/src/react-balance-text.d.ts
- yarn.lock
This commit adds a skeleton welcome modal for the upcoming partner challenge. Because the Open Voice Challenge is not yet underway, the modal is gated behind an `!isProduction()` check.
NOTE: The modal still needs to be:
- linked to an updated T&C, and
- hooked up to a working signup endpoint.
Test plan:
- Navigate to localhost:9000/?ovchall=1
Modal should pop up. Button should be disabled.
- Check the T&C box.
Button should be enabled.
- Click the button.
Page should redirect to /login.
> Add a welcome modal for the Open Voice Challenge

- web/src/components/invite-modal/invite-modal.tsx
- web/src/components/onboarding-modal/onboarding-modal.tsx
- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/welcome-modal/welcome-modal.tsx
Test plan:
- `yarn prettier`
- `yarn test`
- Navigate to localhost:9000?challenge=pilot
An analytics event with:
`{action: "modal-welcome", category: "Challenge", locale: undefined}`
should be logged.
- etc.
> Add GA tracking events to the Open Voice Challenge

- server/src/server.ts
Our AWS-hosted Kibana instance cannot support multiple user role
settings, eg. Admin and Contributor. We would eventually like to run our
own self-hosted instance, but for now this plugs the security hole
introduced by allowing anyone full admin / write access to Kibana.
> Block Kibana access from anyone outside of ADMIN_EMAILS

- web/src/components/layout/layout.tsx
- web/src/components/welcome-modal/welcome-modal.tsx
This commit lets the Open Voice Challenge's welcome modal accept dynamic values
from query strings, disregard invalid params, and handle valid params.
Test plan:
- `yarn test`
- `yarn prettier`
And...
- Navigate to http://localhost:9000/en?challenge=oiyu
Modal should not open.
- Navigate to http://localhost:9000/en?challenge=pilot
Modal should not open.
- Navigate to http://localhost:9000/en?challenge=pilot&team=ibm
Modal should open. All mentions of the team should be capitalized properly ("IBM").
- Click the "I agree..." checkbox.
- Click the "Join..." button.
Page should redirect to `/login?challenge=pilot&team=ibm`.
> Remove placeholder content from the welcome Modal

- server/src/auth-router.ts
- server/src/lib/api.ts
- server/src/lib/model/db/migrations/20191107232609-add-referer-to-challenge-enrollment.ts
- server/src/lib/model/user-client.ts
When we analyze our signup data, we might want to know where users came
from when they initially signed up. Tracking the HTTP `referer` header
on `enroll` entries is a lightweight way to do so.
> Add HTTP referer string to challenge enrollments

- server/src/lib/model/db/migrations/20191108184707-add-pilot-challenge-data.ts
This commit finalizes the pilot name, competing teams, and available
achievements. As we're starting QA next week, it is important to have
these in place on all of our DBs.
The repeated subqueries aren't pretty, but it reads nicely as a template
string and we don't need to worry about performance on such a small job.
> Seed the 2019 Pilot with challenge+team+achievement data

- web/src/components/layout/footer.css
- web/src/components/layout/subscribe-newsletter.css
Issue in focus: #2212 
The footer used to get cropped in smaller viewports as seen in the issue #2212 - the renders of the previous scenario can be seen there.
* iPad emulation on chrome
* iPad emulation on Firefox
* Desktop view - 1080p screen
* The cropping began around 1190px which was almost equal to the CSS variable  `--xl-up`
* Certain elements were centered to match up with the other elements of the UI
*  `max-width: 260px;` was added to the links box as it is the same width the box transitioned to once the media query kicked in. If this is removed, the box stretched with an approximate 95% width (100% - margin) which didn't look aesthetically pleasing.
This is my first time contributing to this repository. In case something needs to be changed or a different approach needs to be …
> UI: Fixed footer UI issue on iPad

- web/src/components/pages/profile/info/info.tsx
Test plan:
- Enroll in the challenge
- Navigate to http://localhost:9000/en/profile/info
- Click the "Leaderboard Visibility" dropdown
"Visible within challenge team" option should appear.
- Select "Visible within challenge team"
- Click "Save"
- Navigate to http://localhost:9000/en/dashboard/challenge?date=2019-11-24
- Click the eyeball in one of the leaderboards
"Visible" / "Visible for team only" should be selected.
> Fix #2290: Add "Visible within challenge team" option to profile page

- server/src/config-helper.ts
- server/src/server.ts
Separated Kibana admin list into its own property. The server-side `config.json` doesn't have these new emails in ADMIN_EMAILS and it was overriding the defaults, but it should leave KIBANA_ADMINS alone since it doesn't specify anything for that. TODO: figure out how to update server-side `config.json`.
> Give community access back to Kibana

- web/src/components/onboarding-modal/onboarding-modal.css
- Set the `close` button grey
- Move the `robot` icon down
- Reduce the margin between buttons
> Fix #2283: Improve onboarding modal display

- web/src/components/invite-modal/invite-modal.css
- web/src/components/modal/modal.css
Add `opacity` to the `close` button and change the color of the `Copy link` button.
> Fix #2284:  Modify invite modal styles

- web/src/components/pages/dashboard/challenge/challenge-list.tsx
- web/src/components/pages/dashboard/challenge/team-card.tsx
For now, the data structure for the top team from the back-end is like below:
``` json
[{
"position":0,
"id":13,
"name":"SAP",
"w1_points":"100",
"w1":"1",
"w2_points":"100",
"w2":"1",
"w3_points":"100",
"w3":"1",
"nextRank":2,
"avatarClipUrl":null,
"clientHash":"***",
"you":false
}]
```
`w1,w2,w3` is the weekly ranking of a team separately. But for the front-end,  I need to show the ranking of the current week
> Fix: Team progress ranking display should depend on the current week

- web/src/components/index.css
- web/src/components/register-section/register-section.css
Added a quick CSS rule to hide overflow-x that fixes #2239. @Gregoor @rileyjshaw please take a look.
> Fix horizontal overflow

- common/challenge.ts
- server/src/auth-router.ts
- server/src/lib/api.ts
- server/src/lib/model/user-client.ts
- web/src/components/welcome-modal/welcome-modal.tsx
TIL [`document.referrer`](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) is standard across all major browsers, and reports the same value we would see on the server. This reduces the headache of sending it from the server, to the client, back to the server, that we were discussing earlier.
This change means we'll get the original inbound referer, and will hopefully catch more sources like Twitter, Facebook, etc. Fingers crossed!
Note: Referrer? Referer? Typo [theirs](https://tools.ietf.org/html/rfc1945#section-10.13), not mine :)
> Improve challenge referer tracking

- server/src/lib/model/achievements.ts
This is a tiny change for a big bug, so here's my logic as to what's happening: 
* The clips are still being stored in the db and uploaded to S3
* If you comment out the upload code locally (153-215 in `server/src/lib/clip.ts`) you can fake submitting clips without actually uploading
* A faked submission gave me the following error: 
`web        | [BE] TypeError: Cannot destructure property `earned` of 'undefined' or 'null'.`
`web        | [BE]     at Object.exports.hasEarnedBonus (/code/server/src/lib/model/achievements.ts:122:26)`
`web        | [BE]     at <anonymous>`
`web        | [BE]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)`
Fake submissions work now on my local. The intermittentness of the error, and particularly why Lindsay and I were able to submit …
> Fix type error on achievements sql

- server/src/lib/model/user-client.ts
Another simple fix! Rationale: 
* there are zero duplicate emails within the realm of `has_login = true`
* the `findClientId` method from Gregor uses `has_login` as a uniqueness check
* this method was last updated in the same commit that created the `has_login` field
* `has_login` is set to true anytime `saveAccount` is called
¯\_(ツ)_/¯
> Tighten query for enrolling registered users

- server/src/lib/challenge.ts
- server/src/lib/model.ts
@rileyjshaw , @phirework , if the final decision is caching only the leaderboard as we do for the original Stats dashboard and removing the cache, and the delay, for My points and Individual progress, this PR can serve the purpose.
Otherwise, we can close the PR.
> Fix #2322, fix #2337: stop caching other point requests outside the leaderboards

- server/src/lib/model/db.ts
1) signed up within the first week;
2) signed up without invited_by;
3) including the current user if it should;
Currently, the number of team invites doesn't include current user.
@rileyjshaw , I made the bold statement in the stand-up that the current code base is correct about the team invites.
I realized that I was wrong after rechecking.
> calculate the team invites more precisely:

- .gitignore
I've started through docker locally and I got the newrelic log file. I don't think we ever need that in git.
> Add newrelic_agent.log to gitignore

- web/src/components/layout/layout.tsx
Have deliberately left the CSS in case we need to restore this in the future, and have also tagged this as `tags/remove-iOS-banner` for easy referencing.
> Remove iOS banner until we know what we're doing with the app

- docker/local-docker-config.json
Small quibble of a commit, I would argue that in local dev you're much more likely to turn this off than need it on and I would like the default to be `false` just so I don't keep accidentally maxing out my system resources :P
> Set default value for importing sentences

- nubis/puppet/files/confd/templates/voice.json.tmpl
- server/src/config-helper.ts
Have already updated the `ADMIN_EMAILS` and `KIBANA_ADMINS` values via consul on both prod and stage, this just removes the PII and relies entirely on that KV store.
> Remove emails from config-helper.ts, add kibana_admins to confd template

- web/src/components/register-section/register-section.css
Registration section aligned left for niche screen size especially for devices like Kindle Fire HDX and certain other tablets
Currently there are no issues opened related t this. I thought it would be good to have consistent styling throughout for even the niche screen sizes.
In case this is an unnecessary change, please let me know and I'll close the PR. In case the changes need refinement, drop a comment below and I'll address them asap
> [web] UI: Fix alignment of registration section

- server/src/lib/challenge.ts
make current week the first week if challenge has not started yet;
make current week the last week if challenge has already finished;
This PR fixes: https://github.com/mozilla/voice-web/issues/2410
@rileyjshaw  FYI.
> challenge board will crash if challenge has finished or not started

- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
Throws an error on web when the user has canceled the image file selection. After that, the user can't select a new avatar again. I've added a condition for fixing this problem.
Scenario:
- Open the avatar page.
- Click the browse button. 
- Select an image file.
- Click the browse button, again.
- Press ESC or click the cancel.
> Add condition for checking file type

- server/src/lib/model/db.ts
In our ideal future where we have an adaptive date system living outside
of our database, we can have the weekly challenge conditions
automatically update. For now, it's easier to just push to prod at
approximately the right time... 😞
> Update Open Voice Challenge team criterea for week 2

- web/src/components/pages/contribution/listen/listen.tsx
show toast after the `async` `vote()` is returned, otherwise toast will never show up, this is done in the following steps:
1) extract the toast functionality into a separate `async `method of the same _tsx_ file,
2) use the `promise.all().then() `to make sure that the achievement attributes piggy-backed in vote request already update the `props `before showing toasts.
This is PR should resolve issue: https://github.com/mozilla/voice-web/issues/2386.
@rileyjshaw , @phirework  please take a look at it, and help to identify whether it would obviously break other functionalities.
> Fix #2386: No points earned for first Listen contribution, until all 5 are submitted

- server/src/lib/challenge.ts
- server/src/lib/clip.ts
- server/src/lib/model/achievements.ts
- server/src/lib/model/db.ts
- web/src/components/invite-modal/invite-modal.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/dashboard/dashboard.tsx
- web/src/services/api.ts
- web/src/stores/clips.ts
- prevent multiple `invite_contribute_same_session ` toasts AFTER challenge by checking challenge time under different timezone;
- change `firstInvite `to `showInviteSendToast`;
- change `hasAchieved `to `hasEarnedSessionToast`;
- change `firstContribute `to `showFirstContributionToast`;
- change `firstStreak `to `showFirstStreakToast`;
- set the default value of `challengeEnded `to true;
@rileyjshaw , as mentioned in PR: https://github.com/mozilla/voice-web/pull/2382, this PR will not show any `invite_contribute_same_session `bonus once challenge has ended.
> prevent multiple invite_contribute_same_session AFTER challenge

- package.json
- server/package.json
- web/package.json
- yarn.lock
This commit ensures that we're on the latest version of TypeScript. More
importantly, it ensures we're using the same version of TypeScript across
the application.
Also… now we can finally use [Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)! 🎉
Test plan:
- `yarn install`
- `rm -rf server/js web/dist`
- `yarn build`
- `yarn prettier`
- `yarn test`
> Upgrade TypeScript

- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/contribution/success.tsx
This addresses [the rerendering issue](https://github.com/mozilla/voice-web/issues/1295) affecting the "Ready to do 5 more" button on the success page.
I approached this by narrowing down the cause of the render, which is the result of several functions being re-declared on every render. So, by passing direct references to the properties ".resetState" and ".upload" in speak.tsx and also moving the component's creation outside of the `Success` component's render cycle, we are helping React reconcile the component properly.
This strategy might surface several other opportunities for improving performance of these components (by unnesting component functions) if that has ever been an issue.
`/en/speak`
> Fix #1295: Contribute more button rerendering

- nubis/puppet/files/confd/templates/voice.json.tmpl
- scripts/scrub-user.js
- server/src/config-helper.ts
A pretty rough and basic node command line script for deleting user profiles. 
Expected behaviour: 
* Trigger by calling `node scripts/scrub-user.js [1+ email address, separated by spaces]` from root directory
* For each email address, command line will: 
* Display a summary of the user's stats, with number of `client_id`s, number of clips, and date the first clip was submitted
* Prompt for confirmation that this user profile should be deleted
* If the user submitted clips, prompt for confirmation that the records for those clips should also be deleted
* Add those `client_id`s to `deletionSummary` object for display later
* If the first contribution from that user has been included in a past dataset, add those `client_ids` to `deletionSummary` object for display later
* Once all emails …
> Node script for profile deletion

- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/contribution/success.tsx
This addresses a new spike in Sentry error logs after the deployment to Prod on Dec 6th, and I think is related to bug #2459: 
* https://sentry.io/organizations/mozilla-q6/issues/1376071679/?query=is%3Aunresolved&sort=freq&statsPeriod=7d
* https://sentry.io/organizations/mozilla-q6/issues/1376100317/?query=is%3Aunresolved&sort=freq&statsPeriod=7d
Looking through the history of `speak.tsx` it looks like the `onReset` and `onSubmit` callbacks were intentionally passed as functions rather than references. It would be worth revisiting the purpose of the original PR to avoid re-rendering the contribute button unnecessarily, but as there is a December snippet campaign launching midnight UTC of Dec 10 I wanted to make sure core site functions were working first.
> Revert PR #2225

- web/src/components/app.tsx
* Moves our Sentry logging from a free Sentry.io instance to the paid version we get through the Mozilla Ops Sentry
* Adds an environment variable to differentiate staging and prod
* Adds release tagging for when we move to K8s
* Moves Sentry importing and initializing out of `componentDidCatch` - if I was reading that correctly it was being re-initialized with every error, which can't have been good for performance.
> Update Sentry configs

- .travis.yml
- nubis/puppet/web.pp
- package.json
- server/src/server.ts
- yarn.lock
Handle HTTP => HTTPS redirection in PROD
This is based on the X-Forwarded-Protocol header set by upstream reverse-proxies, like ELBs and the like
Fixes #2482
Depends On #2481 
Sneaking in:
- http-status-codes for human-readeable http status codes
- [travis] skip docker login when building a PR
> Handle HTTP => HTTPS redirection in prod

- web/webpack.config.js
Based on [this thread and associated links](https://github.com/webpack/webpack/issues/7502), I think we can solve all of the "failed loading chunk" issues with this setting. However, I just turned on Moz-hosted Sentry on staging, and our freebie version of Sentry never separated by environment, so I have a hard time figuring out how much that is actually an issue on staging. 
I'm just leaving this here pending all the other dependency updates, and once there's a bit more info in staging Sentry we can push this to master to test the actual impact. No rush on this.
> add hashing to bundle output

- web/src/components/pages/dashboard/goals/custom-goal.css
- web/src/components/pages/dashboard/ui.tsx
From this:
to this:
Tested on http://localhost:9000/en/dashboard/en/goals
> Fix #2447: re-center custom goals progress

- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20191219191744-add-clip-validated-at.ts
To reduce server load, we want to cache some dynamic properties on clips so we
don't need to query the votes table as often. We're already storing `is_valid`,
but knowing _when_ validation happens is also important.
This RFC includes an example of how existing queries could be simplified. See
the modified query in getClipsStats().
> RFC: Add validated_at column to clips table

- server/src/lib/model/db/migrations/20191227183100-match-clip-sentence-locale.ts
In investigating issue #2488, discovered that there are ~650 clips whose `locale_id` do not match that of the original sentence. I'm not sure why this is happening because it seems pretty intermittent: the issue happened a BUNCH on May 9th 2018, then a handful of times on June 1st 2019, July 16 2019, Oct 18th 2019, Nov 2nd 2019, Nov 23rd 2019, and then steadily but not overwhelmingly since Dec 7th. My best guess based on timing is that this might be related to server load, since the dates in Oct/Nov coincide with big bugs we had to fix, and we've been fighting server performance issues all December but I haven't been able to find anything in the code that would point to that being a problem.
In the absence of any sort of useful debugging information, I want to update all of the offending …
> Add migration script for rewriting locale_ids

- web/src/components/pages/datasets/dataset-info.css
- web/src/components/pages/datasets/subscribe.css
The background image set using CSS contained within the div instead of covering the entire background. This led to issues like:
* Displeasing UI
* The heading getting hidden in the white background
This is prominent on screens of tablet.
Before:
After:
Before:
After:
**Edit**
Issue in focus: #2520
> UI[web]: Fix background size in dataset page

- web/src/components/pages/datasets/subscribe.css
Checkbox's white background masked the tick mark.
This led to the scenario where one couldn't say whether the checkbox was clicked or not.
There is currently no open issue regarding this however this seems like an inconvenience to the users.
* Before when box was checked
* Now when the box is checked
One can clearly make out whether the checkbox is ticked in the second photo as compared to the first one where the check mark blends with the white background.
> UI[web]: Fix accessibility issue with checkbox of Newsletter subscription

- web/src/components/pages/datasets/dataset-info.css
- web/src/components/pages/datasets/resources.css
On a medium sized screen, the elements align to the left instead of the center.
There are currently no issues relating to this but the alignment looks odd on the tablet screens where the layout has elements aligning both to the left and the center.
* **Before**:
Data information:
Tiles:
* **After**
Data information:
Tiles:
> UI[web]: Fix centering on dataset pages

- web/src/components/pages/dashboard/awards/awards.css
This center aligns the heading in the `no-awards-page` section in the awards page. The page is designed to center align the paragraphs and the buttons but the heading is left aligned. This disrupts the page styling on tablet screen especially that of an iPad.
There are no issues related to this. This make the design consistent for smaller screen devices.
* **Before**
* **After**
The changes were tested using the responsive mode on Firefox 71 and Chromium 79
> UI[web]: Alignheading in awards section of dashboard

- web/src/components/pages/about/how-it-works.css
In the screenshots for #2516, icons are not properly centered on the
left edge of their corresponding textboxes. This commit updates the icon
CSS to not rely on image dimensions; they should always be properly
aligned now.
Test plan:
• Navigate to /about
• Scroll down to "How does it work?"
• Ensure icons are centered on the left edge of their textboxes, at both
desktop and mobile widths (and in any language).
> Improve alignment of "How does it work" icons on /about

- web/src/components/pages/about/get-involved.css
The Get Involved section of the About page wasn't centered once the viewport width dropped below 768px and flex-direction changed as a result of media query. The section snapped to the left. The UI inconsistency isn't noticeable much on desktop or mobile device but its much more pronounced in tablets.
Adding width:100% expands the div to the maximum width effectively centering the section.
**Issue in Focus**
There are no issues related to this PR. This fixes a small disruption in the UI making the whole page consistent with everything centered. The rogue div snapping to left is brought in line.
* **Before**
* **After**
Above, 768px, the UI is still consistent with the previous version and this doesn't break the UI anywhere.
> UI[web]: Center Get Involved sectionfor tablet viewport size

- nubis/terraform/main.tf
The `t3` instance class is the latest generation of AWS Ec2 instances, for best practise reasons we should update to this newer version.
Resolves #2540
> Adjust instance class from t2 to t3

- web/src/components/layout/footer.tsx
Addresses https://jira.mozilla.com/browse/OI-1446
Before:
After:
> Move GitHub link from pre-footer to footer

- web/src/components/pages/contribution/report/report.css
Fixing the length of TextArea in the report section, such that it will set Textarea within the layout.
> Setting TextArea maximum width (fixes #2587)

- CONTRIBUTING.md
Ever since commit 96de8dd7e7b0b3ee5275518aff13d1c46ab1dbd3, the way auth0 is setup for Docker has changed. I've edited CONTRIBUTING.md to accommodate this change. 
Feel free to suggest any changes, I'd be more than happy to comply.
> Updated Auth0 setup for Docker in CONTRIBUTING.md

- web/src/components/layout/nav.css
Fixes  #1631 
Follows the following properties :
If the mobile navigation was open at small screen size, it should:
-  close when the user resizes the screen to be a full desktop size
-  re-open if the user resizes the screen to be a small size again
> Fixing Menu

- web/src/components/pages/datasets/dataset-info.tsx
This hopefully addresses #2614. It's a weird one - I can definitely reproduce the bug on prod, but not on any of our non-prod servers or in my local. Chrome Autocomplete doesn't even show the country associated with an email address anywhere except for that one form field on prod specifically. 
This doesn't happen on the other email forms on the site (the Contact form and the Request A New Language form). 
My best _guess_ is that the locale stored in `this.state` (which should be the locale that the user is trying to download) is somehow colliding with the locale in `this.props` and updating the latter when it shouldn't be. However, since I can't replicate the bug locally, I don't actually know if this fixes it! I've renamed the property in `this.state` which seems like a harmless and …
> clearer dataset state names

- .travis.yml
Based on the "Transition branching and deployment" document, we want to deploy on merge to "stage" branch and not "staging". This change will accomplish that.
> Deploy on merge to stage branch

- server/src/auth-router.ts
- server/src/config-helper.ts
- server/src/lib/model/achievements.ts
- server/src/lib/model/user-client.ts
- server/src/main.ts
- web/src/components/app.tsx
- web/src/components/layout/layout.tsx
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/speak/audio-web.ts
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/challenge/constants.ts
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
- web/src/components/pages/datasets/subscribe.tsx
- web/src/components/pages/landing/landing.tsx
- web/src/components/pages/profile/info/info.tsx
- web/src/services/api.ts
- web/src/services/localization.ts
- web/src/stores/clips.ts
- web/src/utility.ts
This is a pretty big change, so if it looks good we should land it sooner than later to avoid conflicts building up.
If we need to re-run it, here are the steps to reproduce:
```
npm i -g optional-chaining-codemod # https://github.com/villesau/optional-chaining-codemod
for d in $(find . -type d); do
optional-chaining-codemod $d/*.ts --parser=ts;
optional-chaining-codemod $d/*.tsx --parser=tsx;
done
yarn prettier
```
I did a bit of manual cleanup afterwards, but nothing to difficult.
> Run optional chaining codemod and Prettier

- package.json
- yarn.lock
There's a security vulnerability in `minimist`, which in our repo is mainly used by `db-migrate` and its dependencies: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
I've pinned a resolution for v1.2.3, which gave me some errors as some of db-migrate's dependencies are relying on minimist versions 0.0.1 (!!) and 0.0.8. I dropped my local db and re-ran all migrations and didn't have an error, so I think this is fine, but let me know if you found something in testing.
> Add resolutions pin for minimist

- web/src/components/ui/ui.css
The `LinkButton` used for `Login/Signup` and `Logout` button in options dropdown that appear for smaller viewport  used the CSS rule "height: auto", for --md-up whereas most of the UI transition, if not all happen at --lg-up for the Tablet viewport. Due to this fact, this change will not cause any regression for existing LinkButton in other places (dataset page, landing page, contribution, dashboard, notification-banner) - Most have them have custom CSS properties that override the `height: auto` and `width:auto` property
There aren't any issues open dealing with this inconsistency.  The button's padding suddenly appears for width below `--md-up` and this leads to UI inconsistency.
* **Before**
Going below the size defined by `--md-up`, the button expands as can be seen below:
* **After** …
> UI[web]:Solve padding issue with the login/signup button in dropdown

- .prettierignore
If you try to merge `master` into a local branch, prettier will try to process all the sentence text files it adds and format them. Mostly this is just annoying, sometimes this actually breaks prettier and results in a GC out of memory error, and either way you'll probably end up with annoying merge conflicts.
> Add prettier ignore file for sentence data

- web/src/components/pages/contribution/success.tsx
- web/src/components/pages/dashboard/stats/progress-card.tsx
- web/src/components/pages/home/hero.tsx
- web/src/components/pages/languages/localization-box.tsx
- web/src/constants.ts
Implements [OI-1458](https://jira.mozilla.com/browse/OI-1458)
re: https://discourse.mozilla.org/t/english-has-reached-its-goal-of-1200-hours-of-validated-hours-what-will-be-the-next-goal/53826,
this commit adds a _list_ of hour goals, so that popular languages (eg. English) can reach for higher targets.
I made the decision to keep all goals on the site the same except for
the language cards on /languages. I _think_ this makes sense, but I'm
happy to discuss! Let me know if you think we should do something
different.
> Create 2500 validated hours target on lanugages page

- server/src/lib/model/db/migrations/20200402174044-add-composite-index-to-sentences.ts
This adds a composite index to the `sentences` table which will dramatically increase the speed of serving up fresh sentences when users come to the site, which I've tested both with dummy data locally and on stage. This primarily targets the `findSentencesWithFewClips` function in `db.ts`, which does the horrifying thing of sorting the entire sentence set of a language by `clips_count`. If this deploys smoothly I imagine we'll want to revisit the indexes on the votes and clips table as well to see what gains we can get there.
I'm mostly following off logic from [this article](https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys), happy to chat through offline.
> Add indexing to sentences table

- .travis.yml
We do not want to deploy when there is a new commit coming from Pontoon. This will keep our deployment history cleaner
> Do not deploy on localization commit.

- .travis.yml
@rileyjshaw found yesterday that after pushing a tag `stage-v1.25.2-ios-recording-web ` the deployment to stage wasn't done.
I've been looking into it and I'm mostly sure it was due to a missing space between the logical negation operator and the variable name.
Merging this to try to validate the assumption before your workday starts.
> Fix deployment condition

- CONTRIBUTING.md
Auto-rebuilding from `/web` has been broken on my machine for the past
week. I had time to look into it this afternoon. Turns out Docker was
running out of memory and crashing with a cryptic error.
I was already allocating 2GB to Docker, so hopefully we can continue to
reduce the memory footprint of `voice-web`. Until then, I thought this
would be a useful note for folks running the app for the first time.
> Add a note about Docker's memory settings

- server/src/lib/model/db.ts
This update affects two functions related to serving the activity cards on the dashboard and homepage. 
`getVoicesStats`: Instead of joining to the entire user_client_activities table and then filtering by hours, this now just grabs the last 10 hours of records from that table before doing the hourly grouping.
`getContributionStats`: this reverses a [change from back in December](https://github.com/mozilla/voice-web/commit/7505bcb27f) when we were first trying to speed up these queries. Gozer figured out a method that was way faster, but we didn't realize this entire time that if there was an hour in which no activity happened at all, that hour just wouldn't exist in the result set. This leads to interesting graphs like this one from stage: 
So I went back to the old slow query from …
> Improve activity queries

- common/clips.ts
- server/src/lib/model.ts
- server/src/lib/model/db.ts
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/sentence-recording.ts
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
- web/src/stores/clips.ts
- web/src/stores/sentences.ts
The `Sentence` interface was being separately defined in both `web` and `server`, this just pulls that as well as `Clip` into the 'common' module for easier sharing.
> Move Sentence and Clip types into common folder

- web/src/components/pages/contribution/report/report.tsx
Its accepting space to bypass the check, if someone put space in it the button gets enabled and the user can submit the report
> Fix empty value check

- web/src/components/pages/contribution/speak/audio-web.ts
- web/src/components/pages/contribution/speak/speak.tsx
Due to some overaggressive revoking of URLs, we were seeing bugs in
replaying and re-recording audio on the /speak page (eg. #2716, and
perhaps related to #2553). `this.last` was a huge vector for bugs, and
only used for `URL.revokeObjectURL` calls, so this commit moves URL
cleanup to `speak.tsx` and defers it until a Skip or Upload action
occurs.
This commit contains various other cleanups and small fixes, such as
making sure the most recent version of state.clips is referenced in our
setState calls. We paired on this together, so I won't go into any
further detail :)
> Remove the "last" reference from audio-web.ts

- server/src/lib/api.ts
- server/src/lib/clip.ts
- web/src/components/pages/contribution/speak/audio-web.ts
- web/src/components/pages/contribution/speak/speak.tsx
We've had some reports of loud clips being flagged as silent (eg.
https://discourse.mozilla.org/t/cant-submit-recordings-because-im-told-they-are-too-quiet-even-though-theyre-not/59373).
This commit ensures that a low volume error is thrown only if our
volume-checking utility is working and has been called. For various
reasons, some platforms may never receive an `onaudioprocess` event. In
such cases, we shouldn't assume that the recording is silent. I’ve added
notes to the server to check for silent clips.
This commit also removes any mention of "visualizer" from `audio-web.ts`,
since our visualizer is not audio-reactive.
> Change minimum volume handling code for /speak

- server/src/server.ts
Back in the days when Kibana was our main logging viewer we needed JSON logs. Now that we're on Papertrail, JSON logs are very messy and hard to read. Dev/Sandbox have been using the default console.log with no issues, so let's try also doing this on stage. cc @The-smooth-operator 
I'm leaving `lib/logger.ts` for now in case we end up needing it for something else.
> Remove JSON log outputs

- server/src/config-helper.ts
- server/src/lib/aws.ts
This should turn on the logging that AWS has by default so we can hopefully see more detail when weird file access bugs happen:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html
cc. @The-smooth-operator
> Turn on logging for AWS

- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20200529173455-add-valid-clip-column.ts
After some pretty extensive testing, I couldn't figure out a query that excludes all sentences that already have a valid clip without dramatically increasingly the query time (depending on user activity levels and implementation style, anywhere from 2-4 seconds per query, up from an average of 0.01s). This may not be a huge issue _now_ since we preload sentences as soon as users come to the site and there should always be sentences available for recording, but it's not something that'll scale well at all, especially since I'm only one person testing and I have no idea what will happen when 700 users all try to load a query that takes 2-4 seconds to run at the same time. 
So instead, this implementation lays the ground-work for future-forward single sentence record limits, with some …
> Architecture for single sentence record limit

- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- server/src/lib/model/db.ts
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
We've been seeing reports of clips of one language showing up on the
/listen page of another language. Our client does its best to be
responsive and quick when a user changes their language… as it should.
But when someone changes their language mid-way through recording a
batch of clips, it shouldn't affect the language those clips are saved
under.
This is a small and simple commit to move locale-handling to the server.
It adds a db call with `db.findSentence`, but removes three calls by
avoiding `db.getLocaleId`… so I think this might be a performance win in
the end.
> Don't rely on client's locale when saving clips

- web/src/components/pages/contribution/listen/listen.css
bug fix for issue #2780 where vote button icons become invisible in the disabled state during hovering.
> added fill rule for disabled hover state

- server/src/lib/model/leaderboard.ts
@mbransn According to the strictest definition of the rule of 5, we should be hiding leaderboard entries for all languages that have fewer than 5 unique speakers, which as of right now is just Votic. But since leaderboards are influenced by user settings, I've set it up so that leaderboard entries are hidden for all languages that have fewer than 5 visible speakers, which feels more in line with the spirit of the rule. Let me know if you have any concerns about this!
> Scrub leaderboard data if there are fewer than 5 users on list

- web/src/components/pages/languages/languages.tsx
Once upon a time in the halcyon days of 2018, we decided that languages on the `/languages` page should be sorted by the currently selected locales and then by active hours, except for English, which would always be last (unless you were currently localized as English). No one currently knows why this is, and it is a confusing user experience (see #2834) so we're changing this to prioritize the currently selected language and otherwise sort by active hours as normal.
> Sort languages by active hours other than currently selected language

- web/locales/en/messages.ftl
@phirework The previous merge from master erased all message strings for the demo mode. This PR fixes that.
> message strings from an earlier commit

- .travis.yml
- CONTRIBUTING.md
- README.md
- contribute.json
- web/src/components/invite-modal/invite-modal.tsx
- web/src/urls.ts
This is mostly documentation updates. Travis is now looking at a new branch, but it's still pushing to `itsre/voice-web` because that's a setting in Docker Hub that I don't think we're planning on changing right now, right? Unless you want to move everything into the new Docker Hub org now as well...
> Change repo name and default branch name

- server/src/lib/api.ts
- server/src/lib/clip.ts
We have a lot of dead code in our codebase built around the
eventual desire to ship the voice avatar.
I am investigating bugs around clip recording and uploading, so I want
to ensure these paths are never hit in our codebase. By adding some
simple logs, I can check back in Papertrail after a week or so to ensure
these conditions weren't triggered. If they weren't, good. If they were,
hello bug!
> Add logging for voice avatar and base64 upload handlers

- web/src/components/app.tsx
- web/src/components/index.css
- web/src/components/layout/layout.tsx
- web/src/components/pages/faq/faq.css
Prompted by a surprising layout breakage on our new error pages, I found some oddities in our page layout. This is my attempt to simplify a few years of uh, iterative development.
I did a bunch of detective work and testing while going through this, which I've tried to document below. But please let me know if you have any questions or concerns!
I've got a big change to follow this one to get rid of the `#scroller` and `#scrollee` containers, but that deserves its own commit and explanation. This is some comparatively simple prep work.
Here are the changes, explained:
---
- Remove an unused `.focus` style.
Added in 2017 (pre 60ae00771519), this class was used to add custom Firefox Focus scroll behaviour. The class was removed in 16d38229594d, but I accidentally left a custom rule in place …
> Clear some cobwebs from our page layout

- web/src/components/app.tsx
- web/src/components/index.css
- web/src/components/layout/footer.tsx
- web/src/components/layout/layout.tsx
- web/src/components/layout/nav.css
- web/src/components/pages/error-page/error-page.css
Remove the "scroller" and "scrollee" scroll containers
A more ambitious follow-up to my [my previous layout PR](https://github.com/mozilla/common-voice/pull/2863).
> Prompted by a surprising layout breakage on our new error pages, I found some oddities in our page layout. This is my attempt to simplify a few years of uh, iterative development.
Prior to this change, each of our pages lived within a nested `div#scroller` and `div#scrollee` container. On desktop these were inconspicuous wrapper `div`s. But on mobile, `#scroller` took on a `position: fixed` over the viewport, and `#scrollee` scrolled within it. With banners, dynamically-sized elements, and new flexbox layouts, keeping everything in a fixed panel has started to cause surprising bugs:
The solution is one part new, one part old. …
> Remove the "scroller" and "scrollee" scroll containers

- server/src/lib/model/user-client.ts
- web/locales/en/messages.ftl
- web/src/components/pages/profile/info/info.tsx
- web/src/constants.ts
I'm pushing this as a follow-up to our pairing session today. cc @phirework
- Remove unused `save()` function from `user-client.ts`
- Add `AND user_clients.has_login` to UserClient queries
- Send `accountClientId` rather than `client_id` to `updateDemographics()`
- Update and re-label translations: s/sex/gender
- A few whitespace bugs hitched a ride on this commit
> Final pre-launch updates for per-clip demographics

- web/src/components/pages/profile/layout.css
> Another way to fix  Issue #2253

- server/src/lib/bucket.ts
This was the case before, but the math was not intuitive and the commit message was stating the duration was 1 day
> Set session token expiration to 12 hours;

- server/src/lib/clip.ts
- web/package.json
- yarn.lock
Hopefully over time we send less and less blank clips from the client.
But until every client and device is perfectly reliable, we should also
double-check that clips are valid on the server. For now, we're using
file size as a proxy for that.
After this commit, this is the flow of an audio clip from the client, to
the server, to AWS, to the DB:
- Clip is recorded on the client
- Clip is submitted to the server
- HTTP stream of the clip is streamed to ffmpeg, which is then piped to
an AWS streaming upload
- Once the upload and transcoding are complete, if the audio clip is
invalid or resulted in an mp3 size < 300 bytes, we bail and delete the
file from AWS
- Otherwise, we consider it valid and save it to the DB
Specific changes in this commit:
- Update audio-recording-polyfill to …
> Prevent blank clips sent to the server from propagating

- server/src/lib/bucket.ts
Fixes:
```
[1] FAIL src/test/upload-recording.test.ts
[1]   ● Test suite failed to run
[1]     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
[1]     src/lib/bucket.ts:69:42 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
[1]     69           await this.model.db.deleteClip(id);
[1]     src/lib/bucket.ts:72:35 - error TS2339: Property 'CLIP_BUCKET_NAME' does not exist on type 'CommonVoiceConfig'.
[1]     72               Bucket: getConfig().CLIP_BUCKET_NAME,
```
> Fix clip id type

- web/src/stores/demographics.ts
Galician accents, as announced in https://discourse.mozilla.org/t/common-voice-languages-and-accent-strategy-v5/56555
> Add Galician accents

- .env-local-docker
- web/src/components/pages/dashboard/challenge/challenge.css
- web/src/components/pages/dashboard/challenge/weekly-challenge.css
- web/src/components/pages/dashboard/stats/stats-card.css
- web/src/components/plot/plot.css
- web/src/components/plot/plot.tsx
As mentioned in issue #2880 , the components of "Contribution Activity" and "Top Contributors" were misaligned. I've fixed those cards. If there is any feedback or still any error, please feel free to provide it.
> Contribution page fix

- web/src/components/pages/contribution/speak/audio-web.ts
> Decrease blob size of MediaRecorder api to prevent truncation in FF87

- web/src/components/pages/dashboard/stats/stats-card.tsx
- web/src/components/pages/dashboard/stats/stats.tsx
- web/src/components/pages/home/stats.tsx
- web/src/components/plot/plot.css
* Fixes bug introduced by #3006 that plots on homepage are overflowing into 200% width
* Introduces optional `scrollable` parameter for stats cards to selectively allow for overflow scroll to preserve readable labels in mobile for graphs
> Add optional scrollable parameter to stats cards for overflow

- server/src/lib/model/user-client.ts
This is caused by not awaiting the updateDemographics() promise. It
it therefore scheduled for running, but may be executed *after* the
UserClient.findAccount() call is awaited. Therefore, there is race
between updating the demographics and querying for it later, resulting
in a non-deterministic retrieval and the gender/age data sometimes
disapearing from the form. This is confusing for the user who thinks
the data was not saved.
I've seen it happening on the prod website.
> Fix a race condition when updating demographics data

- web/src/components/pages/contribution/speak/speak.tsx
We originally increased the min recording length to 1.5s in an attempt to deal with blank clips, but that wasn't actually the source of the problem, so I'm dropping it down to 1s to better support languages with shorter sentence segments.
> Reduce min recording length back down to 1s

- web/src/stores/demographics.ts
It just add 2 variants for Catalan non-native speakers. One value for Spanish native speakers, and other one for native speakers of other languages.
> Add 2 variants to Catalan language for learners (non-native) speakers

- docs/COMMUNITIES.md
Just a minor tweak in the documentation – adding links to the website and Telegram chat of the Belarusian community.
> Add Belarusian to COMMUNITIES.md

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/tracker.ts
Allow the user to signal that he messed up and want to begin again.
Could also consider starting recording again immediately? (this would be my personal preference, but without extra work it isn't really visible to the user that something happened. If there was a duration counter visible it would be less of an issue.)
Related to: #1052, #2105
> speak: add "discard ongoing recording" shortcut

- server/data/da/europarl-v7-da.txt
As requested by @phirework in #2730, I recreated the original PR after manual QA.
@Isomorph70 wasn't sure if you would prefer to create a PR yourself, hopefully this is okay with you :)
Reviewed 2399 of the original 5136 sentences with 3% error rate, at 99% confidence.
After deleting problematic sentences, the new total is 5066.
Manual QA results here https://github.com/Pertel/danish-cv-validation/blob/main/Common%20Voice%20-%20Sentence%20QA%20-%20Danish.ods 
I deleted the sentences with issues found in review, but am unsure if this was too early in the process.
Let me know and I'll revert the deleted lines.
@nukeador
> Add danish europarl sentences

- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
Sometimes (maybe when the server is under load and not responsive)
the client sends multiple copies of a file to the server, and diff
pods all try to encode the file at the same time, which both
is an inefficient use of resources. The errors from these also makes
it difficult to diagnose real FFmpeg issues from weird collision ones.
This PR checks if a file exists on S3 before beginning the encoding
process, and if yes, skips it. It incidentally also:
* Fixes issues where throw errors inside a request don't terminate
the rest of the function
* Ensures tasks for after S3 upload actually happens after the entire
stream is encoded
*  Send encoding errors to Sentry instead of just logging
> Dupe encoding

- common/takeout.ts
- server/src/lib/api.ts
- server/src/lib/bucket.ts
- server/src/lib/takeout.ts
- web/locales/en/messages.ftl
- web/src/components/pages/profile/download/download.tsx
- web/src/services/api.ts
* Ensure clips are wrapped in subdirectory so that unzipping doesn't
pollute the current directory
* Ensure cleanup tasks removes files
* Keep records of old expired takeouts in case cleanups fail and
we need to discover where those files are
* Add frequency limit to # of takeouts users can request
* Increase # of clips per takeout chunk to 2k
* Add language code to metadata file
> Fixes and QoL improvements for personal data takeout function

- web/locales/en/messages.ftl
This adds a section for the Sentence Collector source strings. Sentence Collector will export automatically to this section on every automatic export. Commits are only done when there indeed are changed/deleted/new strings.
PR for Sentence Collector: https://github.com/common-voice/sentence-collector/pull/536
> Add Sentence Collector EN strings export section

- web/src/components/pages/document-page.tsx
Resolves #3287 
There are two commits in this PR:
* The latest is a state-only change that switches to `ComponentDidUpdate` so that Redux changes trigger a redraw of the inner HTML.
* The prior commit accomplishes the same thing but refactors the component to a functional one.
I wasn't sure which would be preferred, so I included both--deferring to minimizing unnecessary change. If the functional version is preferred I can re-push with just that. If the class-based version is preferred and the extra commit needs to be pruned, I'm happy to do that as well.
For my part, I like the simplicity of functional components and their integration with the Hooks API. Unfortunately the spacing (between parens and braces) isn't right on that commit. I'll fix it if we choose that one.
> Update Terms and Privacy content on Locale change

- scripts/import-locales.js
Since we added Sentence Collector sentences to the same localization file, we're lowering the threshold for how complete the localization needs to be for it to show up in `translated.json` to avoid putting undue burden on new/smaller communities joining in the future.
> Lower localization threshold to account for SC

- docs/COMMUNITIES.md
Czech (cs) community does not use Telegram anymore.
> Replace obsolete Telegram group by Matrix

- web/locales/cy/messages.ftl
- web/locales/de/messages.ftl
- web/locales/en/messages.ftl
- web/locales/hsb/messages.ftl
- web/locales/sv-SE/messages.ftl
In the latest batch of exported string there is one string `about-playbook-what-is-language-content-3` has a incomplete closing HTML tag `</ctaLink` instead of `</ctaLink>`. This commit fixes en locale, as well as those locales already translated but did not have the tag corrected in translation. 
* me myself.
> fix incomplete closing tag ctaLink in about-playbook-what-is-language-content-3

- server/src/lib/api.ts
- server/src/lib/clip.ts
This bug was returning null because of incorrect check of valid numbers.
> fix(param): query param incorrectly parsed

- web/src/components/visually-hidden/visually-hidden.css
- web/src/components/visually-hidden/visually-hidden.tsx
Add `VisuallyHidden` component. This hides content visually but allows assitive technology to access it still.
```js
<VisuallyHidden>This is hidden weee!</VisuallyHidden>
```
Sometimes we want something to not show visually but availablefor assistive technologies such as screenreaders.
These styles are from GOV.UK's work, known for their accessibility work.
> feat(accessibility): add component to hide things visually

- server/package.json
- web/jest.config.js
- web/package.json
- web/src/services/localization.ts
- web/src/test/jest.setup.js
- web/src/test/mock-localization.tsx
- web/src/utility.test.ts
- web/tsconfig.test.json
- yarn.lock
Added base files to add tests to the `web/` part of the codebase.
Adds a `renderWithLocalization` helper function that allows us to mock localization with a drop in replacement for React Testing Library's `render` function.
Usage:
```js
import { renderWithLocalization } from '../../test/mock-localization';
// ...
it('should render the component', () => {
await renderWithLocalization(<p>Hello World</p>
});
```
> feat(testing): add basic testing setup for web

- web/index_template.html
References #2861
We can't localise the share metadata easily because we currently don't serverside render our HTML, the website is all JavaScript.
+ Removes English descriptions
+ Renames 'Common Voice by Mozilla' to 'Mozilla Common Voice'
> feat(localization): remove english from share metadata

- web/src/components/pages/dashboard/stats/stats-card.tsx
I noticed when moving between the languages on the stats page we would incorrectly store the stats filters.
This PR fixes this issue.
> fix(stats): moving between languages stored filters

- web/src/components/index.css
- web/src/components/pages/contribution/speak/recording-pill.tsx
- web/src/components/pages/profile/info/info.css
- web/src/components/pages/profile/info/info.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-input.test.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-input.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-list.test.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-list.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents.css
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents.tsx
- web/src/components/pages/profile/info/languages/input-language-name.test.tsx
- web/src/components/pages/profile/info/languages/input-language-name.tsx
- web/src/components/pages/profile/info/languages/languages.css
- web/src/components/pages/profile/info/languages/languages.test.tsx
- web/src/components/pages/profile/info/languages/languages.tsx
- web/src/components/ui/icons.tsx
- `setUserAccentLocales` to `setUserLanguages`
Soon this will be including variants and 'Language' seems to be better than `UserAccentVariantLocale`?
- Various linting
- Move language UI components into separated files
- Added tests for core functionality
> chore(profile): test and refactor language form elements

- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-input.test.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-input.tsx
This PR stops users from entering empty accents on the profile page when adding languages.
Thanks @mozgzh
> fix(profile): don't allow empty accents values

- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-list.tsx
- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents.css
+ Fixes some spacing issues for the profile pages accent list on RTL languages
+ Move the 'Close' X to the right on LTR and to the right on RTL
**Before**
**After**
> fix(profile): accents UI on RTL languages have incorrect spacing

- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/tables/clip-table.ts
This PR is to enable caching for a heavy query that's involved with finding clips to show to a user. By breaking up the query into multiple parts, utilizing caching where it makes sense and ensuring BI is in code (instead of SQL), the DB server can rest easier, ideally, dramatically reducing reads and total rows processed.
> Improve getRandomClips performance

- web/src/components/pages/contribution/contribution.tsx
Tell Google Chrome to never translate sentences that people should read.
Thanks to the great issue from @jmontane. This doesn't fully resolve the issue but does help.
Partially fixes #3491
> fix(translation): never let google chrome auto translate sentences

- server/src/lib/model/awards.ts
- server/src/lib/model/leaderboard.ts
- server/src/lib/model/user-client.ts
- tsconfig.base.json
- web/package.json
- web/src/components/pages/about/nav.tsx
- web/src/components/pages/faq/faq.tsx
- web/src/components/pages/faq/selectors.tsx
- web/src/components/pages/profile/download/download.tsx
- web/src/components/pages/profile/info/info.tsx
- web/src/components/welcome-modal/welcome-modal.tsx
- web/src/hooks/use-active-section.ts
- web/webpack.config.js
- yarn.lock
Was doing some brief Webpack digging. This does seem to be [the best way to import lodash](https://itnext.io/lodash-es-vs-individual-lodash-utilities-size-comparison-676f14b07568).
- Add `yarn build:audit` to launch the Webpack Bundle Analyzer
- Fix lodash dependancies importing lots more lodash than we needed
| Before | After | Percentage change |
|-|-|-|
| 283.34 KB | 259.97 KB | -8.24804% ✅ |
> fix(lodash): importing lodash incorrectly

- .prettierrc
https://prettier.io/blog/2021/09/09/2.4.0.html#replace-jsxbracketsameline-option-with-bracketsameline-option-11006httpsgithubcomprettierprettierpull11006-by-kurtztechhttpsgithubcomkurtztech
> fix(prettier): deprecated option

- web/locales/ca/messages.ftl
- web/locales/en/messages.ftl
- web/src/components/pages/contribution/contribution.css
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/listen/listen-error-content.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/speak-error-content.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
- web/src/stores/clips.ts
- web/src/stores/locale.ts
- web/src/stores/sentences.ts
+ Do not load sentences and clips needed for /speak or /listen pages on any page load. Now loads when needed
+ Add a spinner loading on /speak, /listen page when loading
+ Adds error messaging for when getting random sentences/clips error
+ Tidy up styling/markup for error messages
+ Detect erroring clips and remove them from clips list
+ Do not request clips again if we have a XMLHttpRequest error
> fix(speak/listen): better loading of data and better error handling

- web/index_template.html
Fixes #773
Do not stop a user from scaling.
For the future if anyone sees this PR and is thinking to disable scaling again this is a core accessibility issue and should never be disabled.
https://web.dev/meta-viewport/
> fix(accessibility): do not disable viewport scaling

- server/src/lib/api.ts
/metrics route is used in various systems-checking. Remove said endpoint breaks systems health checks and to fix would require additional systems changes. Since the focus of the image queue PR is not related to that, I've created a hollow endpoint to that allows the healthchecks to work as normal.
> Add metrics endpoint

- scripts/import-locales.js
- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20220322130651-locale-target-sentence-criteria.ts
- server/src/lib/model/db/migrations/20220323130651-locale-target-sentence-criteria.ts
This branch brings changes to how sentence criteria are defined for the platform.
Instead of having the static 5000 sentence criteria hardcoded, it will be added to the database and utilized from queries.
Work includes:
- Create new column in locales and add sentence criteria target.
- Modifying import-locales.js to make use of db
- Modifying /language_stats endpoint to return `sentence_target_count` per locale
`/language_stats` now looks like the following: 
```{
"inProgress": [
{
"locale": "ace",
"localizedPercentage": 16,
"sentencesCount": {
"current_count": 87,
"target_sentence_count": 750
}
}...
```
> Add target sentences column and data

- .github/workflows/build.yaml
Currently, if I'm promoting a branch like `main` to `stage` and am not fast enough (e.g. a pontoon commit is merged first), I cannot build the image. This change should make so any versioned tag can be built even if the last commit is from Pontoon
> Rewrite condition when building image

- server/src/lib/model/db/import-sentences.ts
Reduce import size when batching import sentences to stop OOM issues when deploying application.
> Reduce import size when batching import sentences

- web/src/components/pages/about/playbook.css
* Fixes #3635 
* The content should now fit and display correctly without clipping. However, the height does dynamically change if the content within the button is long so I am not sure of the design direction of the buttons require a strict height.
* @robovoice1 for logging the bug
* @mozgzh for a good solution suggestion
> update buttons in cv-tab-content to be able to fit its content

- web/src/components/ui/ui.tsx
Errors are no longer ignored when Localization component called outside `LanguagesProvider` component. As a result, since the `Spinner` is called early in the app (on app load) and before `LanguagesProvider` it throws an error.
Quick fix is to remove localization on `Spinner` and just hard-code "Loading" for screen readers.
> Remove localization in spinner after package upgrade throws error

- web/src/components/pages/about/playbook.css
Elements of class `tab-subtitle` had `margin-bottom: -1rem;`, causing overlap with the text below. We increase margin-bottom to prevent overlap.
The affected part of the site is located at https://commonvoice.mozilla.org/en/about?tab=how-grow-language#playbook.
* https://github.com/common-voice/common-voice/issues/3801
> Fix overlapping subtitle and paragraph text

- docs/LANGUAGE.md
The completion rate reaches 75% not 90%.
The completion rate reaches 75% from https://commonvoice.mozilla.org/en/about?tab=how-localize#playbook and Common Voice's pontoon.
* The completion rate reaches 75% not 90% for localization.
> Update Localization in LANGUAGE.md

- common/statistics.ts
- docs/API/statistics.md
- server/src/lib/model/statistics.ts
- server/src/lib/statistics.ts
- server/src/lib/validation/statistics.ts
All the stats endpoints can be queried by year now. The current year is used, if the `?year={year}` query parameter is omitted. The `year` query parameter can also be combined with existing query parameters, e.g:
GET `/api/v1/statistics/clips?filter=rejected&year=2021` HTTP/1.1
QA:
- Check the different stats endpoints, e.g. the one mentioned above, and compare whether the `yearly_sum` adds up to the `total_count`[^1]
- Use combined query parameters as well
[^1]: The `speakers` endpoint is the exception, refer to the [documentation](https://github.com/common-voice/common-voice/blob/main/docs/API/statistics.md) for more information
> Expand the stats API so users can query by year 

- web/src/components/pages/datasets/dataset-corpus-download.tsx
- web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx
- web/src/components/pages/datasets/dataset-download-email-prompt.tsx
- web/src/components/pages/datasets/dataset-info.tsx
- web/src/components/pages/datasets/dataset-segment-download.tsx
The "Join mailing list" checkbox was hidden for users who had signed up for the mailing list but I discovered that the checkbox is still visible for users that download the dataset with an email different from the one they use in their profile. 
On the BE we don't really have a way of knowing if the user is subscribed if they use a different email to sign up. So I think we can just stick with the acceptance criteria and default to always showing the checkbox because we don't have a reliable way to know if a user has signed up to the mailing list or not.
> staging-hotfix: Make join mailing list checkbox in the datasets page always visible

- common/statistics.ts
- docs/API/statistics.md
- server/src/lib/model/statistics.test.ts
- server/src/lib/model/statistics.ts
- server/src/lib/statistics.ts
- server/src/lib/validation/statistics.ts
There is a new stats API endpoint: `/api/v1/statistics/metadata`, that shows clips with metadata in comparison with all clips. This endpoint takes an optional `?year` query parameter as well, which can be used to filter by a given year.
> OI-2575: Add clips with metadata to stats api

- web/src/components/pages/contribution/contribution.tsx
- web/webpack.config.js
The speak contribution flow changed and impacted the listen contribution flow. Since the speak contribution flow does not follow the normal order, the success page got deleted. The success page is still needed for the listen flow and got re-added in this PR. This closes #3890 by fixing the bug.
> OI-2557: Fix 'no more clips' issue

- web/src/components/index.css
- web/src/components/media.css
- web/src/components/pages/contribution/contribution.css
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/pill.css
- web/src/components/pages/contribution/sentence-collector/review/review.css
- web/src/components/pages/contribution/sentence-collector/sentence-collector-wrapper.css
- web/src/components/pages/contribution/sentence-collector/write/write.css
- web/src/components/pages/contribution/speak/firstSubmissionCTA/firstPostSubmissionCTA.css
- web/src/components/pages/contribution/speak/secondSubmissionCTA/secondSubmissionCTA.tsx
* https://github.com/common-voice/common-voice/issues/3969
This PR fixes the issue where on zoomed screens some buttons do not fit the screen and as zoom is disabled on the contribution pages buttons are unavailable
Changes:
* enabled scroll on `/speak` and `/listen` if contents do not fit the screen (removed `overlay:hidden;`)
* set height of `/speak` and `/listen` to `100dvh - 2px` so it fits mobile screens snugly
* adjusted margins and paddings so the content fits better into the screen
* set min-height to 70%, so content is more compact and does not create a scroll
* ~adjusted `contribution.tsx` to not print primary buttons on `isDone` overlay screen, so the screen is smaller and visible parts fit the screen~
Tested on:
* Firefox, Chrome, Edge, Safari on mobiles, tablets and desktops …
> Adjusting speak and listen css so buttons fit screen

- server/src/lib/model/db/import-sentences.ts
* https://github.com/common-voice/common-voice/issues/4061
The `is_used` column of the `sentences` table can be used to hide sentences from the UI, but the current codebase would override any values of this column during the sentence import. This PR will fix that, the value of `is_used` will be preserved.
This will allow removing problematic sentences from the Common Voice UI without removing their recordings.
The use case of this is to remove offensive sentences from the system retaining their recordings.
> Will not override existing value of is_used

- server/src/lib/model/db/import-locales.ts
* Added three main variants of Tamazight (zgh):
- {shi} ⵜⴰⵛⵍⵃⵉⵜ -- Tachelhit
- {tzm} ⵜⴰⵎⴰⵣⵉⵖⵜ ⵏ ⵡⴰⵟⵍⴰⵚ ⴰⵏⴰⵎⵎⴰⵙ -- Central Atlas Tamazight
- {rif} ⵜⴰⵔⵉⴼⵉⵜ -- Tarifit
* Brahim Essaidi, Yassine Aït-El-Mouden from Pontoon Tamazight team
> Update import-locales.ts with Tamazight variants

- server/src/lib/model/db/migrations/20230815103600-hide-problematic-sentences.ts
* https://github.com/common-voice/common-voice/issues/4138
This PR will hide sentences that have `?` in the middle of some words in sentence text.
Check for locale on first query is omitted on purpose as this issue is affecting multiple locales and it is hard to imagine some language where `?` in the middle of the word is a valid grammatical structure. If necessary, I would be happy to adjust the PR.
Checking Latvian sentences noticed also that some sentences do not have any text, so this PR will also hide those.
To run a query manually one would use 
```
UPDATE sentences SET is_used = FALSE
WHERE (created_at > '2023-05-01 00:00:00' AND text REGEXP '.*\\?[a-zāčēģīķļņšūžâîûüöç].*') OR text = ''
```
and
```
UPDATE sentences SET is_used = FALSE
WHERE locale_id=(SELECT id from locales WHERE …
```
> Will hide problematic sentences

- web/src/components/pages/contribution/speak/speak-error-content.tsx
Pull request will fix link that is visible on the sentence recording screen when there are no sentences to record
> Fix for link to add more sentences

- web/src/components/pages/contribution/sentence-collector/review/review.css
- web/src/components/pages/contribution/sentence-collector/review/review.tsx
fixes #4142 
Fix: Skip button text-overflow
Previously, translated texts that were too long would spill over from the skip button.
**Before** 
**1. The skip icon is not displayed on the large screen for oversized translated text.** 
**2. When viewed on a small screen, the icon disappears and the text overflows. for large text**
****
**After fix** 
1. If the translated text is too long for a small screen, it will be shortened to an ellipsis. 
https://github.com/common-voice/common-voice/assets/85433137/ad341785-dcae-46b3-8fec-d3da306ecf06
2. if the text is not large then it would not be shortened to an ellipsis
> fix: skip button text overflow

- server/src/core/sentences/types/validators.ts
- server/src/core/sentences/validation/languages/he.ts
- server/src/core/sentences/validation/validation.ts
- server/src/test/core/pending-sentences/validation/validation.test.ts
Adds Hebrew sentence validation.
Hopefully another pull request will include removal of already-submitted sentences that aren't valid - though this should be done delicately (see comments regarding punctuation allow in the English validator that was made invalid in the Hebrew validator).
It adds one eslint warning regarding the use of `require` - I didn't want to touch it as all other validators use this syntax.
* https://github.com/common-voice/common-voice/issues/4121
Just me; coordinated with @moz-dfeller .
> feat: add Hebrew sentence validation

- server/src/lib/model/db.ts
Updated the query to use a sub query which runs about 20% faster than the previous query.
Relates to #4195
> Oi 2816 add timestamp to language stats

- server/src/lib/model/db/migrations/20240123163000-update-sentence-bands.ts
Languages updated to 750 sentences:
* 'crh', 'vmw', 'guc', 'fuf', 'wep', 'qvi', 'nhe', 'dag'
> Migration to update sentence bands for crh, vmw, guc, fuf, wep, qvi, nhe, dag

- server/src/api/sentences/handler/add-sentence-handler.ts
- server/src/api/sentences/validation/pending-sentences-requests.ts
- server/src/application/helper/error-helper.ts
- server/src/application/sentences/repository/locale-repository.ts
- server/src/application/sentences/repository/sentences-repository.ts
- server/src/application/sentences/repository/variant-repository.ts
- server/src/application/sentences/use-case/command-handler/add-sentence-command-handler.ts
- server/src/application/sentences/use-case/command-handler/command/add-sentence-command.ts
- server/src/application/types/error.ts
- server/src/application/types/sentence-submission.ts
- server/src/core/sentences/types/sentence.ts
- server/src/core/sentences/types/validators.ts
- server/src/core/sentences/validation/validation.ts
- server/src/core/types/variant.ts
- server/src/test/application/sentences/use-case/command-handler/add-sentence-command-handler.test.ts
* add the variant tag and remove locale id from the `add-sentence` endpoint request
* the `variant` property is optional on the request
* some small naming changes
* refactor add sentence command handler to be easier to test
* add a test for the add sentence command handler
> Oi 3005 update the add sentence endpoint to take in the variant

- server/src/api/sentences/handler/add-sentence-handler.ts
- server/src/api/sentences/validation/pending-sentences-requests.ts
- server/src/application/sentences/repository/locale-repository.ts
- server/src/application/sentences/repository/sentences-repository.ts
- server/src/application/sentences/repository/variant-repository.ts
- server/src/application/sentences/use-case/command-handler/add-sentence-command-handler.ts
- server/src/application/sentences/use-case/command-handler/command/add-sentence-command.ts
- server/src/core/types/locale.ts
- server/src/core/types/variant.ts
- server/src/test/application/sentences/use-case/command-handler/add-sentence-command-handler.test.ts
Make sure that the submitted sentence locale matches the locale that variant belongs to. Also remove the `localeId` from the add sentence endpoint to prevent an additional mismatch between provided `localeName` and `localeId`.
> OI-3057: check if variant is matching the locale

- common/clips.ts
- server/src/application/sentences/repository/variant-repository.ts
- server/src/infrastructure/db/mysql.ts
- server/src/lib/clip.ts
- server/src/lib/model/db.ts
Add variant info to the response object to display it on the speak and listen page.
* feat: add method to retrieve variants by sentence id
* feat: append variant metadata to sentence for listen page
* feat: add variants to sentences for the speak page
> OI-3078: Provide variant tag on the speak and listen page

- web/src/components/pages/contribution/sentence-collector/review/review.tsx
It crashed when the current language has no variant. Therefore we need to optionally chain the variant property.
> fix: check if variant exists on current language

- server/src/lib/model/db/migrations/20240312124200-update-sentence-bands.ts
Update the sentence bands to 750 sentences for `kln`, `dav`, `luo` and `azz`.
> Update sentence bands for luo/dav/kln/azz

- server/src/lib/model/db/import-locales.ts
The language selector only showed language codes instead of the name of the language. Now the language names will be displayed in currently selected language.
> fix: show localised language name

- web/src/components/pages/contribution/listen/listen.tsx
* https://github.com/common-voice/common-voice/issues/3747
* https://github.com/common-voice/common-voice/issues/4233
This PR will fix "There are no more clips to validate" error only after first 5 clips for logged in contributors. After each 5 clip batch the next will be loaded without need for users to reload the page.
> Fix for clip loading in Listen section

- server/src/api/sentences/handler/add-small-sentence-batch-handler.ts
- server/src/api/sentences/routes.ts
- server/src/api/sentences/validation/pending-sentences-requests.ts
- server/src/application/repository/sentences-repository.ts
- server/src/application/sentences/helper/domain-helper.ts
- server/src/application/sentences/use-case/command-handler/add-bulk-sentences-command-handler.ts
- server/src/application/sentences/use-case/command-handler/add-multiple-sentences-command-handler.test.ts
- server/src/application/sentences/use-case/command-handler/add-multiple-sentences-command-handler.ts
- server/src/application/sentences/use-case/command-handler/add-sentence-command-handler.ts
- server/src/application/sentences/use-case/command-handler/command/add-multiple-sentences-command.ts
- server/src/application/types/sentence-submission.ts
- server/src/core/sentences/cleaning/multiple-sentences.test.ts
- server/src/core/sentences/cleaning/multiple-sentences.ts
- server/src/test/application/sentences/use-case/command-handler/add-sentence-command-handler.test.ts
Add functionality to allow processing of small sentences batches (<1k sentences). Pass the complete sentences string as `sentences` in the request body. The backend will validate the incoming input and process all valid sentences and return a list of invalid sentences with their corresponding error, if there are any.
Example request:
```
POST /api/v1/sentences/batch
```
Post body:
```json
{
"sentences" : "This is the first sentence.\nHere is another sentence. \n\nI left   some    spaces.",
"source": "me",
"localeName": "cy",
"domains": ["general", "finance"],
"variant": "cy-midwales"
}
```
Example response:
```json
{
"message": "Valid sentences have been added succesfully",
"total_count": 10,
"valid_sentences_count": 9,
"invalid_sentences_count": 1,
"invalid_sentences": [
{
"sentence": …
```
> 602 build validation pipeline for multiple sentences

- web/src/components/pages/contribution/sentence-collector/write/sentence-write/index.tsx
- web/src/components/pages/contribution/sentence-collector/write/sentence-write/sentence-write.test.tsx
- web/src/components/pages/contribution/sentence-collector/write/write-container.tsx
This pull request includes several changes to the `SentenceWrite` component and its related files to improve the handling of sentence domains. The most important changes include renaming and updating props, adjusting imports, and modifying test cases accordingly.
* [`web/src/components/pages/contribution/sentence-collector/write/sentence-write/index.tsx`](diffhunk://#diff-7255be654677f1208e26ce980a74f57eafb25e425bc35fadf5dc2a6c4e51df79L33-R34): Renamed the `sentenceDomains` prop to `selectedSentenceDomains` and updated its usage throughout the component. [[1]](diffhunk://#diff-7255be654677f1208e26ce980a74f57eafb25e425bc35fadf5dc2a6c4e51df79L33-R34) [[2]](diffhunk://#diff-7255be654677f1208e26ce980a74f57eafb25e425bc35fadf5dc2a6c4e51df79L50-R51)
* …
> fix(write page): fix domain dropdown

- server/src/lib/model/db/import-locales.ts
This PR adds variants for Circassian languages (ady & kbd) for different/major countries & scripts.
Here is it in table form:
Reviewer @ftyers 
Edit-1: Added Kabardian reference to variant
Edit-2: Changed transliteration bcp-47 code from `<lc>-Latn-TR-t-<lc>-cyrl-tr` to  `<lc>-Latn-TR-t-<lc>-cyrl` as some of the sentences would be common to all variants and those will also be transliterated to Latin-Turkish.
> Add Circassian (ady & kbd) variants

- server/src/api/cli/start-dataset-release.ts
- server/src/infrastructure/queues/bulkSubmissionQueue.ts
- server/src/infrastructure/queues/queues.ts
- server/src/infrastructure/queues/updateValidatedSentencesQueue.ts
Fixing the the `updateValidatedSentences` job, that stopped working.
* adding the job name to the sand-boxed processor
* change the ordering of some function parameters
> fix: update validated sentences job was not triggered anymore

- server/src/lib/utils/secondsToHours.test.ts
- server/src/lib/utils/secondsToHours.ts
A quick fix to display hours with one decimal place if a language has fewer than 10 hours collected.
Example:
> feat: round hours that are less than 10h to one decimal

- web/src/components/pages/about/why-common-voice.css
* [#4677](https://github.com/common-voice/common-voice/issues/4677)
* Fixed the misaligned header text on the About page for small screens by correcting the UI padding issue. The issue was causing text to be cut off or misaligned on mobile screens and smaller devices.
* Self
* Feedback and suggestions from @jessicarose regarding the issue
> Fix: Proper padding for header text on About page for small screens

- server/src/lib/api.ts
- server/src/lib/model/db.ts
The `client_id` was destructered in the `getVariants` function call although it is not even used. The destructing also caused an error because the `client_id` is not always present but was assumed to be.
> fix: remove unused client_id

- web/src/components/pages/contribution/contribution.css
- web/src/components/pages/contribution/sentence-collector/review/review.css
This fixes #4758 for most usual 1080p screens by using smaller font and smaller left/right padding, letter-spacing, and line-height values.
Note that:
- The default 14 words/sentence (estimated from English) should be about 1.5x14 = 21 words for 15 sec recordings.
- Although the recording limit is increased the frontend is not adapted for longer texts.
- Frontend is most probably tested against English texts, where average word length is ~5 symbols. On the other hand we calculated ~7 symbols/word average for Kabardian (similar for Adyghe). Also many symbols are wide, like Ж Д Ш Ю
This is tested for Kabardian ON THE BROWSER for a 21 word sentence for 15 sec recordings. Here are the results:
For Speak:
For Listen with variant pill:
> Allow long text to fit sentence area

- server/src/lib/model/db/language-data/variants.ts
This PR adds generic Cyrillic variants for sentences common for all locales. Until now we used empty variant info for those, but whenever we added Latin transliterations, people only see them because they have 0 recordings, and Cyrillic ones have at least one recording. To be able to filter them in the profiles, we need to migrate the `sentence_metadata` to these new variants - next.
The ones in bold are added.
Next will follow migrations in both `ady` and `kbd` locales.
This is **urgent** because people cannot skip thousands of Latin sentences, so they stopped recording.
> [FIX] (URGENT) Add generic *-Cyrl variants for ady and kbd for common sentences

- server/src/lib/model/db/language-data/variants.ts
- server/src/lib/model/db/migrations/20250221120000-set-empty-ady-variants-to-cyrl.ts
- server/src/lib/model/db/migrations/20250221120100-set-empty-kbd-variants-to-cyrl.ts
This is a follow-up for #4791 for Circassian languages (`ady` and `kbd`).
If the variant field is empty, they get "moved" to `<lc>-Cyrl` to distinguish from others in profile.
Until now, except recently added `<lc>-Latn-TR-t-<lc>-Cyrl` sentences, there are other sentences without variant info, so it is safe.
EDIT: The first commit has already been merged, but here will silently be processed. I hope it is OK.
> Migrate Circassian common sentences to <lc>-Cyrl variants

- server/src/lib/model/db/language-data/accents.ts
- server/src/lib/model/db/language-data/variants.ts
This adds Laz language variants and accents.
PR is for İsmail Bucaklisi
For review by @ftyers 
Variants and accents are ordered from west to east.
> Add Laz language variants accents

- server/src/lib/model/db/language-data/variants.ts
Add variant to `sw` Kiswahili - Katanga (DRC) - sw-katanga 
Tested by running 
```
SELECT l.name, l.native_name, v.variant_name, v.variant_token 
FROM variants v, locales l
WHERE v.locale_id = l.id 
AND l.name = 'sw'
```
|name|native_name|variant_name                              |variant_token|
|----|-----------|------------------------------------------|-------------|
|sw  |Swahili    |Katanga (DRC)                             |sw-katanga   |
|sw  |Swahili    |Kibajuni (KE) - Northern dialect          |sw-kibajuni  |
|sw  |Swahili    |Kimakunduchi/Kikae (TZ) - Southern dialect|sw-kikae     |
|sw  |Swahili    |Kimrima (TZ) - Northern dialect           |sw-kimrima   |
|sw  |Swahili    |Kimvita (KE) - Central dialect            |sw-kimvita   |
|sw  |Swahili    |Kingwana (DRC) …
> Add sw-katanga variant

- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/tag.css
- Fixes sentence variant display in both SPEAK and LISTEN pages
- Instead of uppercase variant token it now displays a combination of `name (token)` as they come from database (no case manipulation).
- Fixes several reports:
- https://github.com/common-voice/common-voice/issues/4790
- https://github.com/common-voice/common-voice/issues/4840
- https://github.com/common-voice/common-voice/issues/4806 (second part)
Example:
> Fix variant names in speak listen

- web/src/components/layout/layout.tsx
- web/src/components/localization-select/localization-select-complex.test.tsx
- web/src/components/localization-select/localization-select-complex.tsx
- web/src/components/localization-select/localization-select.css
This implements the idea presented in https://github.com/common-voice/common-voice/issues/4734
For logged in users who have languages set in their profiles, the user language codes are passed to the language selector component, where the list is re-organized.
When not logged-in or no user languages selected, it behaves normally.
Screenshot:
> Feat - Move user languages to top of the list

- server/src/lib/model/db/language-data/variants.ts
* #4144 - support Cyrillic orthography in Uyghur
This PR is 1 of 2 required to facilitate support for Cyrillic orthography in Uyghur. Following merge of this PR, a second PR is required to ascribe all _existing_ sentences for `ug` to the `ug-Arab` variant. 
The following checks have been done: 
* Check there are no sentence validation rules for `ug` that affect the addition of Variants => no rules exist for `ug`
* Check _only_ the required files are committed to the PR => yes, only `variants.ts`
* Check addition of Variants is in alphabetical order in `variants.ts` => OK 
* Check that the Variants are correctly applied to the DB => OK 
|name|native_name|variant_name|variant_token|
|----|-----------|------------|-------------|
|ug|Uyghur|Уйғур тили|ug-Cyrl|
|ug|Uyghur|ئۇيغۇر تىلى|ug-Arab| …
> Add ug-Cyrl and ug-Arab variants to partially resolve #4144 - support Cyrillic orthography in Uyghur

- web/src/components/pages/datasets/dataset-info.tsx
Fixes https://github.com/common-voice/common-voice/issues/4819
- Not tested on live data (works on dev env - with empty "storage")
> Fix: Revert to `en` for download if UI language does not have a dataset

- web/locales/spontaneous-speech/en/pages/common.ftl
- web/locales/spontaneous-speech/en/pages/contribution/check-transcript.ftl
- web/locales/spontaneous-speech/en/pages/contribution/prompts.ftl
- web/locales/spontaneous-speech/en/pages/contribution/transcribe.ftl
- web/locales/spontaneous-speech/en/pages/contribution/validate.ftl
Fixes "Pontoon keys not changed" issue for changed "continue-with-skipped" workflow in Spontaneous Speech, which prevents translations.
> Update SS ftl with no-<resource>-continue-skipped-message

- server/src/lib/model/db/language-data/variants.ts
Add variants for Alsatian `gsw`.
```
gsw-FR-sudrfran:  Südrheinfränkisch (Weissebuisch, Màdere, usw.) "
gsw-FR-rhinfran: Rhinfränkisch (Bùckenùmm, Lìtzelstän, usw.)"
gsw-FR-nordalem: Nordniederàlemmànisch (Rishoffe, Zàwere, Bùsswìller, Hawenau, Brüemt, Stroossbùri, Molse, Dàmbàch, Schlettstàtt, usw.)"
gsw-FR-sudnalem: Südniederàlemmànisch (Kolmer, Gawìller, Mìlhüüsa, Àltkìrich, usw.)"
gsw-FR-hochalem: Hochàlemmànnisch (Hìniga, Pfìrt, usw.) "
```
> Add Alsatian variants

- server/src/config-helper.ts
* #4845
* #4708 
* #4389 
* #4003
This PR: 
* Changes the logic in the `configuration-helper.ts` and no longer checks for a `config.json` file, which was causing confusion with people setting up their own development environment, as it threw an error if it wasn't found, _even though_ it wasn't required. 
* Removes references to `loadedConfig` which no longer serves a purpose AFAICT
* Adds better semantic logging of what's happening through `console.log`
* Provides better failure message if dotenv file not found 
I do have some questions about things that I don't understand in this file: 
* I don't understand how `injectedConfig` works, or what purpose it serves? 
* With the logging I added, I can see that the config gets loaded _a lot_. I couldn't see an easy way to log _what_ was being …
> Update config-helper to ignore non-existent config.json

- server/src/lib/model/db/migrations/20250607160000-fix-for-basque-accent-typo.ts
This is simply a re-implementation of PR #4323 as a fix for the issue #4287 
This is done as a template because the PR became stale due to inactivity.
All acknowledgement goes to the people in that issue and PR.
> 1155-MCV Re-implement fix for eu accent typo

- server/src/lib/api.ts
- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- server/src/lib/model.ts
- server/src/lib/validation/clips.ts
- server/src/lib/validation/sentences.ts
- web/src/services/api.ts
When a user sets a variant and "show only sentences/clips from my variant", the system shows "you are out of sentences/clips".
We want to give an option to the user to continue with sentences/clips from any variant (including those without any variant).
This PR handles the backend of this with an `ignoreClientVariant=true` query parameter (default false) which should be called from front-end after a button click.
> 1157- Backend to retrieve sentences & clips without variant when variant ones run out

- bundler/Dockerfile
Simple fix for bundler not working in `docker compose up`, preventing developers and also releases.
This has also been reported here: https://github.com/common-voice/CorporaCreator/issues/129
> 1166-CC Fix setuptools version to fix bundler problems

- server/src/lib/lazy-cache.ts
- server/src/lib/model/db.ts
This fixes a race condition we debugged.
Many new and/or low-resource languages must have seen this: You remember that you already recorded a sentence, you record it again, but when you submit it a pop-up comes out saying it could not be saved with two options: Retry - Cancel.
Even if you retry, you cannot pass it, the only way is to press cancel.
We found out the code is correct, but there is a race condition: The database (DB) updates are slower than selects.  Here is what was happening:
- The front-end (FE) requests 25 sentences for being recorded. The back-end (BE) provides them.
- The user submits 25 sentences 5 by 5. The first 4 batches go without a problem. After the last 5 (or less remaining) are sent, FE requests a new batch (of 25).
- While the database is updating the sentence …
> 1173-MCV Fix: Use Redis to keep recorded "sentence_id"s per user

- bundler/queries/bundleLocale.sql
This should fix https://github.com/common-voice/common-voice/issues/4794
- **Not tested** on live data (I don't have it on local dev env)!
- **TODO**: We need to put a note in [cv_dataset repo](https://github.com/common-voice/cv-dataset)'s `CHANGELOG.md` for this change.
- **NOTE**: Older releases will not be affected, so one should check dataset version to determine the separator in post-processing scripts.
> Fix: Change accents separator to "|" from default "," in bundles/metadata

- server/src/lib/lazy-cache.ts
Fixes long expire duration for Redis caching (ms => sec conversion was needed)
> 1184-MCV-BE Fix: Scale ms to seconds for expire

- web/locales/common-voice/en/pages/home.ftl
Add missing accessibility key `about-menu-aria-label` for main menu item "About".
> Add missing about-menu-aria-label

- server/src/lib/model/db/migrations/20250705160000-update-sentence-bands.ts
This migration sets sentence bands after a detailed analysis.
- Compared Pontoon locale data with MCV locales, checking population values
- Already is_contributable locales are left out
- Bands could be set to a lower level for any reason, these are also left out
- Thus this migration only sets locales (mostly new additions) to a lower band
> Update sentence bands

- .env-local-docker.example
- docs/DEVELOPMENT.md
- server/src/config-helper.ts
* #4973 
* #4885 
* Minor change to `.env-local-docker.example` to uncomment the `CV_FXA_*` key-value pairs 
* Add comments to guide developers 
* No changes required to `DEVELOPMENT.md`
* git checkout 4973-bug-commenting-out-of-cv_fxa_-key-values-in-env-local-docker-causes-halt-at-startup-when-building-dev-environment 
* build fresh docker containers, as a new dev setting up a local dev environment would with 
```
docker image prune --all --force
```
* copy new `.env-local-docker.example` to `.env-local-docker` 
```
cp .env-local-docker.example .env-local-docker
```
* build and run docker containers 
```
docker compose up
```
=> running localhost:9000 OK
* @moz-bozden for sense-checking and peer review
> Uncomment CV_FXA_* key-value pairs, add comments referring to set up Auth0

- server/src/test/api/profile/handler/create-api-credentials-handler.test.ts
- server/src/test/api/profile/handler/delete-api-credentials-handler.test.ts
- server/src/test/api/profile/handler/get-api-credentials-handler.test.ts
- server/src/test/application/profile/command-handler/createClientCredentialsCommandHandler.test.ts
- server/src/test/application/profile/command-handler/deleteClientCredentialsCommandHandler.test.ts
- server/src/test/application/profile/query-handler/getClientCredentialsQueryHandler.test.ts
- server/src/test/infrastructure/authentication/authentication.test.ts
On the server-side, add the remaining tests for all operations on the public API for credentials including the command and query handlers and the methods in authentication.
> Add additional tests for public API credentials

- server/src/lib/clip.ts
- web/locales/common-voice/en/pages/error.ftl
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
Although we fixed the main reason here (https://github.com/common-voice/common-voice/pull/4944) we still have some remaining errors. This PR changes the upload workflow to handle these, while we can continue to find the real reason:
- Instead of showing retry/cancel after each duplicate-clip problem, the new workflow sends the whole batch (1-5) and reports back at the end with an alert box where the user can only say OK (no retry option, because it will fail again).
- Clip sending will still be retried 3 times internally e.g. temporary for communication errors, but without the Retry button (which you can never pass) there will be 3 errors recorded for duplicate clips.
- This enables a better experience for the user and a better feedback on what is actually happening.
- We will have …
> 1187-MCV Change clip-upload process to handle remaining duplicate-clip errors

- web/src/components/pages/profile/info/languages/input-language-accents/input-language-accents-input.tsx
- web/src/components/pages/profile/info/languages/languages.css
- Fixes https://github.com/common-voice/common-voice/issues/4378
- Adapts styling of Downshift (component used in accent select) to variant selector - as much as possible, but I kept the bottom-border for better visibility.
**Wide screen - Short list**
**Wide screen - Long list**
**Mobile screen - Long list**
> Fix overflow in long accent lists and adapt style to variant selector

- server/src/lib/model/db/migrations/20250731160000-remove-defunct-hi-in-locale.ts
`hi-IN` is a variant requested and opened in Pontoon in the past - without any translations, after a while it was removed in favor of `hi`. In the meantime some users added it as a language and even added some accents. No other data (sentence, clip etc) is attached. It is also not on Pontoon anymore...
This migration removes `hi-IN` language with all its remnants from the database.
See internal issue 1222 for detailed analysis.
> 1272-Add migration to remove hi-IN locale with remnants

- web/src/components/languages-provider.tsx
There was a render timing issue within languages-provider.ts in LanguageRoutes component, giving the following error in console:
```
languages-provider.tsx:73 Warning: Cannot update a component (`LanguagesProvider`) while rendering a different component (`Router.Consumer`). To locate the bad setState() call inside `Router.Consumer`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render Error Component Stack
at Route (react-router.js:414:1)
at sentryRoute(Route) (<anonymous>)
at Switch (react-router.js:616:1)
at LanguageRoutes (languages-provider.tsx:46:1)
at LocalizationProvider (provider.js:24:1)
at LanguagesProvider (languages-provider.tsx:113:1)
at Router (react-router.js:45:1)
...
```
This PR handles it by introducing useEffect (dependency …
> 1296-Fix render timing issues in LanguageRoutes with useEffect and setTimeout

- web/src/components/localization-select/localization-select-complex.tsx
- web/src/components/localization-select/localization-select.css
The language picker shows native language names, but if the translators did not translate the language name in Pontoon (yet), they are shown as language codes.
In this PR, we check if the name = code and show them as localized strings: In the current selected language, if exists - else English name will be fallback. We also show the language code in parenthesis so that native speakers can also locate them from the code.
Example below shows some examples in Turkish interface.
Whenever they get translated in respective locales, the new native values will be shown (after a production release).
For more info see item no 5 in internal issue 1292.
> 1295-Workaround for picker not showing all locale names

- web/src/components/languages-provider.tsx
- web/src/urls.ts
Spontaneous Speech uses browser local-storage to keep the current UI language.
This PR does two things:
- Implement local-storage based UI language passing (from SS to CV or vice-versa)
- Makes menu items adaptive to installation (they will not point to production site anymore, a prerequisite for the time when SS repo becomes public)
Notes:
- In some cases localStorage cannot be used (e.g. private tabs), so will will fall-back to English (if the URL does not contain a language). Actually this is the current behavior.
- Another PR in SS repo will compliment this
> 1299-V1 Make use of local storage to pass UI language info to SS

- web/src/components/pages/dashboard/stats/stats.tsx
This was happening in Dashboard, used by many, resulting in many error logs.
There was an old code returning early, which violated the rule-of-hooks (hooks should not be conditional). We started to investigate in #5037 and could pinpoint the location.
There is also a chance that this also fixes frequent re-logins when the user refreshes the page to solve the problem - we'll monitor it...
> 1314-Fix rule-of-hooks problem

- server/src/lib/model/db/migration-helpers/accents-variants/accents.ts
- server/src/lib/model/db/migration-helpers/accents-variants/index.ts
- server/src/lib/model/db/migration-helpers/accents-variants/locales/default.ts
- server/src/lib/model/db/migration-helpers/accents-variants/locales/index.ts
- server/src/lib/model/db/migration-helpers/accents-variants/types.ts
- server/src/lib/model/db/migration-helpers/accents-variants/users.ts
- server/src/lib/model/db/migration-helpers/accents-variants/variants.ts
- server/src/lib/model/db/migration-helpers/common/index.ts
- server/src/lib/model/db/migration-helpers/common/locales.ts
- server/src/lib/model/db/migration-helpers/index.ts
- server/src/lib/model/db/migrations/20250801130000-migrate-accents-variants-ga-ie.ts
This PR adds generic migration helper code for migrating old accents to new variants, and applies it to Irish `ga-IE` case, to fulfill the request in https://github.com/common-voice/common-voice/issues/4993
The code is generic, but should not be reused without extensive testing in local development environment.
> 1276-Irish (ga-IE) accent to variant migration

- server/src/lib/lazy-cache.ts
When people are getting variant-only clips, the query takes longer than expected, thus Redis based LazyCache default lock duration of 3 minutes was not enough, causing lock-release issues.
With this workaround, we increase the lock duration to 5 minutes, until the related queries are more optimized.
> 1325-Increase default LazyCache lock duration as a workaround

- web/locales/spontaneous-speech/en/pages/common.ftl
Removing language keys in SS, which already exist in Pontoon, thus in CV. Still two to go.
These have already been cross-checked/approved in internal issue 1306.
> 1306-Remove duplicate language code key definitions in SS .ftl

- server/src/lib/model/user-client.ts
The DB gets NULL value, which is not allowed, so if not TRUE/1 we force to 0 (handle "undefined").
> 1358-Fix update query for user-variant is_preferred_option sometimes fail

- server/src/lib/model/db/import-sentences.ts
- server/src/server.ts
According to the comment on `importSentences()`: `If no IMPORT_LANGUAGES specified, all from the file system, else the intersection.`
This condition is implemented by checking the length of the array from splitting IMPORT_LANGUAGES string.
However, this array is produced by `trim().split(',')`. In Javascript, splitting a string which does not contain the separator yields an array with the original string as only element. This causes `[""]` to be used as set of languages, which fails to import anything.
> Fix IMPORT_LANGUAGES not working as intended when unset

- common/language.ts
- server/src/lib/api.ts
- server/src/lib/model.ts
- server/src/lib/model/db.ts
Provides language data with variants and predefined-accents embedded under a language.
This will very much simplify language data handling in Public API and Spontaneous Speech.
Notes:
- Removes previously added /language/accents/predefined
- Specified the caching period to 6 hours to speed up new updates - it is very low cost...
> 1385-Add /languagedata endpoint and remove predefined accents endpoint
