- ios/voicebank-ios-wrapper/Info.plist
- ios/voicebank-ios-wrapper/ViewController.swift
- ios/voicebank-ios-wrapper/index-cv.html
> API to control device orientation.

- config.json
- package-lock.json
- package.json
- server/src/lib/clip.ts
- server/src/lib/db/mysql.ts
- server/src/lib/db/postgres.ts
- server/src/lib/files.ts
- server/src/promisify.ts
- server/tsconfig.json
- tools/createS3.js
Should save everything to S3, convert S3 ogg's to mp3's.
Still need to test the "listen" part, but can't as the "listen" functionality is broken in the master.
I don't want a through review, just a quick look over the come to make sure it doesn't suck too much.
FYI: To set up S3 you should create `~/.aws/credentials` and set it up as follows
```bash
kdaviss-MacBook-Pro:src kdavis$ cat ~/.aws/credentials 
[default]
aws_access_key_id = <my aws_access_key_id>
aws_secret_access_key = <my aws_secret_access_key>
```
after that it all works magically
> Fixed #68 and fixed #89

- server/src/lib/clip.ts
> Fixed #101

- package.json
- server/src/lib/aws.ts
- server/src/lib/clip.ts
- server/src/lib/files.ts
> Use outbound proxy for HTTP calls when present

- server/src/lib/clip.ts
- server/src/lib/files.ts
- server/src/server.ts
Hopefully this simplifies the audio handling a bit. This pull request
However, it does not yet move from sox to something else.
> Fixed #111

- ios/voicebank-ios-wrapper/Base.lproj/Main.storyboard
- ios/voicebank-ios-wrapper/ViewController.swift
> adding timer to check for connectivity

- web/css/index.css
> Fix row wrapping for recordings submit page

- web/src/lib/components/listen-box.tsx
> preload audio

- ios/voicebank-ios-wrapper/BrowserViewController.swift
hi
I implemented `UIAlertViewController` for `webView(_ webView: UIWebView, didFailLoadWithError error: Error) ` method  .  
If user want to load the page again , I  reloaded the page . To implement this  , I make _url to class variable in `BrowserViewController` . In other side If user want to go back to main view , then it will be loaded with `dismiss` . 
Thanks
Elia
> BrowserViewController Update : added UIAlertViewController for WebView Element

- gulpfile.js
> Increase restart delay to 2.5 seconds

- nubis/builder/project.json
- nubis/terraform/consul.tf
- nubis/terraform/main.tf
> Upgrade to Nubis v1.5.0

- package-lock.json
- package.json
- server/src/lib/files.ts
@Could you take a look at this?
I found a way to "continue" the S3 getObject's call so that it walks through all the elements in S3 50 at a time and caches these elements in on the server. I make the update more often as it's only getting 50 elements each time.
Maybe in future we need to think about limiting the number of elements in that are cached on the server. But for now, this will get the the job done with respect to better randomization.
> Fixed #255

- gulpfile.js
- nubis/puppet/node.pp
> Use forever to run the node app, ensuring restarts on crashes

- server/data/new-sentences.txt
Fixed Spelling Error. "But maybe" spelled as "Butmaybe".
> Fixed Spelling Error in new-sentences.txt

- server/data/new-sentences.txt
All of the sentences come from my own personal writing with certain details replaced or rephrased.
> Original sentences for Common Voice

- server/data/funny.txt
> Typo fix for #328

- server/data/new-sentences.txt
To fix issue #331 (https://github.com/mozilla/voice-web/issues/331)
Typo in new-sentences.txt ("t6" instead of "to")
> Pull request to fix issue #331

- web/src/lib/components/pages/faq.tsx
> Add text sources to FAQ

- server/src/lib/logger.ts
- server/src/server.ts
@gozer can you tell me if this output fulfills your logging requirements?
> make all console operations output json, closes #308

- nubis/puppet/logs.pp
> Tell fluentd about our new JSON logs

- web/css/index.css
- web/src/lib/components/pages/profile.tsx
This is a proposed fix for #173
> Moving label for "email" outside of input div

- web/css/index.css
> Specify size for check boxes

- .gitignore
- web/css/index.css
Fixes #163 
@MycroftAI
https://mycroft.ai/
> #163 - [MycroftAI] Adding visual feedback on play/delete button

- README.md
Potentially useful information for new contributors. Also prevents confusion about what Nubis is (#350).
> Added directories explanation to README

- web/css/index.css
- web/src/lib/components/listen-box.tsx
Fixes #212 
@MycroftAI
https://mycroft.ai/
> #212 - shouldn't be able to click yes/no without having first played the sample

- nubis/builder/provisioners.json
- nubis/puppet/web.pp
> Use a real DocumentRoot into web/ and serve images, fonts and css out of it

- nubis/puppet/logs.pp
- nubis/puppet/web.pp
- images => 30 minutes 
- css    => 30 minutes
- fonts  => 6 hours
Fixes #375
> Add some default browser caching with expires 

- nubis/puppet/web.pp
> Deflate missed mime-types

- web/src/lib/components/pages/record.tsx
- web/src/lib/components/pages/record/audio-ios.ts
- web/src/lib/components/pages/record/audio-web.ts
> Add to check if audio recording is supported by browser by checking availability of MediaRecorder API

- web/css/index.css
- web/src/lib/components/icon.tsx
- web/src/lib/components/pages.tsx
I have moved the discourse link to the blue bottom bar
> Discourse link moved to blue bottom bar

- web/src/lib/components/listen-box.tsx
> Reset listen box state

- server/data/mds3dstn71.txt
Hello. I hope this PR is okay.
> Add mds3dstn71 sentences for #341

- web/src/lib/api.ts
- web/src/lib/app.tsx
- web/src/lib/components/pages.tsx
- web/src/lib/components/pages/record.tsx
- web/src/lib/components/pages/record/audio-web.ts
- web/src/lib/components/validator.tsx
- web/src/main.ts
> Change code style to async/await in web folder

- web/src/lib/components/listen-box.tsx
This reverts commit d31de9407ab64f8d7fd0672fc22294630377f5a7.
> Revert "Only load audio src in ListenBox if it's defined (#442)"

- web/src/lib/components/listen-box.tsx
> Add back in "Only load audio src in ListenBox if it's defined (#442)""

- CONTRIBUTING.md
- README.md
This is a very bare bones draft of a potential future CONTRIBUTING.md file for this project (and the README adapted accordingly). 
There were a few questions that popped up along the way:
- Is the Mozilla Community Participation Guidelines actually the CoC that governs this project? And I think we should add how people can report unacceptable behavior. 
- I think it's essential to add a section called "What You Should Know" that covers the basics of the project, but I would need more information about how the project modules work and what frameworks/software/important tools are being used.
- Should we include information about how to run tests? 
- Are there any other software requirements that are missing? 
- Additionally, should information about configuration go here? There were some …
> Contributing Guide WIP

- CONTRIBUTING.md
- README.md
- Added a separate Discussion section to the README with Discourse, the GitHub issue tracker and IRC.
- In `CONTRIBUTING.md`, moved the `gulp help` command directly after the other commands.
- Changed some wording in the 'Project Directory Structure' section and added links to used libraries.
> Minor changes in README and CONTRIBUTING

- server/data/SNIPS_AddToPlaylist.txt
- server/data/SNIPS_BookRestaurant.txt
- server/data/SNIPS_GetWeather.txt
- server/data/SNIPS_PlayMusic.txt
- server/data/SNIPS_RateBook.txt
- server/data/SNIPS_SearchCreativeWork.txt
- server/data/SNIPS_SearchScreeningEvent.txt
@kdavis-mozilla This adds 13.7K sentences from the SNIPS benchmark for speech products. They were kind enough to release the data under cc-0 for us. Shall we try this out for a while?
1.) https://github.com/snipsco/nlu-benchmark
> add command corpus from snip nlu benchmark, improves #23

- server/data/ceejaydeepee.txt
- server/data/est31.txt
- server/data/jf99.txt
- server/data/tmm88.txt
- server/data/vkatsikaros.txt
These changes will add sentences from:
- [Ceejaydeepee](https://pastebin.com/pWM1y61d)
- [tmm88](https://pastebin.com/3VHV0cY1)
- [jf99](https://pastebin.com/gLTMV3kb)
- [vkatsikaros](https://gist.github.com/vkatsikaros/551c284c609a62a4fa8035b612e0838f)
- [est31](https://gist.github.com/est31/166021fc4a9efc6f82caf9ba50498be9)
I included the raw version of the sentences (except for tmm88's sentences which included numbers before each line). Edit: I've notice too late that tmm8's contributions have a lot of phrases and incomplete sentences. Might need to be reverted?
> Add sentences for #341

- web/css/index.css
Fixes #501
This PR changes to background color of .sentence-box to `#E7E5E2`
> change background color of .sentence-box

- web/src/lib/components/pages/record.tsx
> Change Play/Stop to Review

- package-lock.json
- web/src/lib/components/pages/record.tsx
Update voice-submit headline/subhead.  Let us know if there were any problems with our pull.
> Michael Brooks and Margaret Berry fixed issue 499 

- README.md
**this PR does basically aim at:**
- *adding ToC (Table of Contents) - to README.md file*
---
**main motivation behind such:**
- *improving overall document accessibility*
- *contributing to improve document and increase in a small factor the possibility of receiving addition PRs*
> docs - README.md -> adding ToC (Table of Contents)

- CONTRIBUTING.md
- HOWOTO_S3.md
Add a step-by-step guide to creating an aws service account, setting up S3 buckets and IAM credentials, and configuring those credentials via aws cli ui and config.json.
Resolves #522
> Add S3 setup guide/howto

- package-lock.json
- web/css/index.css
Update footer links to match primary green #b7d43f UI color.
> #498 Update footer link color 

- package-lock.json
- web/css/index.css
update help-links color to #e7e5e2
> #497 Update footer help-links background color

- web/src/lib/components/icon.tsx
- web/src/lib/components/listen-box.tsx
As per discussion in #285, I have changed the pause button to have a stop function, and it looks like a stop button.
> Changed pause function and icon to stop in listen mode

- web/css/index.css
- web/src/lib/components/listen-box.tsx
Fixes #502
This PR updates the styling of the re-record / delete button.
> Change delete box styling

- config.json
- nubis/puppet/files/confd/templates/voice.json.tmpl
- nubis/puppet/node.pp
- server/src/lib/utility.ts
- server/src/server.ts
> Use our environment as part of leadership determination

- server/data/reinhart1010.txt
Adding 8 new sample sentences with 3 new words:
+ Billowing
+ Remuneration
+ Insipid
I am trying to add more new words instead of more sentences, so there will be a larger corpus of vocabularies to be analyzed in Common Voice.
> Added reinhart1010.txt

- web/src/lib/components/pages.tsx
> remove home from desktop navigation

- web/src/lib/app.tsx
> Update page content on back/forward buttons

- nubis/puppet/logs.pp
> Start reading the logfile at the beginning, important at node startup

- web/css/index.css
was limited in possible horizontal space by the page structure and didn't want to start fiddling with the center column size, if more space is needed we would have to look into that #546
> updated box shadow and added space in box

- web/css/index.css
- web/src/lib/components/pages/record.tsx
added a little more vertical space as per the mockup #548
> Redesign record button

- web/src/lib/components/pages/record/record.css
- web/src/lib/components/pages/record/record.tsx
- web/src/lib/components/vars.css
Changes for #549:
* Add horizontal divider
* Add profile button
* Add collapsible section for "why profile?"
I tried to match the design in the screenshot as best as I could.
> Add Profile actions underneath record

- web/src/lib/components/pages/record/record.tsx
Just fixing a few typos in string and comments.
> Fix a few typos in record.tsx

- web/src/lib/api.ts
Some clean-up and de-duplication of the API service in the web part.
> Clean up web/api.ts

- gulpfile.js
- package.json
- yarn.lock
> Sourcemaps

- web/src/lib/components/pages/record/record.tsx
Fixes #526 
Let me know if I need to rebase this by the time you get a chance to look at this.
> Keep sentence in same position after re-recording

- web/src/lib/components/pages/record/profile-actions.css
- web/src/lib/components/pages/record/profile-actions.tsx
- web/src/lib/components/pages/record/record.css
- web/src/lib/components/pages/record/record.tsx
- web/src/lib/user.ts
> show profile form underneath record

- web/src/lib/components/icon.tsx
- web/src/lib/components/index.css
- web/src/lib/components/listen-box/listen-box.css
- web/src/lib/components/pages/record/profile-actions.tsx
- web/src/lib/components/pages/record/record.css
- web/src/lib/components/pages/record/record.tsx
- web/src/lib/components/pages/record/review.css
- web/src/lib/components/pages/record/review.tsx
- web/src/lib/components/vars.css
> Redesign Recordings Review

- docs/HOWTO_S3.md
- server/src/lib/api.ts
- server/src/lib/bucket.ts
- server/src/lib/clip.ts
- server/src/s3-service.ts
- server/src/server.ts
This PR improves the way S3 is created inside the server and solves the issue of getting an error when trying to use the eu-central-1 region for S3 buckets. Details were added to the issue that this PR resolves #569
> Improved the way S3 is created inside the server

- server/data/shakespeare_phrases.txt
- server/data/tww.id.au.proverbs.txt
proverbs from http://tww.id.au/proverbs/proverbs.html labeled "Please feel free to copy these proverbs and distribute them to the younger generation. "
and Shakespeare from http://www.pathguy.com/shakeswo.htm
via https://github.com/dariusk/corpora cc0 git repo
> New Sentences

- server/data/DNGros.txt
These sentences were posted on issue https://github.com/mozilla/voice-web/issues/341 as pastebin link, but were never merged. This pull requests adds a few hundred more sentences to that original paste. It contains some fairly general sentences as well as mix of numbers, acronyms, and names that may not currently be in the dataset but would be important for an STT system to be able to accommodate. It also contains a few sentences that a similar to each other or sentences that others have written except for small changes which can hopefully serve as examples to identify over fitting.
> Add 500 new sentences

- web/src/lib/components/alert/alert.css
- web/src/lib/components/alert/alert.tsx
- web/src/lib/components/index.css
- web/src/lib/components/pages/record/record.tsx
> Add alert component to record page

- package.json
- yarn.lock
I do want this:
But it looks like they require all-access on the organization for that, which is a no-go.
https://github.com/siddharthkp/bundlesize#2-build-status
So for now it only checks whether the bundle size exceeds 100kb and if so, the test fails.
> Set bundle size limit to 100kb

- server/data/DictionaryofForeignPhrases.txt
~300 lines from "Dictionary of foreign phrases and classical quotations:"
link:
http://archive.org/details/cu31924031292554
right:
https://archive.org/details/cornell&tab=about 
"There are no known copyright restrictions in the United States on the use of the texts.
More information on rights issues associated with public domain texts
can be found at http://cdl.library.cornell.edu/guidelines.html."
> Some more public domain sentences

- web/src/lib/components/pages/record/profile-actions.css
- web/src/lib/components/pages/record/profile-actions.tsx
> Add success alert for profile creation

- server/data/not-used/SNIPS_AddToPlaylist.txt
- server/data/not-used/SNIPS_GetWeather.txt
* Missing apostrophe 's'
* 's of
* it's vs its
* St., Mrs., Mr.
* ATVs
* EMTs
* 20s, 30s, 50s, 60s, 70s, 80s
* -ies
* 's' to 'a'
* 'an' before vowel sounds
* 'a' before non-vowel sound
* Some typos
> Fix some grammar mistakes

- server/data/reinhart1010.txt
Again, these new sentences are made to popularize these rare-occuring words in all sample sentences. New words such as _lachrymosity_ are also added.
> Added 27 more sentences

- CONTRIBUTING.md
Add fork and clone instructions
> Add fork and clone instructions

- server/src/config-helper.ts
- server/src/lib/bucket.ts
- server/src/lib/model.ts
- server/src/lib/model/clips.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/tables/clip-table.ts
- server/src/server.ts
Started this with going directly to the DB for every request, which took a sec even with this small dataset. So I built some per-instance caching into it, so it's reasonably fast now.
Also added a flag in the config for whether migrations should be enabled.
> Clips from DB

- web/src/components/nav.css
Intended to address issue https://github.com/mozilla/voice-web/issues/717
Before:
After:
> [Mobile] Make hamburger icon skinnier.

- web/src/components/pages/home/project-status.css
Intends to fix issue #712. Screenshot:
> Progress widget adjustments

- server/src/config-helper.ts
- server/src/lib/clip.ts
- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/tables/user-client-table.ts
- web/src/services/api.ts
- web/src/stores/user.ts
Demographics are now synced with every user sync and not only on when submitting clips
> Demographics in DB

- server/src/lib/api.ts
- server/src/lib/clip.ts
- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/server.ts
@mikehenrty I'm still setting `isMigrated` from the outside but I still feel agnostic about that, so if it feels wrong to you I can switch it to `setIsMigrated` or whatever you think would be more readable/consistent.
> Write Clips & Votes to DB

- README.md
[Docs] - VoiceWeb - README.md - spelling (minor issues)
> [Docs] - VoiceWeb - README.md - spelling (minor issues)

- nubis/puppet/node.pp
> Upgrade to node 8.x

- server/data/DNGros.txt
- server/data/DictionaryofForeignPhrases.txt
- server/data/activate.txt
- server/data/ajaydee.txt
- server/data/harvsents.txt
- server/data/jf99.txt
- server/data/mlennox.txt
- server/data/pro.gadget.txt
- server/data/thehowl.txt
- server/data/tlcoles.txt
The goal of this PR is to cleanup the used corpus data sets.
> Corpus: cleanup used data sets

- .editorconfig
- web/src/components/alert/alert.css
- web/src/components/index.css
- web/src/components/nav.css
- web/src/components/pages/data/data.css
- web/src/components/pages/record/record.css
- web/src/components/ui/ui.css
- web/src/components/vars.css
> Add editorconfig

- nubis/puppet/logs.pp
> Parse systemd's journal for JSON formatted messages

- web/locales/en/messages.ftl
- web/src/components/contact-modal/contact-modal.tsx
> Fluentify contact modal

- web/src/components/listen-box/listen-box.css
> Fix focus on listen box

- contribute.json
- web/contribute.json
I made this because of issue #981.
I scanned the contribute.json at https://www.contributejson.org/ and it passed.
Please review the keywords that I have chosen.
> Add contribute.json

- server/data/de/german-cities.txt
Created german sentences and filled them with german city names from german cities with population > 50000.
I created these template sentences https://pastebin.com/C90NCgke (updated) and filled them random with names from german cities taken with this [Wikidata Query](https://query.wikidata.org/#SELECT%20%3FitemLabel%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ515.%0A%20%20%3Fitem%20wdt%3AP17%20wd%3AQ183.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel.%0A%20%20%3Fitem%20wdt%3AP1082%20%3Fpopulation.%0A%20%20FILTER%28%28LANG%28%3FitemLabel%29%29%20%3D%20%22de%22%29%0A%20%20FILTER%28%3Fpopulation%20%3E%2050000%29%0A%7D%20group%20by%20%3Fitem%20%3FitemLabel)
With this template and query we could also create this for cities from Austria, Switzerland or international Cities
> german sentences with city names

- web/src/components/pages/data/data.tsx
Adjusted the link to the third release instead of the first.
Concerns issue #1010
> Updated link to TED-LIUM.

- server/data/de/jf99.txt
> [German data] Small punctuation fix

- server/data/de/german-cities.txt
- server/data/de/jf99.txt
I hope this does not conflict with PR #1071.
> Sentence corrections

- android/app/proguard-rules.pro
- server/webpack.config.js
- web/src/components/pages/data/data.tsx
I forgot a couple links last time, made the adjustments.
Concerns #1027
> Update HTTP links to HTTPS.

- server/data/br/ofis_publik_ar_brezhoneg_parallel.txt
Here are some sentences from a public domain parallel corpus of Breton also produced by _Ofis Publik ar Brezhoneg_ but these are ones that end with ? and !
> add breton text with questions and exclamations from OfisPublik corpus

- docker-compose.yaml
> Run yarn on local docker dev setup.

- server/data/kab/corpus-litterature-part1.text
Corpus part one extracted from novels, short stories, daily language, proverbs
> kabyle corpus part1

- server/data/ca/common-short-sentences.txt
- server/data/ca/dogc.txt
- server/data/ca/dogv.txt
- server/data/ca/tocqueville.txt
- server/data/ca/widespread-proverbs.txt
- web/src/stores/user.ts
- 5 Catalan territorial accents. 
- 13K Catalan sentences. See license here: https://github.com/Softcatala/ca-text-corpus
> Catalan accents and sentences

- web/src/stores/user.ts
> Irish major dialacts

- server/data/ga-IE/uachtaran.txt
Important fixes which should improve quality of submitted recordings
> Fix more typos in Irish sentences

- server/data/it/frasi.txt
- web/locales/dsb/messages.ftl
This is a work made by the Mozilla Italia community members in the last weeks.
> First upload of 7440 italian sentences

- server/data/ga-IE/seananocoistin.txt
From: https://github.com/languagetool-org/languagetool/pull/915
> Irish sentences from Seanán Ó Coistín

- server/data/fr/lulucmy-places
Hi,
I made a list of French sentences (for books of the 18th and 19th centuries) about French places.
Some are from Jean-Jacques Baude, Victor Hugo, or Théophile Gautier.
I will add some other sentences from other books if I find good ones.
> French places names / Sentences

- server/data/de/jf99.txt
Siehe auch: https://grammis.ids-mannheim.de/rechtschreibung/6194
> [German data] Small spelling fix

- web/src/components/app.tsx
> Pause upload progress animation.

- server/data/kab/named-entities1.txt
named entities - part1:
Organization names (political organization)
Cities, villages and places in Kabylia
Person names and affiliation
> Kabyle named entities

- server/data/fr/gerard-majax.txt
- server/data/fr/ofis_publik_ar_brezhoneg.txt
@mikehenrty here is a PR to deduplicate the french files, see #1220.
> deduplicate french sentences

- server/data/kab/general-newtech1.txt
Daily expression, some expressions we used on Mozilla kab translation to introduce the new tech language.
> [lang:kab] Create general-newtech1.txt

- server/data/it/frasi.txt
We are working to change the size of sentences to a maximum of 125 characters because Italian can be very verbose and the time of the UI is not enough sometimes.
> Italian improvements

- web/src/components/alert/alert.css
- web/src/components/contact-modal/contact-modal.css
- web/src/components/layout/nav.css
- web/src/components/listen-box/listen-box.css
- web/src/components/pages/data/data.css
- web/src/components/pages/home/home.css
- web/src/components/pages/home/project-status.css
- web/src/components/pages/record/record.css
- web/src/components/pages/record/review.css
- web/src/components/profile-form/profile-form.css
- web/src/components/progress-bar/progress-bar.css
- web/src/components/request-language-modal/request-language-modal.css
- web/src/confirm/confirm.css
Hi! First-time contributor here. Thought I'd pick CSS nesting from #912 as a simple starter task.
Let me know if there are any issues or if I missed any files.
> Use nesting for CSS

- server/data/fr/ofis_publik_ar_brezhoneg.txt
By the way, the formulations for this set of sentences is a bit unusual and vague because speaker may like interpret it as a question "are you sure we liked?" rather than "you're sure we liked".
(@ftyers)
> [lang:fr] grammar error

- server/data/it/frasi.txt
We use very a lot of badwords in our language but is better to remove them from a public project.
We made also other few fixes.
> Italian removing badwords

- server/data/en/elleo.txt
> Fix a sentence

- server/data/de/german-cities.txt
- server/data/de/jf99.txt
- server/data/de/zeno.txt
> Sentence corrections2

- server/data/fr/ofis_publik_ar_brezhoneg.txt
A small error that slipped through the cracks. I noticed it while recording.
> [fr] fix a mistake in ofis_publik_ar_brezhoneg.txt

- server/data/it/frasi.txt
> Short sentences for Italian

- server/data/ca/programari-lliure-llibre.txt
> Add programari lliure book (#1)

- server/data/ga-IE/seananocoistin.txt
> [Irish] some corrections

- server/data/de/countries-and-cities.txt
The first sentence is a „Subjektsatz“. The second sentence is a „Infinitivsatz“ with _ohne_. Comma is mandatory. See also: [§ 75 (1)](https://grammis.ids-mannheim.de/rechtschreibung/6201#par75)
> [German data] fix punctuation in 2 sentences

- server/data/eo/krestomatio.txt
These are some of the sentences (less than 10 words) from the "Fundamenta Krestomatio de la Lingvo Esperanto" (https://www.gutenberg.org/files/8224/8224-h/8224-h.htm)
> List of sentences for Esperanto (eo)

- web/src/stores/user.ts
> Renamed ca (Catalan) accents

- server/data/sl/EngCVSentTranslToSlo.txt
- server/data/sl/Sayingsfromallovertheworld.txt
I updated a few sentences that didn't sound well enough. 
Kind regards.
> Slovenian sentences - update

- web/src/stores/user.ts
> Added Esperanto accents

- server/data/nl/danielsjf.txt
@pcmill @sroet Here are another 500 sentences to bring us closer to the 5000 sentences.
> Another 500 Dutch sentences

- server/data/ca/cities.txt
Cities from Andorra, Balear Islands, Catalonia, and Valencia zones
> Catalan: Create cities.txt

- server/data/ca/common-voice-sentences.txt
Senteces written specifically for Common Voice under CC0 licence. See https://github.com/Softcatala/ca-text-corpus/blob/master/README.md
> Catalan: Create common-voice-sentences.txt

- server/data/it/frasi.txt
It is a working in progress and not yet ready to be merged.
> Another italian revision to finish the file

- web/src/components/listen-box/listen-box.tsx
- web/src/components/normalized-player.tsx
- web/src/components/pages/contribution/listen/listen.tsx
Implement audio normalization on the client, using a method based on ReplayGain.
Fixes #336
> Normalize audio for verification

- docker-compose.yaml
#1457 docker using networks instead of links
> docker using networks instead of links

- server/data/nl/danielsjf.txt
Correct some typo's in Dutch sentences
> Correct some typo's in Dutch sentences

- server/data/nl/danielsjf.txt
> Update Dutch sentences

- server/data/de/DonHege.txt
These are the German sentences provided by @DonHege in https://github.com/mozilla/voice-web/issues/341#issuecomment-423515499. I have reviewed them, but let's wait for DonHege's agreement.
@DonHege Have a look at my corrections and check if you agree with them. I made 1 commit for correcting mistakes and 1 commit for proposed changes.
Der Ausdruck "Wallbox" war mir nicht geläufig und scheint eine Markenbezeichung von BMW zu sein? Mein Vorschlag wäre "Wandladestation" (Weiterleitung von Wikipedia). Markennamen sind nicht nicht verboten, würde ich aber tendenziell auf landläufige Begriffe wie Tesafilm oder iPhone bschränken.
Außerdem habe ich als Ziffern geschriebene Zahlen durch Wörter ersetzt und Anführungszeichen entfernt, weil irgendwer entschieden hat, dass die nicht mit in die …
> merge sentences from @DonHege

- server/data/cy/brawddegauindeg.txt
Helo
Could you add the attached 300 new Welsh language sentences to CommonVoice? 
They have been composed by Indeg Williams (PhD student at Bangor University) and therefore acceptable for CC-0 licensing purposes. 
Diolch!
> New Welsh sentences

- server/data/de/countries-and-cities.txt
- server/data/de/jf99.txt
> more German language corrections

- server/data/eo/kastelo-de-prelongo.txt
Sentences from the start of _Kastelo de Prelongo_, of **Henri Valienne** (1854 - 1908)
https://eo.wikisource.org/wiki/Kastelo_de_Prelongo/%C4%88apitro_Unua
> new Esperanto sentences from old public domain novel

- server/data/cnh/chin-project.txt
Here are the first 1000 sentences from our Hakha Chin working group at IU.
> add Hakha Chin data from working group

- server/data/ast/Frases
As the Asturian team has translated the Common Voice's webpage, the same team (from Softastur the association account) uploads the first 100 phrases to add preliminary support for Asturian.
This phrases are extracted from one of the Asturian member's mind. We are in conversations to get more phrases from Academia de la Llingua Asturiana (Academy of Asturian Language). Right now we are reviewing phrases from a Asturian sayings book whose author relicensed it's creation
Let us know if there is some requirement which does not meet or is missing.
> Add preliminary support for Asturian

- server/data/nl/danielsjf.txt
> Fix spelling Dutch sentences

- server/data/nl/pcmill.txt
> Fix spelling errors in Dutch sentences

- server/data/de/jf99-batch01.txt
> add 250 more German sentences

- server/data/eo/proverbaro.txt
New Esperanto sentences from "Proverbaro Esperanta". This is a collection of Esperanto proverbs released in the year 1910. It is in the public domain, because the author has been dead for more than 100 years.
Only one sentence has been changed, the parenthesis have been removed from "Esti sub la ŝuo (de sia edzino)." because it would otherwise confuse a person trying to read it.
> New Esperanto sentences from "Proverbaro Esperanta"

- server/data/eo/chu-li.txt
A lot of new Esperanto sentences from the novel "Ĉu li?". Its copyright has expired so it is now in the public domain.
> New Esperanto sentences from "Ĉu li?"

- server/data/cnh/chin-project.txt
Here are all the sentences from the Chin group.
> add all sentences

- server/data/eo/chu-li.txt
- server/data/eo/krestomatio.txt
* Fixed parentheses.
* Added missing dot.
* Removed incomplete sentences.
* Fixed typo.
> Fixed some Esperanto sentences

- server/data/de/jf99-batch04.txt
Another 250 sentences reviewed by @Ordoviz.
> add jf99-batch04.txt

- server/data/de/jf99-batch01.txt
- server/data/de/jf99-batch02.txt
- server/data/de/jf99-batch03.txt
- server/data/de/jf99.txt
As resolved in the discussion at https://github.com/jf99/voice-web/pull/4 with @Ordoviz, the following words are substituted, so that they have a unified syntax:
- erstmal -> erst mal
- nochmal -> noch mal
> [German] mal-Wörter

- server/data/fr/vfvv1.1.txt
- server/data/fr/vfvv2.txt
- server/data/fr/vfvv3.txt
- server/data/fr/vfvv4.txt
- server/data/fr/vfvv5.txt
- server/data/fr/vfvv6.txt
https://framabook.org/vieux-flic-et-vieux-voyou/
> Importing french CC-0 book

- server/data/eu/argia01.txt
- server/data/eu/librezale01.txt
Sentences have been compiled and revised in this [wiki](https://librezale.eus/wiki/Common_Voice_proiekturako_bost_mila_esaldi_behar_dugu_jabetza_publikoan).
Take a look to the _history_ of that wiki page to see the corrections and improvements done during last two months.
> First 6.284 Basque sentences. Checked, fixed, cleaned and reviewed.

- nubis/terraform/main.tf
Taking the website into the present. 🎉
> Enable IPv6 dualstack for the website

- server/data/it/frasi.txt
Some found with the following pipeline:
cat frasi.txt  | aspell --lang it list | sort | uniq | less
cc @Mte90 @Sav22999
> data/it: fixup some typos

- server/data/eu/argia01.txt
- server/data/eu/librezale01.txt
Some corrections to Basque sentences after testing them in the beta sentence-collector.
For example, the Sentence Collector of Common Voice finally does not accept acronyms, so I removed them. I also did some other corrections and improvements to the Basque sentences.
> Some corrections to Basque sentences

- web/src/stores/demographics.ts
Spanish accents from https://en.wikipedia.org/wiki/Spanish_dialects_and_varieties#Sets_of_variants
> Spanish accents (from EN wikipedia)

- web/src/components/pages/contribution/speak/speak.tsx
Added keyboard shortcut (shift + clip number) to immediately re-record a line.
clip number indexed like 1,2,3,4,5.
solves #1768
> Added keyboard shortcut (shift + clip number) to immediately re-record a line

- web/src/components/pages/contribution/speak/speak.tsx
I had mistake this in previous PR.
> minor fix in code

- server/data/en/DNGros.txt
- server/data/en/DictionaryofForeignPhrases.txt
- server/data/en/est31.txt
This corrects some texts in the English files. There were often words missing or some words were capitalized for some reason.
> Correct some texts

- CODE_OF_CONDUCT.md
CPG full form added as not alteration allowed #1922
> CPG full form added as not alteration allowed 

- .gitignore
- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
Hi! I've solved the issue #1983 and added gitignore configuration for WebStorm Ide.
Thanks
> Fix for issue #1983

- web/src/hooks/use-active-section.tsx
Added root margin to intersection-observer such that change is triggerred when section comes at 20% height of screen, fixes issue #2001
> fix issue #2001

- web/src/components/layout/layout.tsx
- web/src/components/pages/about/nav.css
- web/src/components/pages/faq/faq.tsx
- web/src/utility.ts
Fix issue #2010 by allowing multiple FAQ questions to be opened at the same time on mobile. Make the sticky menu on About page go underneath the red bar on the staging site.
> Fix issue #2010 and the red bar on staging

- server/src/lib/clip.ts
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/services/api.ts
> saveclip at backend error handling

- nubis/terraform/metrics.tf
- nubis/terraform/variables.tf
Long story short, I added the wrong/old file, which was incomplete. It should be good now
> Fix broken Terraform code

- docker-compose.yaml
* Added a restart policy to Docker container db
* Added container names for better debugging
* Added spin up dependency of web container over db container.
> Made necessary changes to docker-compose configuration

- web/src/components/layout/user-menu.css
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
- web/src/components/pages/dashboard/stats/leaderboard.css
- web/src/components/pages/profile/avatar-setup/avatar-setup.css
- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
* use upload progress notification
* changes in position for mobile view
* voice wave animation in leaderboard
> * use upload progress notification

- server/src/lib/api.ts
- web/src/components/pages/profile/avatar-setup/avatar-setup.css
- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
> status upadte for first voice avatar recording

- web/src/components/pages/dashboard/stats/leaderboard.css
> fix min width for username in leaderboard

- web/src/components/layout/user-menu.tsx
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
Reverts mozilla/voice-web#2228
> Revert "add event name to avoid audio play on mouse leave as the playAvatar f…"

- web/src/components/notification-pill/notification-pill.css
- web/src/components/notification-pill/notification-pill.tsx
- web/src/stores/notifications.ts
@rileyjshaw Could you give me more requirements about the notification pills up-gradation? Now I add a type named `achievements` and set the background as blue. I don't know whether or not it is enough for the up-gradation.
> Upgrade notification pill for Open Voice Challenge

- CONTRIBUTING.md
Clarifies policies on PRs to address confusion raised in #2251
> Clarify contribution policy for localization content

- server/src/server.ts
- web/src/components/index.css
- web/src/components/layout/content.tsx
- web/src/components/pages/document-page.tsx
- web/src/components/welcome-modal/welcome-modal.css
- web/src/components/welcome-modal/welcome-modal.tsx
- web/src/services/api.ts
- web/src/urls.ts
Test plan:
- Navigate to localhost:9000/en/?challenge=pilot&team=mozilla
- Click "challenge terms" or "Terms & Conditions"
Common Voice Open Voice Challenge Legal Terms should appear (once
STOPSHIP is resolved)
Note: before merging this to `master`, we must ensure the corresponding
legal document exists in our `mozilla/legal-docs` repository as noted in
the `STOPSHIP` comment.
> Add Open Voice Challenge Terms & Conditions

- server/src/config-helper.ts
> Add emails to permitted ADMIN_EMAILS list per OI-1249

- web/package.json
- web/src/components/pages/dashboard/challenge/constants.ts
- yarn.lock
re: https://github.com/mozilla/voice-web/pull/2295
> Simplify date spoofing

- web/src/components/pages/dashboard/challenge/challenge-offline.tsx
- web/src/components/pages/dashboard/challenge/constants.ts
- web/src/components/pages/home/home.tsx
Fixes a bug where a null date caused a crash.
Also moves the challenge signup achievement to the challenge tab.
> Fix date and challenge signup notification

- server/src/lib/model/achievements.ts
- server/src/lib/model/goals.ts
earnBonus('three_day_streak'...) is a BUG before, it will return sooner than it should.
@rileyjshaw , suppose earn the bonus for every 3-day streak, not 5-day streak.
> earn three-day-streak bonus every time a 3-day streak is reached

- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/dashboard/dashboard.tsx
Fix issue https://github.com/mozilla/voice-web/issues/2319
> Fix #2319: Remove achievements items from session storage

- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/dashboard.tsx
- web/src/services/api.ts
Thanks to @can-007 for support 👍
> Check if user exists before making any API calls for challenge data

- web/src/components/pages/profile/info/info.tsx
Hopefully fixes our login redirect woes.
:fingerscrossed:?
> Comment out login redirect

- web/src/components/pages/dashboard/challenge/constants.ts
- web/src/components/pages/dashboard/dashboard.tsx
Also sets the default tab to /challenge for enrolled users, which should fix https://github.com/mozilla/voice-web/issues/2344.
> Hide /challenge route for users who aren't enrolled

- web/src/components/pages/dashboard/challenge/weekly-challenge.css
Now the achievements on challenge dashboard look like below: 
I have modified the styles in PR https://github.com/mozilla/voice-web/pull/2272. But the styles have been overwritten. So remove it again.
> Fix: Achievements display on challenge dashboard

- server/src/auth-router.ts
- web/src/components/layout/content.tsx
- web/src/components/layout/layout.tsx
- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/dashboard.tsx
- web/src/components/pages/profile/info/info.tsx
re: comments on https://github.com/mozilla/voice-web/commit/9e984e021debff09efe33ddece045b4898e096c3, a few of these `await` calls weren't actually `await`ing anything.
I'm going to look into cleaning up & simplifying the profile save behaviour. Before diving in, I wanted to restructure the code to indicate what's actually happening right now.
> Remove some bug vectors from profile's async submit / redirect flow

- web/src/components/pages/dashboard/challenge/challenge.css
- web/src/components/pages/dashboard/challenge/weekly-challenge.css
- web/src/components/pages/dashboard/dashboard.css
- web/src/components/pages/dashboard/dashboard.tsx
Fix issue https://github.com/mozilla/voice-web/issues/2376
> Fix #2376: Improve the challenge dashboard display on tablet

- server/src/lib/model/achievements.ts
Before the challenge:
- prevent multiple `invite_send ` bonus
- prevent multiple `invite_contribute_same_session ` bonus as well;
After the challenge:
- prevent `invite_send `and `invite_signup `bonus;
- multiple `invite_contribute_same_session `bonus can't be avoid with this PR;
Code change is mainly about adding ` AND (NOW() < TIMESTAMPADD(WEEK, 3, start_date))` in SELECT clauses to determine earn the bonus or not.
@rileyjshaw , @phirework , this should fix https://github.com/mozilla/voice-web/issues/2311.
I have created this PR to replace the other PR https://github.com/mozilla/voice-web/pull/2331. 
Because the original branch of that PR has conflicts that can't be solved locally, git reported errors like "`Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap …
> Fix #2311: Possible to get multiple invite_send achievements (NEW PR)

- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/challenge/weekly-challenge-board.css
- web/src/components/pages/dashboard/challenge/weekly-challenge.css
- web/src/components/pages/dashboard/challenge/weekly-challenge.tsx
Fix issue: https://github.com/mozilla/voice-web/issues/2374
> Fix #2374: Mobile challenge dashboard UI fixes

- web/src/components/welcome-modal/welcome-modal.tsx
Fixes #2356. Added account check to `welcome-modal.tsx` that enrolls and redirects directly.
> Tweak enrollment flow for logged-in users

- web/src/components/layout/footer.css
- web/src/components/pages/dashboard/challenge/challenge.css
- web/src/components/pages/dashboard/challenge/weekly-challenge-board.css
fix issue: https://github.com/mozilla/voice-web/issues/2375
> Fix #2375: Challenge dashboard leaderboard UI fixes

- server/data/it/frasi.txt
I removed all the sentences that we fixed in #2406 so this can be approved.
> Removed sentences from italian after #2406

- web/src/components/pages/dashboard/dashboard.tsx
- web/src/components/pages/login.tsx
- web/src/components/welcome-modal/welcome-modal.tsx
Based on PR comments on #2400 (thanks!!) 
* improved regex
* Moved redirect logic into separate method for readability 
* Correct referer value this time
* Incidentally solves (or...improves, I guess) the intermittent dashboard reload issue
Started a new PR instead of reopening that old one since it was already merged, didn't want to deal with conflicts or messiness.
> Better login redirect flow

- server/src/lib/model/db.ts
- use Date.now() instead of new Date().valueOf() to get millisecond of now;
- use `time zone designator`, plus 'Z' in the end, to initialize date to UTC time;
- extract millisecond computation of 3 weeks into one constant;
- local variable hasChallengeEnded is the same as the function name, change to challengeEnded;
@rileyjshaw , really good comments there ...
> refactor hasChallengeEnded:

- server/src/lib/model/db/migrations/20191128165627-weekly-achievements.ts
- server/src/lib/model/leaderboard.ts
> Add column to achievements table to specify week, alter queries

- web/src/stores/demographics.ts
Here is a list for breton accents (https://en.wikipedia.org/wiki/Breton_language#Geographic_distribution_and_dialects).
I took the #1064 PR as an example, tell me if I missed something.
> Add breton accents

- scripts/scrub-user.js
Thanks again for all your help 🙏
> async ALL the things

- nubis/puppet/files/confd/templates/river.toml.tmpl
> Exposes challenge-specific tables to be indexed for Kibana

- .travis.yml
- nubis/puppet/web.pp
- server/src/server.ts
Fixes #2480
Sneaking in:
- X-Release-Version
- X-Environment
> Move generation of security headers to node

- server/src/server.ts
- web/index_template.html
Also added a `prettier-ignore` to the `index_template` so that it wouldn't try to reformat the inline script and thereby mess up the CSP hash.
> add Fullstory tracking code, add CSP hash

- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/dashboard.tsx
- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
- web/src/components/pages/dashboard/goals/custom-goal.tsx
- web/src/components/pages/languages/localization-box.tsx
- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
- web/src/components/request-language-modal/language-autocomplete.tsx
- web/src/components/ui/ui.tsx
We updated prettier, and now it's time to face the consequences!
I guess this commit makes our code more ✨beautiiful ✨, but it also
opens us up to a bunch of merge conflicts. If you're not working on any
of these files, feel free to merge! But I totally understand if you'd
rather wait until something else has landed.
Mostly treating this commit as an FYI that we should do this eventually,
and next week might be a good time since code churn will be at 50% :)
To reproduce: `yarn prettier`
> Run prettier 😬

- locales/native-names.json
- web/src/components/language-select/language-select.css
- web/src/components/pages/about/get-involved.css
- web/src/components/pages/contribution/contribution.css
- web/src/components/pages/dashboard/stats/progress-card.css
- web/src/components/pages/dashboard/stats/progress-card.tsx
- web/src/components/pages/faq/faq.css
- web/src/components/pages/home/stats.tsx
This is mostly RTL and other localization CSS fixes, with a few minor tweaks. 
Localization bugs: 
* https://github.com/mozilla/voice-web/issues/2417
* https://github.com/mozilla/voice-web/issues/1917
* https://github.com/mozilla/voice-web/issues/2434
* https://github.com/mozilla/voice-web/issues/2205
Added Portuguese label:
* https://github.com/mozilla/voice-web/issues/2409
Show exact number of hours:
* https://github.com/mozilla/voice-web/issues/2436
> A bunch of github bugs

- web/src/components/pages/dashboard/challenge/constants.ts
- web/src/components/pages/dashboard/dashboard.tsx
The challenge pilot is over! No need to emphasize a blank tab :)
re: https://jira.mozilla.com/browse/OI-1370?workflowName=OI+Default+Workflow&stepId=1
> Stop defaulting to the challenge tab of dashboard

- server/data/fr/sentence-collector.txt
This is built on top of #2534, so please merge that one first. This adds the cleanup Alexandre introduced in https://github.com/Common-Voice/sentence-collector/pull/274
> Apply FR Cleanup Changes

- web/src/components/layout/nav.css
This fixes the issue for mobile users who can not see whole navigation drawers
> [mobile] User menu is not entirely accesible #1992

- README.md
Update readme with the link to the matrix room.
> Update with the Matrix room link

- web/src/components/layout/footer.tsx
Addresses https://jira.mozilla.com/browse/OI-1447
> Change pre-footer text from Help to FAQ

- server/src/lib/model/db/migrations/20200226094500-newsletter-sub-tables.ts
Doing these in phases so it's not just one unnecessarily big PR
> Update db schema with new table and populate it

- docker/Dockerfile
This will allow us to ship them to a central location
> Write logs to a file inside the container.

- server/src/config-helper.ts
- server/src/lib/model/db/mysql.ts
* Create a read-only pool to the replica node
* Always default to master node
* Implement routing for read/write queries
> Implement read/write isolation using different connection pools

- package.json
- server/src/config-helper.ts
* Undo revert regarding env/ssm setup
* Fix top-level package json `yarn start:prod` command
> Multiple fixes

- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
- web/src/components/pages/profile/settings/settings.tsx
- web/src/components/privacy-info.tsx
> fix(incorrect target anchor)

- web/src/components/layout/footer.tsx
- web/src/components/layout/layout.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/shared/links.tsx
> fix(target vulnerability issue):- added noopener, noreferrer

- server/src/server.ts
- web/index_template.html
- web/package.json
- web/src/components/app.tsx
- web/src/utility.ts
- yarn.lock
In preparation for instrumenting custom events, have moved Fullstory from just being an inline script to installing their full SDK. Also added Amplitude setup code - we don't have an API key right now, but it'll be in the same scope as FS tracking so I thought I'd handle it together.
> Update analytics packages

- web/src/components/pages/languages/languages.tsx
> Fix(Search Empty Value): added trim to query

- web/src/components/ui/icons.tsx
> fix(Svg-edit-icon)

- server/src/lib/model/db/migrations/20200406141259-sentence-tagging-structure.ts
Per discussion in: https://docs.google.com/document/d/1EJ2ngsJiqPJzb0pCRthKtAfXXXnqrsFuEbO3qesakjA/edit
> Add table schema in preparation for metadata work

- server/src/lib/model/db/migrations/20200420154137-benchmark-taxonomy.ts
> Add initial benchmark taxonomy

- web/src/components/layout/nav.css
> fix(divider issue in header)

- web/src/components/pages/datasets/dataset-info.css
- web/src/components/ui/icons.tsx
> fix(button icon disappear on hover)

- server/src/lib/model/db/migrations/20200406141259-sentence-tagging-structure.ts
- web/src/components/layout/layout.tsx
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/recording-pill.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/dashboard/challenge/leaderboard-card.tsx
- web/src/components/pages/dashboard/challenge/team-card.tsx
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
- web/src/components/pages/home/home.tsx
- web/src/components/pages/home/stats.tsx
- web/src/components/pages/languages/localization-box.tsx
- web/src/components/pages/profile/info/info.tsx
- web/src/components/plot/plot.tsx
- web/src/components/privacy-info.tsx
- web/src/components/request-language-modal/language-request-success.tsx
- web/src/components/share-buttons/share-buttons.tsx
Because it's Friday evening and there's 15 minutes before I pack up.
> Defragment the app

- server/src/fetch-legal-document.ts
> Create mapping between legal locales and on-site locales

- web/src/components/pages/contribution/success.css
- web/src/components/ui/icons.tsx
> Fix(Contribute More Icon Disappear Issue)

- server/src/server.ts
This Pull Request adds the same security headers used in production to other environments.
> Apply security headers in all environments

- server/src/server.ts
Should improve our [web security score](https://observatory.mozilla.org/analyze/voice.mozilla.org)
> Update path for contribute.json

- server/data/de/singleword-benchmark.txt
- server/src/lib/model/db/import-sentences.ts
- server/src/lib/model/db/import-taxonomies.ts
- server/src/server.ts
* Add function to import taxonomies automatically after
sentence import
* Generalize when to hash locale_id + sentence in sentence import
* Fix a German sentence problem per issue #2747
> Slightly firm up the taxonomy import process

- .github/ISSUE_TEMPLATE/feature_request.md
Apparently, we can have multiple templates for users to choose from, depending on the occasion. We have a bug report one, so let's add a feature request too.
> Add Feature request issue template

- server/src/lib/model/db/migrations/20200630083018-backfill-ssr-limits.ts
See conversation: https://mozilla.slack.com/archives/CG55XQM0Q/p1592324361084200 
cc @mbransn
> Add script to backfill minority languages for SSRL

- web/src/components/demo-pages/intro/intro.css
This PR fixes as scroll issue with the intro page at smaller break-points.
> fixes scroll issue with Intro page

- web/src/components/pages/dashboard/dashboard.css
- web/src/components/pages/dashboard/dashboard.tsx
This is a fix for the styling issue reported in #2791 .
> Bug fix: styling for dashboard language switch

- server/src/lib/model/db.ts
Straightforward blocklist implementation for which languages don't have the single sentence record limit from #2757 applied to them. Data on speaker #s comes from Pontoon and OI-1300.
> Add exemptions to SSRL for smaller language communities

- web/locales/en/messages.ftl
Fixes #2811 - @peiying2, just want to make sure that this is what you meant?
> Replace localized string with corrected closing html element

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/success.tsx
- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
- web/src/components/pages/dashboard/goals/custom-goal.tsx
This is a fix for the first localization issue stated in issue #2783
> bug-fix: localized text

- web/locales/en/messages.ftl
- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
@phirework I forgot to include some variables in some message strings from the other localization PR. This PR fixes the error.
> fixed ommitted vars and updated ids

- web/locales/en/messages.ftl
I added a missing ' and changed some wording to be a bit clearer
> fix some grammar

- web/src/components/demo-pages/intro/intro.css
Fixes the issue described in #2837.
> move waves up a bit

- web/src/components/demo-pages/kiosk/demo-datasets.css
this fixes the issue described in #2838
> give checkbox a dark background

- .travis.yml
`travis lint` has changed the file spaces
> Point travis to new Dockerhub mozilla/common-voice

- server/data/en/fxvoice-cues.txt
> Add FxVoice sentences

- web/src/components/app.tsx
- web/src/components/index.css
- web/src/components/pages/error-page/error-page.css
> Improve mobile error page styling

- web/locales/en/messages.ftl
- web/src/components/pages/dashboard/goals/custom-goal-steps.tsx
Since the plural form of the verbs depends on the number in the preceding value, I rolled them into the existing variables. Let me know if this is ok.
> Fixes localization issue #2832

- web/src/components/layout/content.tsx
cc @rileyjshaw - this may not be elegant, but it is more resilient than anything else I tried to alter the race conditions 😅
> Add redundant redirect fallbacks in Content.tsx for speak/listen

- web/src/components/ui/ui.tsx
Use `classNames` package to conditionally joining classNames together.
> Improve LinkButton component in ui.tsx

- package.json
- yarn.lock
> Pin dot-prop to 4.2.1+

- yarn.lock
Reverts mozilla/common-voice#2897
> Revert "Bump http-proxy from 1.18.0 to 1.18.1"

- server/data/ug/sentence-collector.txt
Have added a Luganda text-file with 5115 sentences for common voice
> Added luganda validated sentences

- web/src/components/pages/datasets/resources.css
> Fix(Image-over-nav-issue)

- README.md
DEVELOPMENT.md link was broken (the second one under how to contribute section) Hopefully this fixes it.
> Fix DEVELOPMENT.md link

- server/src/lib/model/db/migrations/20201030141754-tweak-taxonomy-structures.ts
The migration in #2925 produces the following SQL error:
```
[…]
web        | [BE] [INFO] Processed migration 20200629133018-track-dataset-version-download
web        | [BE] [INFO] Processed migration 20200630083018-backfill-ssr-limits
web        | [BE] [INFO] Processed migration 20200908153422-migrate-kurdish
web        | [BE] APPLICATION -- Maintenance error { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE)' at line 2
```
And after adding the comma before `TRUE`:
```
[…]
web        | [BE] [INFO] Processed migration 20200629133018-track-dataset-version-download
web        | [BE] [INFO] Processed migration 20200630083018-backfill-ssr-limits
web        | [BE] [INFO] Processed …
```
> Fix taxonomy tweaks SQL

- server/src/lib/model/db/scrub-user-activity.ts
- server/src/server.ts
> Scrub user activities older than 7 days upon deploy

- server/src/lib/api.ts
- server/src/lib/model/db.ts
- web/src/components/pages/datasets/dataset-info.tsx
- web/src/services/api.ts
* Fix incorrect dataset name being passed for singleword segment
* Do not write entry to db if no valid link has been generated
> Tweak dataset download logic to be more robust

- README.md
Add citation request, please feel free to change it. People struggle to find the citation, as in e.g. https://arxiv.org/pdf/2012.11896
> Update README.md to add citation information

- .github/workflows/build.yaml
- .github/workflows/test-application.yaml
- docker/Dockerfile
- package.json
- server/src/lib/model/db/schema.ts
Once we get this working, I'll follow up with cleaning up Travis CI references.
For this to work, we need to add credentials for pushing to the Docker Registry en Github. I don't have permissions for doing it. Let's do it together.
We can merge afterwards.
Closes #2963
> Use Github Actions for CI

- .github/workflows/build.yaml
- server/src/config-helper.ts
Travis was doing this, but since we moved to Github actions we lost this functionality. Now we want to add it back.
> Set X-Release-Version to commit SHA

- docker/prepare_s3.sh
Server store recordings in `CV_CLIP_BUCKET_NAME`, and the bucket create in s3proxy should have the same name, in this case `common-voice-clips`
This resolves #1859, #3009
> fix "NoSuchBucket" error in local deployment with docker

- docker-compose.yaml
- docker/prepare_s3.sh
- docker/wait-for-it.sh
- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20180910121256-user-sso-fields.ts
- server/src/lib/model/db/migrations/20191017134955-add-teams.ts
* Update MySQL version to match what's currently running on the server
* Fix MySQL syntax issues in migration startup
* Fix S3 Proxy link + race condition
> Update docker configuration

- web/src/components/pages/faq/selectors.tsx
> Update GH link to go to main branch

- web/package.json
- web/src/components/app.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- yarn.lock
If a first-time contributor tries to leave the contribution page before there are 5 full clips, the privacy modal interferes with the navigation prompt modal's redirect.
> Make sure partial submission modal closes on submit

- server/src/config-helper.ts
- server/src/lib/api.ts
- server/src/lib/bucket.ts
- server/src/lib/model/user-client.ts
- web/locales/en/messages.ftl
- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
* Specify public-read ACL for avatars
* Add some basic obfuscation to file name
* Delete old avatar
> Avatar upload improvements

- web/index_template.html
- web/src/components/index.css
Noto Serif language support list: https://www.fontsquirrel.com/fonts/noto-serif#font_description
Inter language support list: https://rsms.me/inter/#languages
> Switch to two other fonts with better alphabet support where applicable

- server/src/config-helper.ts
- server/src/lib/api.ts
- server/src/lib/aws.ts
- server/src/lib/basket.ts
* Added feature flag
* Wrapped activity functions using feature flag
* Added config objects for Cinchy
* Separately added SQS endpoint secrets to AWS Secrets Manager for
sandbox and stage
> Enable sending to Cinchy via SQS

- web/src/components/plot/plot.tsx
> Set ceiling of home stats graph closer to actual lang max

- web/src/components/pages/profile/settings/settings.css
> Allow email edit button to adapt to text length

- web/src/components/pages/contribution/speak/speak.css
- web/src/components/pages/contribution/speak/speak.tsx
> Fix the re-record button CSS to make it more consistent

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/ui/icons.tsx
> Document the Return key shortcut for submitting clips.

- server/data/lg/lug-batch-six.txt
Number of sentences : 978
QA error rate on random sample of 793 sentences : 0%
Reviews: [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/fbe31c932e514e4eabdfb8a9af4c7d996b8a03ae/batch-six/Ivan3-%20Sentence%20Verification%20Process.xlsx)
> Added a new batch of 978 Luganda sentences

- docs/COMMUNITIES.md
We use a bot to let people join the community that helps newcomers but also avoid spambot.
> Mozilla Italia Telegram changes on communities.md

- server/data/lg/lug-batch-five.txt
Number of sentences : 1016
QA error rate on random sample of 873 sentences : 0%
Reviews: [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/batch-five/Ivan2%20-%20Sentence%20verification%20process.xlsx)
> Added a new batch of 1016 sentences

- .github/ISSUE_TEMPLATE/language_request.md
Added_question regarding_language_script
> Added_question regarding_language_script

- server/data/lg/lug-batch-nine.txt
Number of sentences: 1000
QA error rate on random sample of 807 : 0%
Reviews: [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/a2cc3a173dbeaefa418df9d05a0a5d213ca9fec8/batch-nine/Ivan3-sentence%20verification%20process.xlsx)
> Added new batch of 1000 luganda sentences

- web/src/components/primary-buttons/primary-buttons.css
> Optimize opacity transition for Safari

- server/data/lg/lug-batch-sixteen.txt
Number of sentences : 545
QA error rate on random sample of 482 sentences : 0%
Reviews: [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/b05d4526b8eb16e20e798ed79ea24cd87da23b25/batch-sixteen/Validator%201%20-%20Sentence%20verification%20process.xlsx)
> Added a new batch of 545 sentences

- server/data/sw/wiki.sw.txt
Sentence Extractor Rules PR: https://github.com/common-voice/cv-sentence-extractor/pull/153
Sentence Extractor Extraction Pipeline: https://github.com/common-voice/cv-sentence-extractor/runs/3269649340?check_suite_focus=true
> Add Swahili Wikipedia Extract

- web/src/components/ui/icons.tsx
> Propagate className to chevron icon

- web/src/components/pages/contribution/speak/recording-pill.tsx
> Remove tooltip when playing complete

- docs/COMMUNITIES.md
Adding link to the Telegram chat of the Uzbek language community
> Added Uzbek language community link

- server/data/lg/lug-batch-twenty-nine.txt
Number of sentences: 8,337
QA error rate on a random sample of 2,833: 0%
Review [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/validations/batch-29/validatorx-%20Sentence%20verification%20process.xlsx) [2](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/validations/batch-29/validatorY-%20Sentence%20verification%20process.xlsx)
> added new 8,876 Luganda sentences

- server/data/lg/lug-batch-thirty.txt
- server/data/lg/lug-batch-twenty-nine.txt
Number of sentences: 2,175
QA error rate on a random sample of 1,429: 0%
Review [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/validations/batch-30/validatorX-%20Sentence%20verification%20process.xlsx) [2](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/validations/batch-30/validatorY-%20Sentence%20verification%20process.xlsx)
> Added new 2,175 Luganda sentences

- locales/discourse.json
The current list was last changed 16 months ago, so added the new ones to the list.
> Update list of sub-Discourses with lately created ones

- web/src/components/layout/layout.tsx
> Fix bug 3354

- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
> Fix bug where on-dashboard leaderbard visibility toggle deletes demo info

- server/src/lib/api.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20211125125633-skipped-clips.ts
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/report/report.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
- web/src/services/api.ts
Fixes #3350 and some secondary bugs 
* Handle edge cases where there are no more clips after a skip/report
* Add skipped_clips table and pull these out of rotation
* Fix validation on 'Other' reasoning for reports
>  Improve skip/report handling for validation 

- web/src/components/pages/home/stats.tsx
> Add precise hourly values to stats tooltip

- server/src/lib/model/user-client.ts
> On email change, remove old email prefs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
To help with triaging requests, I have made some suggested imporvements to the issue templates and created a pull request form.
Please let me know if you are happy to merge or would liek any changes.
> Issue Template and New Pull Request Form

- web/locales/cy/messages.ftl
- web/locales/de/messages.ftl
- web/locales/en/messages.ftl
- web/locales/hsb/messages.ftl
Malformed link tag in new About page content as stated in this issue here:
https://github.com/common-voice/common-voice/issues/3416#issue-1110076624
> Fixed malformed link in About page

- web/src/components/pages/home/stats.css
- web/src/components/pages/home/stats.tsx
Whenever hovering on the tooltip it would error. This PR attempts to fix this.
Check first commit. Rest is linting fixes.
> fix(tooltip): homepage errors on hover

- server/data/ca/frases_diccionaris_enciclopedia.txt
20k sentences from <a href="https://www.enciclopedia.cat/">"Diccionaris de l'Enciclopèdia"</a>.
[Link to the waiver](https://github.com/TeMU-BSC/catalan_CC0_sentences/blob/main/Common%20Voice%20ContributionAgmt%20-%20%5B1722573%5D%20-%20Enciclopedia%20Catalana.pdf)
Reviews:
- [annotator 1](https://docs.google.com/spreadsheets/d/10EdVrDsCltyO2p_-a4PlEp3xSeyhzd3KIYJPWXY2mdk/edit?usp=sharing)
- [annotator 2](https://docs.google.com/spreadsheets/d/1a-zG6QN0uiwM_CSbOy0TirjERQQ4tamoTZntVbKX-JQ/edit?usp=sharing)
> More Catalan sentences from Diccionaris de l'Enciclopèdia

- web/src/components/localization-select/localization-select.css
Globe was misaligned in Chrome/Safari
> fix(localization-select): globe icon misaligned

- web/package.json
- web/src/components/notification-banner/notification-banner.tsx
- web/src/components/pages/dashboard/challenge/challenge.tsx
- web/src/components/pages/dashboard/challenge/leaderboard-card.tsx
- web/src/components/pages/dashboard/stats/leaderboard-card.tsx
- web/src/components/pages/dashboard/stats/progress-card.tsx
- web/src/components/pages/dashboard/stats/stats-card.tsx
- web/src/components/pages/dashboard/stats/stats.tsx
- web/src/hooks/store-hooks.test.ts
- web/src/hooks/store-hooks.ts
- web/src/stores/user.ts
- yarn.lock
JIRA ticket: https://mozilla-hub.atlassian.net/browse/OI-2186
+ Refactor localStorage hook to be used in for `StatsCard`
+ Implement the hook into `StatsCard` for locale changes
+ Fix linting in files that PR touches
> feat(stats-card): remember locale options

- web/index_template.html
Linked to #3443 & #2861
I think we need to remove this share metadata too
> fix(metadata): remove description from head

- scripts/import-locales.js
- server/src/lib/model.ts
https://mozilla-hub.atlassian.net/browse/OI-2219
Due to upstream Pontoon changes, POST requests need to be moved to GET requests.
> Transform POST requests to GET

- web/src/components/pages/dashboard/stats/contribution-activity.test.tsx
- web/src/components/pages/dashboard/stats/contribution-activity.tsx
- web/src/services/api.ts
Fixes #3465
The existing component was no longer remounting for some reason after refactoring, so I have rewritten it to be how it should have probably always been.
Added a test so doesn't happen again.
> fix(contribution-activity): all contribution doesnt work

- web/locales/en/messages.ftl
- web/src/components/pages/profile/info/languages/input-language-variant.test.tsx
- web/src/components/pages/profile/info/languages/input-language-variant.tsx
We should make the default option for the variants something other than blank.
Thanks @mozgzh
> fix(profile): add value for default variant select

- web/locales/ca/messages.ftl
- web/locales/en/messages.ftl
- web/src/components/app.tsx
- web/src/components/error-slow-banner/error-slow-banner.tsx
- web/src/components/layout/layout.tsx
- web/src/components/notification-banner/notification-banner.css
- web/src/components/notification-banner/notification-banner.tsx
> feat(banner): slow website banner

- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/tables/clip-table.ts
- web/locales/ca/messages.ftl
- web/locales/en/messages.ftl
- web/src/components/app.tsx
- web/src/components/error-slow-banner/error-slow-banner.tsx
- web/src/components/layout/layout.tsx
- web/src/components/notification-banner/notification-banner.css
- web/src/components/notification-banner/notification-banner.tsx
We had some commits we sent directly to staging but we need to put them on main now.
> Sync performance changes to main

- web/src/components/notification-banner/notification-banner.css
> fix(banner): broken on medium viewport

- server/src/lib/model/awards.ts
- server/src/lib/model/leaderboard.ts
- server/src/lib/model/user-client.ts
the imports were failing for lodash on the server
> fix(lodash): imports on server failing

- web/src/components/app.tsx
Comment out status banner as platform remains stable
> Comment out status banner

- package.json
> Add more specific build scripts

- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/speak/speak.tsx
- web/src/stores/sentences.ts
+ If we run out of sentences make sure to allow it show it's loading again
+ Only show loading spinner if there is no current content showing
> Fix listen/speak loading states

- .env-local-docker.example
- server/src/config-helper.ts
- server/src/lib/bucket.ts
You'll need to add the following to your `.env-local-docker` file for this to work
```
CV_S3_LOCAL_DEVELOPMENT_ENDPOINT="http://localhost:9001"
CV_ENVIRONMENT="local"
```
> Fix listening to s3proxy files

- web/src/components/pages/datasets/dataset-download-email-prompt.css
- web/src/components/pages/datasets/dataset-download-email-prompt.tsx
- web/src/components/ui/icons.tsx
Fixes:
+ Checkboxes taking two clicks to check
+ Can't see styling on dark background
> Fix datasets page checkboxes

- web/src/components/pages/datasets/releases.ts
> Remove console.log from release code

- package.json
- yarn.lock
Update minimist
Remove unused or outdated resolutions
> Update dependancy resolutions

- .env-local-docker.example
- server/src/config-helper.ts
- server/src/server.ts
Not sure this is the solution. Need to see what ENVIRONMENT is set too in each environment it's not clear.
Update: I have checked PROD ENVIRONMENT is set as expected in our vairous deploys
> Use correct environment variable for local development

- web/package.json
- yarn.lock
Reverts common-voice/common-voice#3619
For some reason Typescript is throwing errors
> Revert "Update dependency @peculiar/webcrypto to v1.3.2"

- web/webpack.config.js
> Revert back to less annoying Webpack progress message

- common/language-stats.ts
- server/src/lib/model.ts
- web/src/components/pages/languages/languages.tsx
- web/src/components/pages/languages/localization-box.tsx
Shim the language page to use the newest data structure of language stats endpoint.
> Shim target sentence criteria

- server/src/lib/model.ts
Update endpoint to handle valid seconds for language stats
> Update count for seconds

- server/data/sw/sw-baratz.txt
- server/data/sw/sw-kibajuni.txt
- server/data/sw/sw-kimakunduchi.txt
- server/data/sw/sw-kimvita.txt
- server/data/sw/sw-kipemba.txt
- server/data/sw/sw-kitumbatu.txt
- server/data/sw/sw-kiunguja.txt
These are sentences for for sw-kiunguja, sw-kitumbatu, kiswahili cha bara ya tanzania(sw-baratz), sw-kipemba, sw-kimvita, sw-kimakunduchi and sw-kibajuni. These were created through a collaboration with linguists and local communities of native speakers.
*
*
*
*
* Kibibi Mohamed Amran
* Abdulrahman Ndegwa Karatu
* Dr. Mnata Resani
* Mwimbi Makobo Junior
* Britone Mwasaru
* Rebecca Ryakitimbo
* Kathleen Siminyu
> adding sw variant sentences 

- web/src/components/app.tsx
Got confirmation from localisation team this is unused code and doesn't do anything.
> Remove old Pontoon code

- web/locales/en/messages.ftl
Current copy excludes trans and disabled people and I think we can frame it around the people excluded instead.
> Make about copy more inclusive

- docs/LANGUAGE.md
*
*
* Documentation: updated language md to include sentance bands 
* 
*
*
> updated language md to include sentance bands

- server/src/csp-header-value.ts
- server/src/lib/api.ts
- server/src/lib/queues/processes/imageProcessor.ts
- web/locales/en/messages.ftl
- web/src/components/notification-pill/notification-pill.css
- web/src/components/pages/profile/avatar-setup/avatar-setup.css
- web/src/components/pages/profile/avatar-setup/avatar-setup.tsx
General improvements for uploading and controlling avatars. 
- Reinstated logic that allowed for gravatar and the ability to remove the avatar
- Added "Remove avatar" button
- Modified some styling to work with new button
- Improved errors/notifications
- Component now displays generic default avatar!
How it looks when you don't have an avatar:
How it looks when you have an avatar:
> Fix avatar uploads

- server/src/lib/lazy-cache.ts
Use the release version in the Redis key
> Invalidate Redis cache per release

- server/src/lib/model/db/import-locales.ts
- server/src/lib/model/db/import-sentences.ts
- yarn.lock
Find native names and save them to database and write them to translation file.
> Update import criteria

- web/src/components/app.tsx
- web/src/utility.ts
- Fixes erroneous sentry requests from development environments
- Lazy loads demo pages so assets aren't prefetched on load from different pages (e.g. no longer loads large .svg files which are never used, saving bandwidth)
> Improve frontend load times

- server/data/lg/lug-batch-thirty-one.txt
- [ X] Bulk sentence upload 
- Added 8,305 validated Luganda sentences
- Sample Size of 2,772 but all sentences were validated
- [Proof of validation](https://github.com/AI-Lab-Makerere/luganda-cv-validation/tree/master/validations/batch-31) of sample size (100% OK)
- Source of the sentences: Online News and Documents sourced from different content creators from Makerere University and Gambuuze News (Owned by Buganda Kingdom)
- License: All sentences uploaded are under CC0
Makerere AI Lab, Marconi Lab, Department of African Languages (Makerere University), Buganda Kingdom
> added 8305 sentences for luganda

- server/src/lib/model/db/migrations/20220706114233-dataset-10-db-entries.ts
- web/releases/cv-corpus-10.0-2022-07-04.json
- web/src/components/pages/datasets/releases.ts
Add metadata related to CV10 Dataset Release
> Add CV10 metadata

- server/data/lg/lug-batch-thirty-one.txt
- [X ] Bulk sentence upload
- Added 90,000 validated Luganda sentences 
- Source of Sentences: Created by the Community members and validated by Linguists 
- Licence: CC0 sentences
Link to the [lincense](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/LICENSE.md): 
More details on validation and sentence contribution can be found [here](https://github.com/AI-Lab-Makerere/luganda-cv-validation/tree/master/validations).
Validation [repository](https://github.com/AI-Lab-Makerere/luganda-cv-validation) for Luganda CV
*Marconi Lab
*Makerere AI Lab
*Department of African Languages (Makerere University)
*The Buganda Kingdom
> Added  90,000 sentences for Luganda

- web/src/components/pages/contribution/success.test.tsx
- web/src/components/pages/contribution/success.tsx
* Fixes #3726 
* I have created a test for this fix. However, I was unable to test it within my development server as I was unable to open `/[locale]/listen`. Feel free to let me know if there is any criteria for this PR to pass please.
> Fix incorrect link to goals page

- server/data/sw/batch-2-11-07-2022-contributors-set.txt
- server/data/sw/batch-3-17-08-2022-contributors-set.txt
- server/data/sw/sw-baratz.txt
- server/data/sw/sw-kibajuni.txt
- server/data/sw/sw-kimakunduchi.txt
- server/data/sw/sw-kimvita.txt
- server/data/sw/sw-kipemba.txt
- server/data/sw/sw-kitumbatu.txt
- server/data/sw/sw-kiunguja.txt
These sentences were created through a mini-write-a-thon organised by Britone Mwasaru. They are the second batch being uploaded from the one event. The first PR can be viewed [here](https://github.com/common-voice/common-voice/pull/3756)
All participants read and consented to the Common Voice Contribution Agreement.
They have been validated through collaboration with our team of community champions.
Spread sheets used for validation can be viewed [here](https://docs.google.com/spreadsheets/d/11ekWv-ulyb3p4a3uUmOXQK_A52jZ7VGf-L5HNl6u09w/edit?usp=sharing), [here](https://docs.google.com/spreadsheets/d/1rN2C6RN3hg6vfMY2aYyUTnvMXHptMzyi_Hk8w9nUsck/edit?usp=sharing), [here](https://docs.google.com/spreadsheets/d/1XAZdqDunRUz3ljSaVxZ-6kGngRMm7JRBVg9kFXovOI8/edit?usp=sharing), …
> Bulk Sentence Submission for Kiswahili - 4362 snetences

- docs/COMMUNITIES.md
*
*
Add Georgian community Facebook group link
*
*
*
*
> Add Georgian community FB group link

- web/src/components/index.css
Fixes top navbar glitch on mobile mentioned in #3404 
https://user-images.githubusercontent.com/113194143/189601096-9101107e-895b-4e2d-b85b-5ba4bbf1d588.mov
> chore: fix top navbar glitch on mobile

- docs/EMAIL.md
claryfing AWS to be understandable by newbies and fixing a typo.
* claryfing AWS to be understandable by newbies and fixing a typo.
*
*
*
> (very) small improvement as reading the file.

- server/src/lib/clip.ts
Remove user-supplied values from error messages
> Remove user supplied values from error messages

- server/src/lib/model/db/import-locales.ts
- server/src/lib/model/db/migrations/20220921114241-dataset-11-db-entries.ts
- web/releases/cv-corpus-11.0-2022-09-21.json
- web/src/components/pages/datasets/releases.ts
Add statistics file, add migration and update frontend to display CV11.
> CV11 Dataset Release 

- web/releases/cv-corpus-11.0-2022-09-21.json
> Fix download path for dataset

- docs/COMMUNITIES.md
> Add Cantonese community channel

- web/src/components/vars.css
* https://github.com/common-voice/common-voice/issues/3814
* shorten the transition-duration values for `prefers-reduced-motion: reduce`
> feat: respect reduce motion setting

- web/src/components/locale-helpers.tsx
- web/src/components/pages/profile/info/languages/input-language-name.tsx
- web/src/stores/languages.ts
- web/test/mock-react-redux-provider.tsx
Fix languages dropdown not showing language name but code.
> OI-2420 language list on profile not showing name

- web/index_template.html
Adds Google Tag manager to CV pages
> OI-2489: Add Google Tag manager to CV pages

- web/src/components/contact-modal/contact-modal.tsx
- web/src/components/modal/modal.tsx
- web/src/components/pages/profile/info/info.tsx
- web/src/components/pages/profile/info/languages/input-language-name.tsx
- web/src/components/pages/profile/info/languages/input-language-variant.tsx
- web/src/stores/languages.ts
[OI-1713](https://mozilla-hub.atlassian.net/browse/OI-1713)
Ensure buttons, forms and links have correct labels
> OI 1713 ensure buttons forms links have correct labels

- web/locales/en/messages.ftl
Adding missing translation bracket 
#3829
> Add closing bracket to translation

- common/language-stats.ts
- docs/API/statistics.md
- server/src/lib/api.ts
- server/src/lib/model.ts
- server/src/lib/model/statistics.ts
- server/src/lib/statistics.ts
- server/src/lib/validation/index.ts
- server/src/lib/validation/statistics.ts
Add statistics endpoint that provides a 12 month overview of the platform.
> OI-2427 Stats API work

- server/src/lib/model/db/migrations/20221101124213-add-delta-11-dataset.ts
Add CV11 Delta release! Also fixes a bad value for cv11 valid duration.
> CV11 Delta Release

- web/src/components/index.css
- web/src/components/layout/layout.tsx
* #3822 
Fixes the following:
- Back to top button not working on mobile
- Refixes top navbar glitch on mobile
> Fixes back to top button not working on mobile

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/contribution.test.tsx
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/listen/listen.tsx
- web/src/components/pages/contribution/report/report.tsx
- web/src/components/pages/contribution/speak/speak.tsx
Adding localisation for clip upload error messages and reporting img alt attribute. This closes #3859 and #3888
> Oi 2558 error messages should be localised

- web/locales/en/messages.ftl
- web/src/components/pages/datasets/dataset-download-email-prompt.css
- web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx
- web/src/components/pages/datasets/dataset-download-email-prompt.tsx
- web/src/hooks/use-copy-to-clipboard.ts
Fix text overflow in the datasets page on Android
https://user-images.githubusercontent.com/113194143/211592013-916e11fc-6fc9-4bbd-aa35-55868902a50e.mov
> OI-2559: Fix text overflow on android

- web/src/components/pages/contribution/speak/firstSubmissionCTA/firstPostSubmissionCTA.tsx
Fixes 404 link in first post submission CTA screen
> OI-2551: Fix 404 link in firstPostSubmission CTA screen

- web/src/components/layout/content.tsx
Redirects `/faq` page to `/about` page
> Redirect /faq page to /about page

- web/src/components/layout/nav.css
- web/src/components/layout/user-menu.css
- web/src/components/layout/user-menu.tsx
- Replace dot icon on the logged in profile dropdown with chevron down icon
- Replace hover styling on profile dropdown for logged in users
- Change text for login button to upper case
> OI 2589 & OI-2590

- web/src/components/index.css
- web/src/components/localization-select/localization-select-complex.tsx
- web/src/components/localization-select/localization-select.css
- Remove chevron down icon on the language dropdown
- Change content of localization dropdown to lower case and update design
> OI-2588: Update Localization dropdown styling

- server/package.json
- server/src/lib/clip.ts
- server/src/lib/model.ts
- server/src/lib/model/db.ts
- server/src/lib/model/db/migrations/20230124115524-add-duration-to-clips.ts
- yarn.lock
Calculating clips duration and adding it to the clips table
> OI-2524 feat: calculate duration of uploaded clips

- web/src/components/expandable-information/expandable-information.css
- web/src/components/expandable-information/expandable-information.tsx
- web/src/components/pages/contribution/speak/firstSubmissionCTA/firstPostSubmissionCTA.tsx
Fix arrow alignment on edit profile page
> OI-2610: Fix arrow alignment on edit profile page

- server/data/ca/pccd.txt
[Paremiologia Catalana Comparada Digital](https://pccd.dites.cat/) (**PCCD** for short) is an online collection of Catalan proverbs, idioms, and other sentences in Catalan made by [Víctor Pàmies i Riudor](https://refranys.wordpress.com/). This pull request is for adding the main PCCD dataset to Common Voice under the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license.
The original PCCD dataset is bigger. Here we are only adding the main, more general Catalan sentences ("paremiotipus"). Additionally, some sentences have been omitted:
- Sentences that are too short or too long.
- Sentences that contain inappropriate language.
- Sentences that already exist (or that are very similar) in existing Common Voice Catalan datasets. Note that the PCCD is already a "user" …
> Add PCCD Catalan dataset (CC0)

- server/data/sw/batch-2-10-03-2023-agriculture-set.txt
batch-01-10-03-2023-agriculture-set.txt
* Number of sentences: 4,655
* Correct sentences: 99%
* Error ratio from the QA: 1%
* Reviews: [1](https://github.com/twiga2/agricdataset/blob/master/Common%20Voice%20-%20Sentence%20verification%20process%20-%20Davis%20David.xlsx)    [2](https://github.com/twiga2/agricdataset/blob/master/Common%20Voice%20-%20Sentence%20verification%20process%20-%20Evarist%20Maguo.xlsx)
These are Tanzanian Kiswahili dialect sentences from the livestock and crop domain. Specifically, the sentences on livestock diseases cover cattle, small ruminants (goats and sheep), and camels. The livestock disease manuals were developed by the International Livestock Research Institute (ILRI), Kenya. These manuals were translated from English to Kiswahili by a professional …
> Kiswahili sentences bulk upload

- server/src/lib/model/db/migrations/20230124115524-add-duration-to-clips.ts
Fix for a broken migration - https://github.com/common-voice/common-voice/issues/4004
> Fix for migration on docker

- web/src/components/pages/contribution/speak/recording-pill.tsx
* https://github.com/common-voice/common-voice/issues/3925
The blob URLs do not work on Safari and Chrome on iOS phones, so users of these devices can't hear their own recordings Refactored self-recorded recording playback to use AudioContext. 
Tested on:
* iPhone, iPad
* Firefox, Chrome, Edge on Linux
* Firefox, Chrome, Edge on Android (phone and tablet)
> Refactored recording playback to AudioContext

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/contribution.css
- web/src/components/pages/contribution/contribution.tsx
- web/src/components/pages/contribution/speak/recording-pill.css
UI updates for speak and listen pages
This PR should be merged after #4009
> OI-2643: Speak/Listen pages UI iterations

- web/src/components/layout/nav/secondary-nav.tsx
Remove extra letter from secondary nav
> Fix: Remove extra letter from secondary nav

- web/src/components/modal/modal.css
Fixes report modal as mentioned in this issue - #4043
> OI-2715: Fix report modal on mobile

- server/src/lib/model/db/migrations/20230711121706-fix-citation-encoding.ts
Change encoding for source column to utf8
> Fix encoding for source column in sentences table

- server/src/lib/model/db/migrations/20230718102700-delete-unsuitable-hebrew-sentences.ts
> feat: add migration to delete unsuitable hebrew sentences

- web/locales/en/messages.ftl
- web/src/components/pages/contribution/sentence-collector/review/review.tsx
- web/src/components/pages/contribution/sentence-collector/review/use-review.ts
- web/src/services/api.ts
- Shows toast error message to users if they exceed the rate limit while reviewing sentences.
- Also refactors Review component by moving some logic to a custom hook
> OI-2740: Show toast to user for rate limit exceeded error

- web/src/components/pages/profile/layout.tsx
fixes #4153
fix: removed the unused variable
> fix: remove unused getProfileInfo variable

- web/src/components/pages/contribution/sentence-collector/write/bulk-submission-write/bulk-submission-write.css
- web/src/components/pages/datasets/dataset-corpus-download.tsx
- web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx
- web/src/components/pages/datasets/dataset-download-email-prompt.tsx
- web/src/components/pages/datasets/dataset-info.tsx
- web/src/components/pages/datasets/dataset-segment-download.tsx
Reverts common-voice/common-voice#4207
> Revert "staging-fix: upload zone styles"

- web/src/components/pages/guidelines/sidebar-content/voice-collection/example-content-voice.tsx
- web/src/components/share-buttons/share-buttons.css
- web/src/components/share-buttons/share-buttons.tsx
- web/src/components/ui/icons.tsx
fixes: #4165 
* #4165 
*
* I have updated the twitter icon to new XIcon and also renamed the previous XIcon to XMarkIcon
*
*
*
> fix: Update Twitter Icon to X #4165

- .github/CODEOWNERS
Adds Francis as code owner for .ftl files
> chore: add Francis as codeowner for ftl files

- web/src/stores/user.ts
Fix Typescript namespaces linting issue.
> OI-2807: 'fix' typescript issue in user store

- web/cypress/actions/review-page.action.ts
- web/cypress/e2e/bulk-submission-write-page.cy.ts
- web/cypress/e2e/review-page.cy.ts
- web/cypress/e2e/speak-page.cy.ts
- web/cypress/support/commands.ts
- web/src/components/pages/contribution/sentence-collector/review/review-card.tsx
- web/src/components/pages/contribution/sentence-collector/review/review.test.tsx
> OI-2800: Add e2e tests for review page

- web/cypress/e2e/legal-page.cy.ts
- web/src/components/layout/footer.tsx
> OI-2801: Add e2e tests for legal pages

- web/src/components/pages/contribution/sentence-collector/review/review.css
> Fix height of review card on mobile

- web/locales/en/messages.ftl
- web/src/components/pages/guidelines/constants.ts
- web/src/components/pages/guidelines/sidebar-content/sentence-collection/domain.tsx
- web/src/components/pages/guidelines/types.ts
> OI-2907: Add brief explainer about adding domain tags to your sentences

- docs/Sample Bulk Submission - Sheet1.tsv
*
*
Updating the bulk submission TSV example to reduce confusion.
*
*
*
*
> Replace bulk submission template

- web/src/components/pages/datasets/metadata-viewer/desktop/metadata-viewer.tsx
- web/src/components/pages/datasets/metadata-viewer/gender-splits.tsx
- web/src/components/pages/datasets/metadata-viewer/types.ts
> OI-2903: Update metadata viewer to sex or gender values

- web/src/components/pages/contribution/speak/speak.tsx
Reverts common-voice/common-voice#4393
> Revert "OI-2955: Increase max recording limit to 15 seconds"

- web/src/components/pages/contribution/report/report.tsx
- Adds data testid to report button for analytics
> Add data testid to report button

- web/src/components/pages/home/home.tsx
- web/src/components/primary-buttons/primary-buttons.css
- web/src/components/primary-buttons/primary-buttons.tsx
Add ids to record, play buttons on home page
> OI-2937: Add analytics to Home page

- server/src/lib/model/db/migrations/20240409142600-add-profile-variant-selection.ts
Adding a field to store whether the user wants to contribute to their variant only.
> feat: add field to store user's preferred variant selection

- server/src/lib/model/db/utils/getVariantsToBeUpdated.test.ts
- server/src/lib/model/db/utils/getVariantsToBeUpdated.ts
- server/src/lib/model/user-client.ts
This change enables the storage of the selected variant option on profile page.
> OI-3000: Update user_client endpoint to store the selected variant option

- server/src/api/sentences/handler/get-sentences-for-review-handler.ts
- server/src/application/sentences/repository/locale-repository.ts
- server/src/application/sentences/repository/sentences-repository.ts
- server/src/application/sentences/use-case/query-handler/get-sentences-for-review-query-handler.ts
- server/src/application/sentences/variants/repository/user-client-variants-repository.ts
- server/src/core/variants/user-client-variant.ts
Filter sentences to review based on user's variant preference selection on the profile page.
* feat: add function to repository to find a locale by locale id
* feat: add user client variants repository
* feat: add filter functionality for userClientVariant when reviewing sentences
* chore: add repository types
> OI-3069: Implement filter function for reviewing sentences based on the variant preference setting

- package.json
- server/jest.config.js
- server/src/server.ts
- server/src/test/lib/server-harness.ts
- yarn.lock
> fix: remove wrong mysql2 from dev dependencies

- common/taxonomies.ts
- server/src/core/domains/domain.ts
- web/locales/en/messages.ftl
- web/src/components/pages/guidelines/sidebar-content/sentence-collection/sentence-domain.tsx
> OI-3083: Update sentence domain dropdown list

- server/src/lib/model/db/migrations/20240510111500-update-domain-names.ts
Adjust domain names in the database:
- `food_service_retail` -> `service_retail`
- `agriculture` -> `agriculture_food`
- `automotive` -> `automotive_transport`
> OI-3082: Adjust domain names

- server/src/application/repository/sentences-repository.ts
- server/src/application/sentences/use-case/query-handler/get-variant-sentences-to-record-query-handler.ts
- server/src/application/sentences/use-case/query-handler/query/get-variant-sentences-to-record-query.ts
- server/src/core/sentences/filters/filterUserInteractedSentences.test.ts
- server/src/core/sentences/filters/filterUserInteractedSentences.ts
- server/src/lib/api.ts
Implementing filter function for speak page based on user variant preference settings.
> Implement variant filter function for speak page

- web/src/components/pages/contribution/sentence-collector/write/bulk-submission-write/bulk-submission-write.tsx
* This is a simple fix for the template link in the bulk submission page
Just me.
> Update the link to the bulk submission template

- docs/sample-bulk-sentences.tsv
added variant column
*
*
*
*
*
*
> updated example tsv

- server/src/lib/model/db/migrations/20240701104700-update-dataset-18-0.ts
- server/src/lib/model/db/migrations/20240701105400-update-dataset-18-0-delta.ts
- server/src/lib/model/db/migrations/20240701105500-update-dataset-18-0-stats.ts
The Georgian dataset was missing from the latest dataset release. This changed the totals of the release and that's we need to adjust the numbers.
> feat: add Georgian dataset and update totals

- docs/submitting-bulk-sentences.md
- web/locales/en/messages.ftl
- web/src/components/pages/contribution/sentence-collector/write/bulk-submission-write/bulk-submission-write.css
- web/src/components/pages/contribution/sentence-collector/write/bulk-submission-write/upload-zone-content.tsx
* https://github.com/common-voice/common-voice/issues/4530
*
*
* @jessicarose
>  Specify min 1000 sentences in bulk upload in Github docs and in bulk submission UI #4530 

- server/src/lib/model/db/migrations/2024082916140000-update-sentence-bands.ts
This is a sentence band migration for the languages being collected next week. Each of them should be band A.
> add sentence band migration for inhunuma languages

- server/src/api/bulk-submissions/routes.ts
- server/src/api/sentences/routes.ts
Add rate limit to small batch sentence submission (3 min) and bulk sentence submission (10 min)
> feat: add rate limit to bulk submissions endpoint

- .github/ISSUE_TEMPLATE/documentation_request.md
- .github/ISSUE_TEMPLATE/language_request.md
- .github/PULL_REQUEST_TEMPLATE.md
* Fixes various typos in the `.github` folder
* LanguageTool: "follow-up" is the noun form
* David Allison (myself)
> fix: documentation typos

- docs/COMMUNITIES.md
> [DOC] Add public Telegram channels for Circassian Languages in COMMUNITIES.md

- web/src/components/pages/contribution/sentence-collector/review/review.css
* [FIX] RTL layout for vote buttons
> [FIX] RTL layout for vote buttons

- web/src/components/pages/contribution/sentence-collector/write/write-container.css
* [FIX] RTL layout for write container toggle option
> [FIX] RTL layout for write container toggle option

- web/src/components/modal/modal.css
- web/src/components/pages/dashboard/goals/custom-goal.css
* [FIX] RTL layout for Custom Goals
> [FIX] RTL layout for Custom Goals

- web/src/components/pages/partner/partner-option-section.css
- web/src/components/pages/partner/partner.css
* [FIX] Correct RTL layout for partner section
**Screenshots**
> [FIX] Correct RTL layout for partner section

- web/src/components/pages/contribution/report/report.css
* [FIX] RTL layout for Report icons
**Screenshots**
> [FIX] RTL layout for Report icons

- web/src/components/pages/contribution/contribution.css
* [FIX] Minor RTL layout re-record message
> [FIX] Minor RTL layout re-record message

- web/src/components/pages/languages/languages-waves.css
* [FIX] RTL layout in languages wave
**Screenshot**
> [FIX] RTL layout in languages wave

- server/src/lib/model/db/import-locales.ts
As of now, the start-up script overwrites the `is_translated` database value just depending on the Pontoon translation ratio, even if a language was set manually to `is_translated=true`.
Sometimes we have to set the `is_translated` value manually to kick-start language contribution.
> feat: confer db to determine is_translated value

- web/src/components/pages/dashboard/dashboard.css
* [FIX] RTL Layout for Badge Navigation Bar
**Screenshots**
Before:
After:
> [FIX] RTL Layout for Badge Navigation Bar

- web/src/components/pages/dashboard/challenge/challenge.css
- web/src/components/pages/dashboard/stats/leaderboard.css
* [FIX] RTL layout for leaderboard overlay
**Screenshots**
Before:
After:
> [FIX] RTL layout for leaderboard overlay

- web/src/components/pages/dashboard/stats/leaderboard.css
* [FIX] RTL Text Layout for Leaderboard
> [FIX] RTL Text Layout for Leaderboard

- server/package.json
- server/src/@types/index.d.ts
- server/src/api/webhooks/handler/post-events-handler.ts
- server/src/api/webhooks/handler/post-fxa-events-handler.ts
- server/src/api/webhooks/routes.ts
- server/src/api/webhooks/validation/authenticate-fxa-event.ts
- server/src/lib/api.ts
- yarn.lock
Event handler to handle [Mozilla Accounts SET](https://mozilla.github.io/ecosystem-platform/relying-parties/tutorials/integration-with-fxa#webhook-events)
> 665 event handler hook for fxa

- web/src/components/pages/guidelines/guidelines.css
*  [FIX] RTL layout vote button direction in guideline section
>  [FIX] RTL layout vote button direction in guideline section

- web/src/components/pages/contribution/sentence-collector/review/review.css
* [FIX] RTL layout vote button direction
> [FIX] RTL layout vote button direction

- web/src/components/pages/about/playbook.css
* [FIX] RTL layout button direction alignment
> [FIX] RTL layout button direction alignment

- web/src/components/pages/dashboard/awards/awards.css
* [FIX] Minor RTL layout for star/wave
> [FIX] Minor RTL layout for star/wave

- web/src/components/pages/guidelines/guidelines.css
* [FIX] RTL layout adjust example circles in guideline section
> [FIX] RTL layout adjust example circles in guideline section

- server/src/application/sentences/use-case/command-handler/add-bulk-sentences-command-handler.ts
Just improving how the script handles non-conform header titles, i.e. shave off (mandatory) or (optional) and make all titles lower case.
> feat: normalize bulk submission headers

- server/src/lib/model/db/import-locales.ts
This PR is for @razmikb to speed up things during holidays...
Ref: https://en.wikipedia.org/wiki/Svan_language#Dialects
It has been worked with local linguists and decided to put subdialects as accents (as they actually are). They will follow in another PM.
For review by @ftyers :)
> Add Svan (sva) variants

- docs/COMMUNITIES.md
* Add Persian language community link
> Add Persian language community link

- server/src/lib/model/db/language-data/accents.ts
- server/src/lib/model/db/language-data/variants.ts
This PR is for @razmikb... It has been worked with local linguists.
For review by @ftyers 
From [this file](https://docs.google.com/document/d/1d63nxTAYZxtEpn54NG28xzG0FVhkjQINaL-jsrE8jnw/edit?tab=t.0#heading=h.vksihxgk9p9s):
> Add Megrelian (xmf) variants and accents

- docs/COMMUNITIES.md
I've added a link to the Persian CV Telegram group
N/A
> Add Persian TG group to communities list

- server/src/application/locales/use-case/query-handler/get-locale-messages-query-handler.ts
- server/src/infrastructure/fs/fp-fs.ts
Add translations for language names when spontaneous speech is requesting translation files.
> feat: add common translations to spont speech translations

- web/locales/spontaneous-speech/en/pages/common.ftl
Add key for request language button
> 866-request-a-new-language-buttonnavigation-in-ss

- docs/DEVELOPMENT.md
This is a very minor change to `DOCUMENTATION.md` to test that my `ssh` and `git` permissions are correctly established. 
Many thanks to @moz-dfeller for the pointers in the docs and for working through permission issues caused by Docker.
> Minor change to sentence importing docs to test Kathy's git permissions

- docs/COMMUNITIES.md
* Adds Discord details to [COMMUNITIES.md](COMMUNITIES.md)
> update COMMUNITIES.md with Discord information

- server/src/lib/api.ts
- server/src/lib/email.test.ts
- server/src/lib/email.ts
- server/src/lib/validation/send-language-request.ts
Adding the platform field to the language request email.
> feat: add platform to language request

- server/src/lib/model/db/language-data/variants.ts
#4727 add variants for Vietnamese (Tieng Viet)
> Add variants for `vi` to resolve #4727

- web/locales/spontaneous-speech/en/pages/common.ftl
> 882-update-dataset-picker-to-match-designs

- docs/COMMUNITIES.md
- Add/update Circassian social media channels
- Plus some minor other changes
> Add/update Circassian social media channels in COMMUNITIES.md

- server/src/lib/model.ts
- server/src/lib/model/db.ts
Add information about how many hours were voted as "incorrect"
> feat: add invalidated clips count to the language stats

- server/data/da/singleword-benchmark.txt
The correct Danish spelling of the number 3 is 'tre'
*
*
- [ X] Other
*
*
*
*
> Update spelling of the number 3.

- web/src/components/pages/contribution/sentence-collector/review/review-card.tsx
Fix for https://github.com/common-voice/common-voice/issues/4580
Detailed explanation is [here](https://github.com/common-voice/common-voice/issues/4580#issuecomment-2761791979)
> Fix source field not shown in review

- server/src/lib/model/db/language-data/variants.ts
For @ftyers ...
This is step 1 of 2
1. Add tvu-variants
2. Move existing data to tvu-ndikini
> Add tvu variants

- server/src/lib/model/db/language-data/variants.ts
- server/src/lib/model/db/migrations/20250521000000-set-empty-tvu-variants-to-tvu-ndikini.ts
For @ftyers
Step 2 of 2 (first #4901 should be merged/executed)
> Move existing tvu data to tvu ndikini

- web/locales/spontaneous-speech/en/pages/common.ftl
Fix for SS issue 423: ([BUG] Validate question tab is not translatable)
It is already in the code...
> Add validate key to ftl for Pontoon (SS-Navbar)

- README.md
- docs/CHANGELOG.md
Adds the file under docs and updates links in README.md.
> 1201-MCV - Create CHANGELOG.md file

- docker-compose.yaml
Create a second network to allow other Docker projects to connect their services to the `common-voice-network` and so communicate together.
> Add `common-voice-network` Docker network

- web/package.json
Add security override for stylus dependency
- https://github.com/stylus/stylus/issues/2938
- https://github.com/mrmckeb/typescript-plugin-css-modules/issues/287
> Fix for stylus causing builds to fail

- web/src/components/layout/footer.tsx
- web/src/components/ui/ui.css
Fixes https://github.com/common-voice/common-voice/issues/4867 which appears in some languages.
> Fix: Add left-aligned class to contact us button

- web/src/components/pages/profile/info/languages/input-language-name.tsx
Same idea in #5042 applied here...
> 1312-Workaround to fix language code shown on profile add language

- web/src/components/pages/profile/info/info.tsx
- web/src/components/ui/ui.tsx
The empty string age was not reflected to value field of select element, causing error in console.
> 1313-Fix profile page age field with empty value complaining

- server/src/lib/model/db/language-data/variants.ts
> Update variants.ts for `luo`

- web/src/components/pages/contribution/contribution.tsx
In Speak Page, the sentences array length is checked to see if they are loaded. In cases where communication is slow, they can be late, so the code fails with error. This PR adds a simple check before length check to handle the issue.
```ts
private get isLoaded() {
return this.props.sentences && this.props.sentences.length > 0
}
```
> 1317-Fix unchecked state in isLoaded

- server/src/lib/model/db/migrations/20250807180000-migrate-accents-variants-ca.ts
This PR should be merged after https://github.com/common-voice/common-voice/pull/5015
> 1279-Add Catalan accent-variant migration

- server/src/lib/model/leaderboard.ts
The LazyCache locks in dashboard page leader-boards do not get released for the "ALL" case. We suspect that it might be because of still providing parameters to those queries, where no parameter was expected.
> 1323-Refactor leaderboard queries so that parameters match for no-locale case

- server/src/lib/api.ts
Two fixes in server api:
- At one place after checking user, return statement was missing, causing code execution and errors
- At one place user was not correctly checked, causing errors.
> 1333-Fix missing return in response and user object check

- server/src/lib/api.ts
Fixes a bug I introduced (should handle not-logged-in users, not error out)
> Revert changes

- server/src/lib/api.ts
Reverses merged changes in https://github.com/common-voice/common-voice/pull/5073
Some of them were causing integration issues deep in front end tasks.
These should be reworked and well documented before further attempts.
It would be wise to:
- Re-group the API endpoints as protected/public (user logged-in status)
- Put some middleware to handle protected ones
CC: @sassela
> Revert changes to guards in 5073
